### ISSUE TITLE
Can't run npm install on project

### ISSUE THREAD

**Issue by schuchowsky** [missive/emoji-mart#10]
Hi! I've just forked your repo, in order to change the resulting Emoji component from two span's, to a img with background. 

I've already done it on the dist file and I'm using on my project, but I would like to create a PR for you. The emojis works better as img instead of span in a contenteditable div.

The problem npm is not able to install it.. Any ideas?
![image](https://cloud.githubusercontent.com/assets/13025585/18207416/8a702ad0-7101-11e6-8ccd-24fbde61dfb9.png)

**Comment by schuchowsky** [comment]
I'm sorry, it was taking just too long. Weird, took about 6 minutes. Thanks.

**Comment by iamsaksham** [comment]
Facing the same issue, I am waiting for like a few hours now. Its not getting installed yet.

**Comment by EtienneLem** [comment]
@iamsaksham Just released v0.3.0, it should be considerably faster to install.
