### ISSUE TITLE
How can I preload the sheet before actually rendering the picker

### ISSUE THREAD

**Issue by danfernand** [missive/emoji-mart#106]
I get a pretty noticeable lag in the original loading of any icon set. i tried using a smaller sheetSize but its still pretty noticeable, how can i preload this sheet to avoid this?

I can always render with display none but I'm adding in a tooltip so it would be slightly inconvenient to try to preload this way.

Thanks for the help!

**Comment by danfernand** [comment]
Anything on this one?

**Comment by EtienneLem** [comment]
Sorry, I could’ve sworn I had already answered your question.

You could use `Emoji.defaultProps.backgroundImageFn` to get the sheet URL and do an XHR request to preload it. That function requires 2 params: `set` and `size` respectively. Use the ones you’re using as props for `Picker` (they default to `apple` and `64` if you don’t provide any).

i.e.

```js
Emoji.defaultProps.backgroundImageFn('apple', 64)
// https://unpkg.com/emoji-datasource-apple@^3.0.0/img/apple/sheets/64.png
```
