### ISSUE TITLE
backgroundImageFn usage?

### ISSUE THREAD

**Issue by MovingGifts** [missive/emoji-mart#109]
I am not sure how `backgroundImageFn` works, I want to load the sheet from the cdn once, and then not hit the cdn again and just load the emojis from the sheet that was already fetched.

Is there any way to accomplish this?

**Comment by EtienneLem** [comment]
I believe this is actually fixed by ba1479e8b7619569a3ac8ae84c3adc98c51a9d6e. Browser should properly cache the sheet now that the emoji-datasource version is locked.
