### ISSUE TITLE
Require only necessary parts of CoreJS

### ISSUE THREAD

**Issue by ai** [missive/emoji-mart#112]
Right now EmojiMart requires whole CoreJS. And it is the huge dependency, about 15%.

Maybe we can require only some parts of CoreJS? What example ES6 methods do we use in EmojiMart?

**Comment by EtienneLem** [comment]
I’m not even sure which ones are needed nowadays. Original issue states `for..of` (https://github.com/missive/emoji-mart/pull/92). I’m wondering whether that is the only concern or there’s more to it. If it is, we could easily use good old `for` loops instead and drop `babel-runtime`.

**Comment by ai** [comment]
Hm. technically, we can rewrite `for-of` to old `for (var i = 0…)` to remove CoreJS completely.

**Comment by bniwredyc** [comment]
Hi, guys! I've done it: https://github.com/missive/emoji-mart/pull/113
