### ISSUE TITLE
Add custom assets

### ISSUE THREAD

**Issue by dimaslz** [missive/emoji-mart#114]
Hi, 

I thinks that could be good to pass a custom url to use custom sprite PNG. Some parameter like `sheetSource` or suggest me some name.

If is ok, I can do the PR for that.

Thanks!

**Comment by EtienneLem** [comment]
👋  Dimas,

It’s already possible with the `backgroundImageFn` props. Can either be a local or remote URL 🙌

**Comment by AlexandreBourdeaudhui** [comment]
Hello @EtienneLem 
Do you have an example for `local` ?

Actually, i'm trying with :
```js
backgroundImageFn={(set, sheetSize) => `./sheet_${set}_${sheetSize}.png`}
```
My assets is in same folder.

But doesn't work, idea ? :thinking:

**Comment by EtienneLem** [comment]
When local, the returned URL has to be relative to your HTML file, since it’s served over HTTP and not Node/JS. It’s used as an img `src`, so same constraint as any other img element you would use 😄

**Comment by AlexandreBourdeaudhui** [comment]
Thanks you @EtienneLem, i finally set images in folder `assets` with 
```js
backgroundImageFn={(set, sheetSize) => `/images/sheet_${set}_${sheetSize}.png`}
```
and its working, thank you !!!
