### ISSUE TITLE
Signify custom emoji elements with class

### ISSUE THREAD

**Issue by Gargron** [missive/emoji-mart#117]
There is no way to tell a custom emoji from a standard emoji in the CSS. Standard emojis use a spritesheet, while custom emoji use a single image. But because both are rendered the same, you can't style them differently to make sure custom emojis look correct.

**Comment by Gargron** [comment]
I believe essentially custom emojis need `background-size: contain` to look correct.

**Comment by EtienneLem** [comment]
Thanks, currently looking into that. Will try to add another class when custom too
