### ISSUE TITLE
Exclude a single emoticon

### ISSUE THREAD

**Issue by pinoytech** [missive/emoji-mart#121]
I want to know if there is something we can do to exclude single emoticons.

```
<Picker
  set='emojione' 
  removeEmoticon=[
    ':pensive'
  ]
/>
```

**Comment by EtienneLem** [comment]
👋 

You can use the `emojisToShowFilter` props:

```
<Picker
  set='emojione'
  emojisToShowFilter={(emoji) => emoji.id != 'pensive'}
/>
```

**Comment by thomasparsons** [comment]
```
  emojisToShowFilter={(emoji) => console.log(emoji.id)}
```
returns `undefined` now

you can use `emoji.short_names[0]` in it's place (or an extended version if they have multiple names)
