### ISSUE TITLE
Parse Emoji colons and Text both

### ISSUE THREAD

**Issue by Harshmakadia** [missive/emoji-mart#127]
Hello,

In order to display emoji we follow following syntax

`
<Emoji
  emoji=':+1:'
  size={64}
/>`

But if there is text along with emoji the above syntax fails to parse the text which is added along with the emoji. IS there any way to achieve this where if I write "**Hello World!** ":smile:"" will be automatically parsed.

In short this should be able to parse 
`
<Emoji
  emoji=':+1: Hello world'
  size={64}
/>`

and give this output :+1: Hello world

**Comment by Gargron** [comment]
This feature isn't meant to be used this way. Your text would be *inside* the Emoji component which is *not* what the component is for. But see #79 for the functionality that you do want (but will probably have to implement on your own)

**Comment by DasithKuruppu** [comment]
I came across a similar issue and ended up creating a npm package for it with a parser , the example shows how to intergrate emoji-mart into it [text-emoji-parser](https://www.npmjs.com/package/text-emoji-parser)

**Comment by nolanlawson** [comment]
This issue seems resolve externally, so closing. Please reopen as necessary, thanks!
