### ISSUE TITLE
Layout seems to be messing!

### ISSUE THREAD

**Issue by JikkuJose** [missive/emoji-mart#128]
Am I missing some configuration here? Just copy-pasted the default example & got this!

https://stackblitz.com/edit/emoji-mart?file=index.js

**Comment by EtienneLem** [comment]
👋 

You need to import the css too:

```js
import 'emoji-mart/css/emoji-mart.css'
```

Will make sure to update the examples.

**Comment by JikkuJose** [comment]
Can't it be done within the component so that it isn't something to be documented?

**Comment by JikkuJose** [comment]
Sorry, I know this isn't the place to ask such questions but it doesn't feel obvious how to use this! Can you check this out:

https://stackblitz.com/edit/emoji-mart?file=Demo%2Fcomponents%2FView.js

Could you let me know how to have the emoji placed in the text input? 

Loud thought: wish there was something like a Gitter tab for GitHub.
