### ISSUE TITLE
[Feature] Emoji only in categories if native is present.

### ISSUE THREAD

**Issue by rachitGulati** [missive/emoji-mart#13]
I want to render the emoji's in the sheet only if **native support icon** is present.
Can you please suggest where should I change ?.

**Comment by EtienneLem** [comment]
Do you have a few examples of emojis that wouldn’t have a native version? I guess it mostly depends on the device/OS. It would help to to know which ones aren’t supported on what device to test the implementation.

We could add a `onlyIfNativeIsSupported` props to the Picker component.

**Comment by rachitGulati** [comment]
So in the image below you can see inside the native there is "🙃" instead of emoji face. I am on Mac OS X Yosemite with Chrome  53.0.2785.

![screenshot 2016-10-04 11 18 01](https://cloud.githubusercontent.com/assets/9318393/19063922/6ec05fa8-8a24-11e6-984a-727255b25319.png)

And there are many emoji which are showing this. I am currently using apple sprite. I wanted the native emoji to be shown in my textArea or in input field.

Is there any hotfix for this ? Can you guide me what should I do for it ?

**Comment by rachitGulati** [comment]
@EtienneLem Any update ? I am sorry I keep bothering you but it's a bit urgent for me :( . It would really appreciate any help.

**Comment by EtienneLem** [comment]
So I gave it a go, but it doesn’t seem to work.
Check out https://missive.github.io/emoji-mart and check the `excludeUnsupportedNativeEmojis` checkbox, the Upside-Down Face is still there, correct?

**Comment by rachitGulati** [comment]
I don't know what you have fixed but it seems to be working now at least in your demo . Showing right value for 'native' property of the object inside the console. Don't think so checkbox is even working.

**Comment by rachitGulati** [comment]
Closing this issue as it is not reproducing any more :)

@EtienneLem thanks for fixing it :)
