### ISSUE TITLE
Searching with "_" and "-" leads to inconsistent results

### ISSUE THREAD

**Issue by nolanlawson** [missive/emoji-mart#131]
There's a slightly surprising situation where if you search for e.g. `thinking_fac` you won't get `:thinking_face:`, or if you search for `woman-facepalm` then you won't get `:woman-facepalming`:

![out](https://user-images.githubusercontent.com/283842/31289013-29c73c18-aa7c-11e7-99e7-5001434a66da.png)

This seems to be due to how we split on `-` and `_` characters, but the fix isn't straightforward so I haven't opened a PR yet.

**Comment by nolanlawson** [comment]
I don't have a PR yet, but here's a test to repro the issue: https://github.com/nolanlawson/emoji-mart/commit/f47a9ffc355de7b5a8855dbedc3b3c5c2874d89b

**Comment by EtienneLem** [comment]
🤔 Must’ve been a regression at some point, searching for `thinking-face` and `thinking face` should have exactly the same search results. It used to work, will look into.

**Comment by nolanlawson** [comment]
Sweet! Nice fix. :tada:
