### ISSUE TITLE
Error when passing emoji name that does not exist

### ISSUE THREAD

**Issue by dlochynski** [missive/emoji-mart#134]
Hey, I have updated my project dependency to 2.1.1. Once I pass emoji name that does not exist in emoji set, for instance "test" there is an error occurring: 
`index.js:116 Uncaught (in promise) TypeError: Cannot create property 'custom' on string 'test'`

I got through the code and found something that I did not understand in (I checked the changelog and saw some changes being done in that file) _emojimart/src/utils/index.js_
```

if (!Object.keys(emojiData).length) {
    emojiData = emoji;
    emojiData.custom = true;
    if (!emojiData.search) {
      emojiData.search = buildSearch(emoji);
    }
  }
```

When emojiData object is empty it means that the emoji is a string that did not match anything. What the code does is assigning to the emojiData variable a string that can't have property 'custom' assigned to, because it's not an object anymore.

I was working with previous versions and it was working ok , but I had different problems that shouldn't be important now.

Is that something that was planned to do? Can you explain that?

**Comment by dijonkitchen** [comment]
FYI, you can use the `emojiIndex` noted [here](https://github.com/missive/emoji-mart#headless-search) for a check on if the emoji exists first.
