### ISSUE TITLE
Fails on SSR

### ISSUE THREAD

**Issue by adam-26** [missive/emoji-mart#136]
Hi,

The `measureScollbar()` utility method uses the `document` object that is not available on nodejs.
[See it here](https://github.com/missive/emoji-mart/blob/master/src/utils/index.js#L172).

This causes the error `ReferenceError: document is not defined` when rendering is attempted on nodejs.

Adam.

**Comment by wayne1203** [comment]
Is it the same problem?
![2017-10-26 2 21 35](https://user-images.githubusercontent.com/8578341/32037682-ff3487c0-ba58-11e7-8b04-363a6c7871b4.png)

**Comment by adam-26** [comment]
@wayne1203, looks like it is the same problem

**Comment by wayne1203** [comment]
@adam-26 Are you using RN 0.49 too??

**Comment by EtienneLem** [comment]
v2.1.2 has been released, let me know if you’re still having issues with SSR.

**Comment by iksent** [comment]
document is not defined
ReferenceError: document is not defined
    at _convertStyleToCSS (C:\Programming\gramkit\node_modules\emoji-mart\dist\components\emoji\nimble-emoji.js:94:13)

Using it with Next.js:

```
import { getEmojiDataFromNative } from 'emoji-mart/dist/utils'
import NimbleEmoji from 'emoji-mart/dist/components/emoji/nimble-emoji'
import appleEmojis from 'emoji-mart/data/apple.json'
import emojiRegexp from 'emoji-regex'

export const unicodeEmojiRegexp = emojiRegexp()

const prepareText = (content: string): string => {
  return content
    ? content
        .replace(unicodeEmojiRegexp, (emoji: string) => {
          const emojiData = getEmojiDataFromNative(emoji, 'apple', appleEmojis)
          return !emojiData
            ? ''
            : NimbleEmoji({
                data: appleEmojis,
                html: true,
                emoji: emojiData,
                skin: emojiData.skin || 1,
                set: 'apple',
                size: 18,
                sheetSize: 32,
              })
        })
        .replace('<a href', '<a target="_blank" href')
    : '-'
}

const EditorPostViewer = (props) => {
  const { text } = props

  return (
    <div dangerouslySetInnerHTML={{ __html: prepareText(text) }} />
  )
}
```
