### ISSUE TITLE
Emojis are too close to each other in textarea

### ISSUE THREAD

**Issue by imakou** [missive/emoji-mart#137]
Hi,

First of all, I like this react component, which is awesome.
I use it in my project as an option for typing.
But I face a problem is that emojis are too close to each other.
I'd like to know if there is any way to adjust emojis' margin in textarea?

Thanks.
![screen shot 2017-10-20 at 11 34 06 am](https://user-images.githubusercontent.com/1507950/31829315-e75c7c16-b58a-11e7-9cce-c9283f300eec.png)

**Comment by EtienneLem** [comment]
👋 Given you’re adding emojis in a textarea, I’m guessing you’re inserting the `native` (unicode) into the textarea? In which case, it really comes down to your textarea CSS and the way your browser / OS renders emojis. EmojiMart can’t really help you there, you would get the same result would these emojis be added from your OS native emoji menu.

> I'd like to know if there is any way to adjust emojis' margin in textarea?

I’m not aware of a way to isolate emoji characters with CSS 🤔.
From your screenshot it looks like these would be affected by a negative `letter-spacing` or an equivalent, is that possible?
