### ISSUE TITLE
Accessibility Tooltip prop not working

### ISSUE THREAD

**Issue by taygrave** [missive/emoji-mart#139]
As indicated here, https://github.com/missive/emoji-mart/#emoji, it should be a matter of simply passing in `tooltip=true` prop to the `Emoji` component to get the tooltip to show up, however it is not working, there is no change on hover despite a `true` `tooltip` prop.

Might be a problem with the `short_names`?

**Comment by taygrave** [comment]
This same bug is also true of the `Picker` component prop: `emojiTooltip`

**Comment by EtienneLem** [comment]
👋

The `tooltip` props hasn’t been released yet (I thought it was 😅). I’ll try to do that ASAP, there are a few other issues/PRs that I wanted to merge too.

**Comment by dijonkitchen** [comment]
Might want to keep this issue open until it's been released.

**Comment by EtienneLem** [comment]
Sure, good idea!

**Comment by EtienneLem** [comment]
v2.1.2 now released.
