### ISSUE TITLE
Error if the emoji doesn't exist

### ISSUE THREAD

**Issue by DonovanCharpin** [missive/emoji-mart#14]
Hi guys

I tried to use the Emoji component with an emoji that doesn't exist.

For instance, with `:thumbsup:`, it doesn't work : 
```
<Emoji
          key={i}
          sheetURL={'/images/sheet_apple_32.png'}
          emoji={{ id: 'thumbsup', skin: 3 }}
          size={20}
        />
```
I have this error in the console : 
```
emoji-mart.js?78ec:1041
Uncaught TypeError: Cannot read property 'skin_variations' of undefined
```

**Comment by DonovanCharpin** [comment]
Seems to be in the `utils/index.js`. It missing a check : https://github.com/DonovanCharpin/emoji-mart/commit/eb189673392a0e919facd7333ba7d1be7bffcf9a.

I don't know why but I wasn't able to import my fork with npm to test it but pretty sure the error is in `getData` if `emojiData` is `undefined`.

**Comment by EtienneLem** [comment]
Yes, pretty easy to reproduce indeed. Thanks, will fix ASAP.

**Comment by DonovanCharpin** [comment]
Great, just waiting that to push the feature in production. Thanks
