### ISSUE TITLE
sticker support?

### ISSUE THREAD

**Issue by krsnaa** [missive/emoji-mart#140]
sticker support?

**Comment by EtienneLem** [comment]
Any images (even GIF) could work w/ the `custom` prop, see https://github.com/missive/emoji-mart#custom-emojis

**Comment by krsnaa** [comment]
Thank you @EtienneLem.  Is it possible to have multiple custom-category tabs - or in other words, create separate groupings of custom emojis/images?

**Comment by EtienneLem** [comment]
Not at the moment, but that’s a good suggestion.
