### ISSUE TITLE
No Emoji Found is not being translated

### ISSUE THREAD

**Issue by adferras** [missive/emoji-mart#142]
Even though we have populated translations for "No Emoji Found", emoji-mart is not using them.

Here are our translations:
<img width="278" alt="screen shot 2017-11-07 at 2 11 28 pm" src="https://user-images.githubusercontent.com/7363177/32518025-971122b8-c3c5-11e7-885b-33747893e74e.png">

Here you can see that `search` and `select` is using our translations, but not `No Emoji Found`.
<img width="304" alt="screen shot 2017-11-07 at 2 09 36 pm" src="https://user-images.githubusercontent.com/7363177/32517991-79b25b88-c3c5-11e7-8367-326baad2d7e4.png">

The text is definitely being used via https://github.com/missive/emoji-mart/blob/35c05eb62d1dbf683c3a3f228a05b1df177dc181/src/components/category.js#L201, but we are unable to override it with our own translation.

**Comment by EtienneLem** [comment]
🤔 Will look into, thanks!

**Comment by EtienneLem** [comment]
Ah! Pretty sure you’re actually using an outdated version, here’s how it looks now:

<img width="349" alt="screen shot 2017-11-07 at 7 24 22 pm" src="https://user-images.githubusercontent.com/436043/32530163-51b91bcc-c3f1-11e7-8ce0-9641c441b753.png">

I recall `notfound` being overlooked at first, see 046d489d7ff23f70867744fe4f57d11234a7f087
