### ISSUE TITLE
Invalid emoji name in `Emoji` component crashes

### ISSUE THREAD

**Issue by buoyad** [missive/emoji-mart#143]
See example here: https://codesandbox.io/s/50yjo02m5k

Passing the name of an invalid emoji to `Emoji` crashes the app. This causes bugs that are hard to workaround on the implementation side, especially in cases where users can enter emoji names directly. 

In particular, if this [function](https://github.com/missive/emoji-mart/blob/master/src/utils/index.js#L61) didn't assume that raw strings passed in are already valid emojis, the error could be bubbled up & handled/logged rather than causing a full crasher.

Thanks for the library!

**Comment by EtienneLem** [comment]
There you go, `v2.2.1` has just been released: https://codesandbox.io/s/j2ropwx35v

**Comment by buoyad** [comment]
Oh, thank you for the quick response/release!
