### ISSUE TITLE
Incorrect rendering in native mode depending on browser

### ISSUE THREAD

**Issue by Kovensky** [missive/emoji-mart#144]
I am looking into using `native` emoji to avoid having to download megabytes of spritesheets (and nudge users into upgrading their OSes 😉); but I'm getting some really weird cases of inconsistent rendering on the widget and I have no idea on what is the cause or the solution.

For example, here are captures from the demo page at https://missive.github.io/emoji-mart/:

Firefox | Safari (the only working example)
--- | ---
<img width="357" alt="image" src="https://user-images.githubusercontent.com/73085/32818416-89c4ac0a-ca06-11e7-83bf-a08c9a900be5.png"> | <img width="359" alt="image" src="https://user-images.githubusercontent.com/73085/32818441-b810db56-ca06-11e7-9fa8-095718953427.png">

The situation gets even more confusing and chaotic when I actually try embedding it in my webpage:

Firefox (same issue) | Safari (wtf)
--- | ---
<img width="359" alt="image" src="https://user-images.githubusercontent.com/73085/32818497-117ddad6-ca07-11e7-803c-b764df28861a.png"> | <img width="359" alt="image" src="https://user-images.githubusercontent.com/73085/32818509-23ce455e-ca07-11e7-8d86-6aedad322417.png">

At first I thought this could be a problem related to my global styles, or even the font being used, but no matter how many styles I toggled off I still got the crazy results in Safari. Not sure where to go from here, other than giving up on native.

**Comment by EtienneLem** [comment]
On what OS and version? It looks like there are a lot of unsupported emojis. Not setting a skin tone in your case would probably fix the layout issue.

On Missive we actually gave up on trying to use native on desktop, as there are a lot of variables that you can’t control (unsupported emoji, unsupported skin tone, etc) 😅. That allows us to give the most up-to-date emojis even if the users have an outdated OS.

Emoji Mart is currently using [Emoji Version 4.0](https://emojipedia.org/emoji-4.0/) which was released on November 28, 2016. [Version 5.0](https://emojipedia.org/emoji-5.0/) will eventually be used (see https://github.com/iamcal/emoji-data/pull/100).

**Comment by Kovensky** [comment]
Oh, this was macOS 10.13.1. The tests were done with Firefox 58.0b4 (Developer Edition) and Safari Technology Preview (44). Setting the skin tone was done specifically to test how it would look with a skin tone set 😅 

It works fine with the Apple sprite sheet, which is why I found especially strange when using `native` made it look that broken (on anything but the demo page with Safari).

**Comment by Kovensky** [comment]
A friend helped me debug this, and these are some things I've learned. They each depend on the browser being used.

Chrome: our html `:root` has a `lang` attribute that is set to `"jp"` for most users. Setting the `lang` to any tag that is _not_ recognized as a valid `lang` (say, `lang="zzzzz"` or `lang=""`), or set it to `en`, actually makes it render correctly. The `lang` tag can be set locally, so it might be worked around by `emoji-mart` through setting `lang=""` on the `span`s that render emoji. This is likely a Blink bug.

Safari: We have a global `div { word-wrap: break-word; }` reset. Disabling it, or setting it to `normal` in `.emoji-mart-category, .emoji-mart-preview-emoji` made the emoji combine correctly in it, regardless of the `lang` settings. It did nothing on Chrome, though; only `lang` worked there.

I could not find anything that would work on Firefox.

**Comment by vget98** [comment]
Any update on this problem?

**Comment by EtienneLem** [comment]
There’s nothing much we can do about browsers not supporting some native emojis, especially when it’s the result of the addition of 2 supported emojis that isn’t. For example: ✌️ + 🏻 = ✌🏻. Some browsers (on outdated OS) will render it like so:
<img width="43" alt="screen shot 2018-01-25 at 10 47 24 am" src="https://user-images.githubusercontent.com/436043/35397337-38daeb4e-01bd-11e8-96fd-823b6ff1155e.png">

I would suggest not using the native set when you don’t control in which environment it is displayed.
