### ISSUE TITLE
dubious incompatible change

### ISSUE THREAD

**Issue by leoliu** [missive/emoji-mart#149]
I have a Picker like this:
```
<Picker include={includes}/>
```

In version 2.2.1 `includes` looks like this and works:
```
const includes = [
  "people",
  "nature",
  "foods",
  "activity",
  "places",
  "objects",
  "symbols",
  "flags",
  "custom"
];
```

That fails on v2.3.0.

**Comment by EtienneLem** [comment]
You’re right! Sorry for the delay, `v2.4.0` has just been published.
