### ISSUE TITLE
<Picker native /> has lots of duplicates

### ISSUE THREAD

**Issue by leoliu** [missive/emoji-mart#150]
Look at this screenshot on iOS 11.2

![1513396560579](https://user-images.githubusercontent.com/406907/34067137-4295465e-e258-11e7-854b-2a0918b6aa6e.jpg)

**Comment by EtienneLem** [comment]
👋 

These are actually all different, unicode-wise. For example the vampires: First one is `:vampire:`, second one is `:female_vampire:` and third one `male_vampire`.

https://emojipedia.org/vampire
https://emojipedia.org/woman-vampire
https://emojipedia.org/man-vampire

Same thing for `:mage:`, `:fairy:`, `:merperson:`, `:zombie:`, `:elf:`, etc.
