### ISSUE TITLE
Unsupported emojis should render the shortcode

### ISSUE THREAD

**Issue by ajbeaven** [missive/emoji-mart#157]
I've found that :shrug: doesn't seem to render anything when using the messenger set:

```
<Emoji
    emoji={':shrug:'}
    sheetSize={32}
    size={32}
    set="messenger"
    backgroundImageFn={(() => require('../../../assets/img/emoji-messenger-32.png'))}
/>
```

Presumably this is because the messenger set doesn't support this emoji? In my opinion, it's better to render _something_ rather than nothing. I'd suggest using the raw shortcode passed in to the emoji.

**Comment by savardc** [comment]
We're also having this issue. I'm ok with rendering the shortname or maybe add a callback?

**Comment by EtienneLem** [comment]
Went the callback way, as picker still requires unsupported emojis to be ignored. Here’s how you would render `:shrug:` when unsupported:

```js
<Emoji
  set={'messenger'}
  emoji={'shrug'}
  size={24}
  fallback={(emoji) => {
    return `:${emoji.short_names[0]}:`
  }}
/>
```

I hope that’s good enough 😄

**Comment by ajbeaven** [comment]
Woah, that was crazy fast. Thanks heaps!
