### ISSUE TITLE
Missing emojis are still `rendered` causing layout issues

### ISSUE THREAD

**Issue by pederjohnsen** [missive/emoji-mart#160]
Missing emojis are still `rendered` in the picker causing layout issues
![https://i.imgur.com/PCMHkXl.png?1](https://i.imgur.com/PCMHkXl.png?1)

It seems weird to render them if there is no emoji to display.

**Comment by ajbeaven** [comment]
I think perhaps #158 will resolve this. It's merged but not yet released.

**Comment by EtienneLem** [comment]
These are native emojis, correct? There’s not much we can do to prevent that from happening. Support is different depending on the OS and browser being used, so it needs to be tested at runtime. There’s a branch (https://github.com/missive/emoji-mart/tree/exclude-unsupported-native-emojis) with an experiment, but it has proven not to be 100% reliable and most likely poor for performance. It requires writing and reading dataURL from a canvas for each emoji.

Using native emojis is much faster and always look sharper, but unfortunately has important drawbacks.

@ajbeaven Oh thanks for the reminder, I’ll do that today.
