### ISSUE TITLE
only include the first n emojis .. how ?

### ISSUE THREAD

**Issue by vesper8** [missive/emoji-mart#161]
I want to only include the hearts from the "symbols" category for example, or only include the first 40 emojis from the "people" category

I know I can use the emojisToShowFilter for this but it would be quite a lot of code to filter out all of the emojis I don't want to include

is there another way? Ideally I would like to be able to include people:40 and symbols:15

**Comment by EtienneLem** [comment]
🤔 I can’t think of any other way to do that right now

**Comment by vesper8** [comment]
ok so I started using emojisToShowFilter and oh my! even though I only include two categories.. this function is called 19500 times!! sheesh.. maybe something's wrong there...

anyway I found a site that has the list of unified codes in the order that they appear here
https://kapeli.com/cheat_sheets/Emoji.docset/Contents/Resources/Documents/index

And from that I built a list of emoticons I wanted to use like so

```

			emojiFilter: {
				"1F604": true,
				"1F603": true,
				"1F600": true,
				"1F60A": true,
				"263A": true,
				"1F609": true,
				"1F60D": true,
				"1F618": true,
				"1F61A": true,
				"1F617": true,
				"1F619": true,
				"1F61C": true,
				"1F61D": true,
				"1F61B": true,
				"1F633": true,
				"1F601": true,
				"1F614": true,
				"1F60C": true,
				"1F612": true,
				"1F61E": true,
				"1F623": true,
				"1F622": true,
				"1F602": true,
				"1F62D": true,
				"1F62A": true,
				"1F625": true,
				"1F630": true,
				"1F605": true,
				"1F613": true,
				"1F629": true,
				"1F62B": true,
				"1F628": true,
				"1F631": true,
				"1F620": true,
				"1F621": true,
				"1F624": true,
				"1F616": true,
				"1F606": true,
				"1F60B": true,
				"1F637": true,
				"1F60E": true,
				"1F634": true,
				"1F635": true,
				"1F632": true,
				"1F61F": true,
				"1F626": true,
				"1F627": true,
				"1F608": true,
				"1F47F": true,
				"1F62E": true,
				"1F62C": true,
				"1F610": true,
				"1F615": true,
				"1F62F": true,
				"1F636": true,
				"1F607": true,
				"1F60F": true,
				"1F611": true,
				"1F49B": true,
				"1F499": true,
				"1F49C": true,
				"1F49A": true,
				"2764": true,
				"1F494": true,
				"1F497": true,
				"1F493": true,
				"1F495": true,
				"1F496": true,
				"1F49E": true,
				"1F498": true,
				"1F48C": true,
				"1F48B": true,
				"1F48D": true,
				"1F48E": true,
				"1F389": true
			}
```

and then this is my filter function

```
		emojisToShowFilter(emoji) {
			if (typeof this.emojiFilter[emoji.unified] != "undefined") return true;
		},
```

Thought that might help someone as I couldn't find any example of this method being used for something like this

**Comment by vesper8** [comment]
yes I agree with your assessment that things should be changed.

Isn't there another way at least in my case here? Can't I create a custom sheet with only the 40 emoticons that I want and load that instead? I'm using the native emoticons because loading the other sets takes way too long

**Comment by EtienneLem** [comment]
You would need to build a custom data file (which is built and imported from https://github.com/iamcal/emoji-data) and build new sheets based on that custom data file. I don’t think you can filter out emojis when building emoji-data.

Sounds like quite the mission 😅
