### ISSUE TITLE
Custom shortcode aliases

### ISSUE THREAD

**Issue by savardc** [missive/emoji-mart#163]
Hi,

I'm trying to add support for aliases in our app and I was able to get part of it working with the custom emojis but I don't see how I can get the picker to cooperate without any modification.

I see 2 ways to get this to work: 
- Modify the custom emojis to support a `type` attribute (`emoji` or `alias`) and add the aliases to the shortnames when building the data for the picker
- Expose a function to add/remove shortnames for a specific emoji

There's probably other solution?

Let me know what you think and I'll get started on a PR

**Comment by EtienneLem** [comment]
Is that for custom emojis or any emoji? You’d want to be able to customize results for a given search term? Say you’d want “foozle” to return the `:+1:` emoji?

I feel like `emoji-index.js` would be best suited for that, although as I’m saying that I’m not exactly sure I remember 100% how the index works 😅. Let me know what’s your use case, that could give me some ideas.

**Comment by savardc** [comment]
It's to assign an existing emoji, custom or not, to another shortname. So for your example, `foozle` and `+1` would give you the same emoji.

I think I tried modifying `emoji-index.js` but I wasn't able to get the modification in the picker. I will try again today but if you have any other suggestion please let me know.

**Comment by nolanlawson** [comment]
This should be possible by modifying the JSON files directly. For instance, you could `import` the `all.json` file, run whatever transformations you want on it to add your custom aliases, and then pass that in to the `nimble-picker`. In principle I don't see why this couldn't be solved in userland using the existing APIs.

Closing, please reopen if I've misunderstood something about this.
