### ISSUE TITLE
Shared state between two pickers

### ISSUE THREAD

**Issue by akxcv** [missive/emoji-mart#166]
![emojimartbug](https://user-images.githubusercontent.com/17192674/36439850-23d57b3e-167f-11e8-95d4-d9a49fcf69c0.gif)

When using two pickers, selecting an emoji in one picker affects another's state. How hard would it be to fix that? I understand that some state (e.x. frequently used emojis and default skin tones) should be shared between all pickers, but I feel like that is the one case where the state should not be shared.

**Comment by EtienneLem** [comment]
Interesting 🤔 😅

I think I have a pretty good idea about what’s going on, I’ll check if there’s an easy fix.
