### ISSUE TITLE
react newbie trying to get this to work with my app and webpack

### ISSUE THREAD

**Issue by paries** [missive/emoji-mart#168]
Hello,
I have been trying to get this to work in my app.
i add the Picker component , but when it displays , it looks like there is no css.
i think it may be webpack.

is there anything special i have to do to make this work while using webpack?

thanks

**Comment by EtienneLem** [comment]
👋 

Yes, you do need to manually import the css file. That’s currently missing from the docs, sorry about that. CSS file can be found at `/node_modules/emoji-mart/css/emoji-mart.css`.
