### ISSUE TITLE
Crashes on Safari due to loading many images at once

### ISSUE THREAD

**Issue by janleslie** [missive/emoji-mart#170]
Hi.

The emoji-mart demo seems to crash Safari by loading thousands of images at once.

<img width="1369" alt="bug" src="https://user-images.githubusercontent.com/9676100/36927039-429a40d2-1e7b-11e8-8e04-884aaaec9ba1.png">

**Comment by nolanlawson** [comment]
Thanks for reporting! Does this still repro in latest Safari? Can you provide some code to help reproduce?

**Comment by nolanlawson** [comment]
Cannot repro using Safari 12.0.3 on macOS Mojave. Please reopen if I missed something, but as far as I can tell this seems to be a Safari bug that has been fixed.

**Comment by bismark** [comment]
I'm getting this exact issue on Safari 12.1.1 (macOS 10.14.5). Happens with extensions disabled.

![Screen Shot 2019-08-07 at 2 04 16 PM](https://user-images.githubusercontent.com/412158/62657884-4dfa8f80-b91c-11e9-8a53-e659d22dd0ff.png)
