### ISSUE TITLE
Question: Does using the native emoji set needs a license ?

### ISSUE THREAD

**Issue by ramytamer** [missive/emoji-mart#171]

**Comment by BinaryNate** [comment]
I *love* emoji-mart, but I'm surprised that image licensing doesn't appear to be discussed anywhere. I think that all of these image sets have different licenses. 

For example, if you want to use the Emojione images in a commercial product, [you must either attribute them or purchase a commercial license](https://www.emojione.com/licenses). It appears that using the Twitter image set [also requires attribution](https://github.com/twitter/twemoji/blob/gh-pages/LICENSE-GRAPHICS). I think that the only image set that can be used freely in a commercial product without attribution is the [Google Noto Color Emoji set](https://github.com/googlei18n/noto-emoji/blob/master/fonts/LICENSE).

**Comment by nolanlawson** [comment]
This is a good point; we should probably have something in the documentation about licensing.

For native emoji, no, I can't imagine that you need a license. Firefox on Linux uses Twemoji, Chrome on Linux uses EmojiOne, Mac uses Apple's emoji, Android uses Google's emoji depending on the Android version... I believe in those cases it's the OS or the browser that licensed it. But IANAL.

In any case for explicitly-bundled emoji (i.e. non-native) yeah it should be documented.

**Comment by TranquilMarmot** [comment]
Looks like this is using [`emoji-datasource`](https://www.npmjs.com/package/emoji-datasource):

https://github.com/missive/emoji-mart/blob/ccd591dd5af5ea21455e65b16c233f4876447b80/package.json#L43

`emoji-data` lists info about licensing in its README:

https://github.com/iamcal/emoji-data#image-sources

> - Apple Emoji: Copyright © Apple Inc. - macOS 11.4 Big Sur (20F71)
> - Android Emoji: Copyright © The Android Open Source Project - v2020-09-16-unicode13_1
> - Twitter Emoji: Copyright © Twitter, Inc. - v13.1
> - Facebook Emoji: Copyright © Facebook, Inc. - v9, fetched 2020-10-08 (no 13.1 support)
>
> Apple images are not licensed for commercial usage. Android/Google/Noto emoji are available under the Apache License 2.0. Twitter emoji are available under the Creative Commons Attribution 4.0 license. Facebook emoji have no clear licensing.

**Comment by EtienneLem** [comment]
Nope, the `native` set is the one you can never have trouble with since you’re displaying emojis natively as intended by the platform.
