### ISSUE TITLE
Using without npm

### ISSUE THREAD

**Issue by SimonIT** [missive/emoji-mart#177]
Hello,
is it possible to use emoji-mart without npm? I want to include it in my HTML page. I see that you are hosting it on unpkg, but I don't know which files I have to include.

Thank you!

**Comment by EtienneLem** [comment]
Unfortunately not “possible” to use as-is without at least a bundler (i.e. webpack, parcel, etc.). Note that it has React as a dependency which has to be defined in the bundle.
