### ISSUE TITLE
How to download spritesheet from custom URL as in earlier versions

### ISSUE THREAD

**Issue by iamsaksham** [missive/emoji-mart#18]
I want to download a low quality spritesheet to consume low bandwidth for slow connections, it was there in earlier version but looks like its been removed. Now the _64.png starts downloading itself which are quite large files.
Is there anyway if I can customize it??

**Comment by iamsaksham** [comment]
@EtienneLem @rafbm Can we download low quality spritesheet? Or can we give it our own customURL to download the spritesheet? Because the one that gets downloaded itself takes around 7-8minutes to download on a slow connection which is quite expensive for my project

**Comment by EtienneLem** [comment]
For now use the 0.2.10 version https://github.com/missive/emoji-mart/tree/v0.2.10, will add back support for custom `sheetURL` in a future version.

**Comment by EtienneLem** [comment]
As of v0.3.1 you can set `sheetSize`, which is any of these: `16, 20, 32, 64`.
You can refer to [README#sheet-sizes](https://github.com/missive/emoji-mart#sheet-sizes) to know the filesize of each.

**Comment by iamsaksham** [comment]
@EtienneLem emoji-mart 0.2.10 version is not available on npm. Please publish version 0.2.10 on npm

**Comment by iamsaksham** [comment]
@EtienneLem @rafbm Please publish version 0.2.10 on npm. I'm not able to release new emojis for production as I need v0.2.10. And is there any estimate to when the sheetUrl will be back in the latest updates?

**Comment by EtienneLem** [comment]
I’m having issues with npm trying to publish the v0.2.10, however v0.2.9 should do just fine. Any reason why the latest version doesn’t work for you? I’ve added a way to set the sheet size back, or perhaps you want to serve it locally?

**Comment by iamsaksham** [comment]
I've compressed the images, sheet_64 is now around 1mb. So i'd like to serve them from my cdn.
v0.2.9 wont work in firefox as it detects some empty objects for emojis as hasOwnProperty is missing in the loop.
I've started to add the sheetURL back, will keep it optional prop. I'll generate the pull request in a day or two. Till then v0.2.10 would be fine, if you can publish it on npm

**Comment by EtienneLem** [comment]
Gotcha, I think it worked. v0.2.10 should be available on npm.
