### ISSUE TITLE
Option to set lines for frequently used

### ISSUE THREAD

**Issue by carloschavez9** [missive/emoji-mart#182]
Is it possible to change the default frequently used lines from 4 to something else? I want to just show 2 lines.

**Comment by nolanlawson** [comment]
So if there are more than X number of frequently used emoji, would you want to just hide them entirely?

**Comment by ile** [comment]
Agreed. An option for the number of frequently used emojis would be good. Expressed in lines. The default can be 4 but I would also like to show just 2 lines.

**Comment by raad-altaie** [comment]
yes, please

**Comment by EtienneLem** [comment]
Latest version supports `maxFrequentRows` which does exactly that.
