### ISSUE TITLE
Screenshot in docs is out of date

### ISSUE THREAD

**Issue by johnsenpeder** [missive/emoji-mart#186]
README.md mentions powerful search with this screenshot:
<img width="338" alt="summer" src="https://user-images.githubusercontent.com/436043/32532567-179f1be4-c400-11e7-885e-df6e9b52c665.png" style="max-width:100%;">

But on the demo page it really isn't as powerful:
<img width="338" alt="summer" src="https://i.imgur.com/M7lJ6Je.png?1" style="max-width:100%;">

Not sure if the most recent updates may have caused it :thinking:

**Comment by nolanlawson** [comment]
I'm not sure I understand what this issue is pointing out. Closing old issues, please reopen if this is still relevant. Thanks!

**Comment by johnsenpeder** [comment]
It's just that the readme shows a difference of 6 emojis compared to the live code for the same search result :).

I guess my point is, the image should probably be updated if it's not a bug that it doesn't give the same amount of emojis :+1:

**Comment by nolanlawson** [comment]
Thanks, I've updated the issue!
