### ISSUE TITLE
Some emoticons not working on firefox.

### ISSUE THREAD

**Issue by rachitGulati** [missive/emoji-mart#19]
There are emojis not rendering properly on firefox. The native part of emoji object that is return from library emoji.native is not showing the right value if firefox. And even I store that value in my database and render in push notifications it is not showing correct preview.

Some images are below:

![imageedit_3_4817967686](https://cloud.githubusercontent.com/assets/9318393/19697595/9506d3ea-9b09-11e6-832a-1c5326c05d73.png)
![imageedit_14_5883324768](https://cloud.githubusercontent.com/assets/9318393/19697597/961a8de4-9b09-11e6-8ca0-e3da577e3084.png)

The dark background disappear totally.

It would be great if you can help me to resolve it :).

**Comment by EtienneLem** [comment]
That would be Firefox’s fault. You can fix that by adding `Apple Color Emoji` to your `font-family` stack in CSS. Here’s an example, open it in Firefox https://cldup.com/p0Vdx3DJ4M.html

```html
<html>
  <head>
   <meta charset="utf-8">
   <style>
     body {
       margin: 2em;
       font-family: Arial;
     }
     span { font-family: Apple Color Emoji }
   </style>
  </head>
  <body>
  <div>
    font-family: Apple Color Emoji<br>
    <span>3⃣</span>
  </div>
  <div><br></div>
  <div>
    font-family: Arial<br>
    3⃣
  </div>
  </body>
</html>
```
