### ISSUE TITLE
Autocomplete does not seem to give full shortcode preference in flags

### ISSUE THREAD

**Issue by renatolond** [missive/emoji-mart#197]
Hey! Mastodon uses emojimart and a user reported in https://github.com/tootsuite/mastodon/issues/7725 that typing `:flag-ru:` does not give the russian type as first result. I tested in the demo and it seems to have the same issue:

![image](https://user-images.githubusercontent.com/173791/41273734-edfbf350-6e1a-11e8-94e6-ac17f4552484.png)

I wonder if it's related to #194?

**Comment by nolanlawson** [comment]
seems duplicate of #194 yes
