### ISSUE TITLE
The option showPreview and showSkinTones are not working

### ISSUE THREAD

**Issue by taiharry108** [missive/emoji-mart#198]
I tried to turn showPreview off but the emoji-mart-bar div is still there. Also I don't see any skin tones picker, what is it supposed to be like?

Thank you very much!

**Comment by taiharry108** [comment]
I finally located the skin tones picker. But I still can't turn these options off.

**Comment by nolanlawson** [comment]
This seems to me to be fixed by https://github.com/missive/emoji-mart/pull/277. Please reopen if I misunderstood the issue. Thanks!
