### ISSUE TITLE
Custom emojis category

### ISSUE THREAD

**Issue by EtienneLem** [missive/emoji-mart#2]
**EmojiMart** will not upload custom emojis, but it could support a `custom` prop.

**Comment by felixtosh** [comment]
Hi @EtienneLem - how would one go about adding that custom prop? Is this a hack or sth already available? 

Cheers,
F

**Comment by mc962** [comment]
I'm also curious about how to do this.

**Comment by sonicdoe** [comment]
I’m thinking about making a pull request and would like to discuss how we should implement this beforehand. Here’s what I have thought of:

```js
import { Picker } from 'emoji-mart'

const customEmojis = [
  {
    id: 'octocat',
    name: 'Octocat',
    colons: ':octocat:',
    keywords: ['github'],
    emoticons: [],
    imageUrl: 'https://assets-cdn.github.com/images/icons/emoji/octocat.png?v7'
  }
]

<Picker custom={customEmojis} />
```

The `name`, `colons`, `keywords`, and `emoticons` properties would be used for searching.

The above would render something like this:

<img width="347" alt="Emoji Mart with custom emojis" src="https://cloud.githubusercontent.com/assets/652793/26396428/880813a6-4073-11e7-8ce9-bb431b7bd890.png">

The `emoji` object one would receive `onClick` would look like this:

```js
{
  id: 'octocat',
  name: 'Octocat',
  colons: ':octocat',
  emoticons: [],
  custom: true,
  imageUrl: 'https://assets-cdn.github.com/images/icons/emoji/octocat.png?v7'
}
```

The `custom` property would make it easy to distinguish between official unicode emoji and custom emoji images.

Additionally, I would add the custom category to the `I18N` object so users can provide a different category name.

@EtienneLem It would be great if you could take a look at this and let me know what you think.

**Comment by EtienneLem** [comment]
I love it! That’s how simple I imagined it. Perhaps the `custom` props could be an object that looks like `{ name: 'Custom', emojis: [], anchorUrl: '' }` so that the anchor can also be customized. I like the idea of customizing the name through `I18N`, so either works for me.

For the search, it’s simply a `substr` search on a concatenated string of `name`, `short_names`, `keywords` and `emoticons` (in that order). It’s okay to pass an extra param to `EmojiIndex#search` with the custom emojis because the lib does claim to be searchable even without being mounted 😄  Happy to chip in the PR at some point if you need help

Also, both `colons` and `id` are `short_names[0]` where `short_names` is an array of known… well short names I guess. Most of them only have 1, but some have more, i.e.

![screen shot 2017-05-24 at 9 25 50 am](https://cloud.githubusercontent.com/assets/436043/26405384/1b9573e0-4063-11e7-977e-b1b042b4de72.png)

That emoji looks like:
```js
{
  name: 'Smiling Face with Open Mouth and Tightly-Closed Eyes',
  short_names: ['laughing', 'satisfied'],
  emoticons: [':>', ':->'],
}
```

and that’s all EmojiMart needs and will return a sanitized emoji object on click. However, it may get complicated in that area (`getSanitizedData` and friends). So yeah, just pointing it out. It may be less complicated to have the custom emojis data a little bit different from the original ones. The `Preview` component do expect `short_names` though.

I feel like saying more would confuse you more than help you 😅
I’ll let you have have a first go at it. Don’t hesitate to ping me ✌️
