### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by ai** [missive/emoji-mart#20]
Thanks for picker, it is awesome!

We are integrating to Russian website and want to translate categories and other texts (like `Search` placeholder). I didn’t find a way to do it.

Is is possible or we need to extend API?

**Comment by EtienneLem** [comment]
Good call. Just took a look at the codebase and it really is just the categories and the search input that have static text, will be pretty easy to implement without the use of a third party library. Right now, I don’t think there would be a way to do that other than doing some JS shenanigans after mounting the component.

No promises, but I should be able to find time in the next ~24 hours and release a new version that includes I18n support.

**Comment by ai** [comment]
Yeap, I think we could just add some `props` like `i18n` or `texts`:

```js
<Picker texts={{ search: 'Поиск', smiles: 'Смайлы', food: 'Еда' }}
```

**Comment by EtienneLem** [comment]
Added `i18n` prop to Picker (v0.3.1). See [README#i18n](https://github.com/missive/emoji-mart#i18n) for the object signature.

Thanks for the suggestion, let me know if it doesn’t work as expected 🤘
