### ISSUE TITLE
Add emoji-mart to textinput or textarea.

### ISSUE THREAD

**Issue by phuongthuan** [missive/emoji-mart#207]
How to add emoji picker to text input or text area. 
My component like this:

             `<Input
                type="text"
                name="emotion"
                bsSize="sm"
                autoComplete="off"
                value={report.emotion}
                onChange={this.onHandleFormChange}
              />
              <Picker
                title='Pick your emoji…'
                emoji='point_up'
                emojiSize={30}
                showPreview={false}
                onSelect={(emoji) => console.log('emoji', emoji)}
              />`

How can I add Picker component inside Text input. Whenever I click any emoji, It show me to text input.

**Comment by Lavhe** [comment]
Got a solution to this?

**Comment by comp615** [comment]
You need to write Javascript to handle `onSelect`, instead of `console.log`, change the value of your `input`

**Comment by phuongthuan** [comment]
@comp615 I can select object and console.log that. 
But actually, I wanna add picker to the corner of the text input or text area.
When I clicked on the icon, it will show me board icon. That's it

**Comment by phuongthuan** [comment]
@ycjcl868 I found other lib based on this lib [emoji-mart-picker](https://github.com/Canner/emoji-mart-picker#readme)

**Comment by nolanlawson** [comment]
This sounds like a support question, please reopen if necessary. Thanks!

**Comment by davidhabla** [comment]
https://medium.com/@allegra9/add-emoji-picker-to-your-react-chat-app-30d8cbe8d9a6
