### ISSUE TITLE
Support passing custom className

### ISSUE THREAD

**Issue by goodmind** [missive/emoji-mart#210]
Add forwarding of `className` prop to root div on `Picker` component

**Comment by nolanlawson** [comment]
See discussion in https://github.com/missive/emoji-mart/pull/274#issuecomment-470969125, this feature is not necessary because you can style using selectors based on parent elements.

**Comment by goodmind** [comment]
@nolanlawson but how about using with styled-components?

**Comment by nolanlawson** [comment]
I don't know much about styled-components. Is there something about their approach that is incompatible with using CSS selectors?

**Comment by goodmind** [comment]
@nolanlawson, no but passing `className` is more convenient
```js
const StyledPicker = styled(Picker)`
   background-color: #000;
`
```
would pass generated `className` to `Picker`

**Comment by Boooober** [comment]
Also, styled-wrappers leads to unnecessary DOM nodes. In case when there are too many, for example `Emoji` components, that could be an issue.

Using them in this style would be quite handy:
```javascript
import styled from 'styled-components';
import { Emoji as EmojiMart } from 'emoji-mart';

export const Emoji = styled(EmojiMart)`
  vertical-align: middle;
  // any other styles
`;
```
