### ISSUE TITLE
Add option to hide search input

### ISSUE THREAD

**Issue by gycdgg** [missive/emoji-mart#216]
in some case,  we don't need the search input.
so could it be possible to add a props showSearch?

**Comment by x1nGoo** [comment]
Add option to hide search input ,  which property is ?

**Comment by alirezamaleky** [comment]
Search component takes 93ms to mount and i dont need it, please add option to hide it.

**Comment by Bonfims** [comment]
i can't translate l18n search option, would be nice to hide it.

**Comment by syedsadiqali1** [comment]
Fixed in commit https://github.com/missive/emoji-mart/commit/4d5069b1b7eb785364c2bd224b47bc5c797421f9 . use searchPosition='none' to hide search
