### ISSUE TITLE
Can we add support for "line" emojis?

### ISSUE THREAD

**Issue by daiict218** [missive/emoji-mart#217]
I'm using `emoji-mart` and I've add support for [line](https://line.me/en/) emojis. Although I've added support for line emojis externally but it is causing some problems for me. I have the [emoji list](http://force4u.cocolog-nifty.com/skywalker/2013/12/line-9d50.html) for line. Please let me know, I can make a PR for the sprite and it's integration.

**Comment by nolanlawson** [comment]
I think these should probably be handled as "custom" emoji, since it would be too specific to one social network or messenger to include LINE's custom emojis in emoji-mart (I believe).
