### ISSUE TITLE
How to parse emoji?

### ISSUE THREAD

**Issue by wilson0506** [missive/emoji-mart#222]
Hi, if i added the emoji into body of the message, how to parse it back into emoji, any directive or pipe?

**Comment by wilson0506** [comment]
angular6

**Comment by satyapendem** [comment]
@wilson0506 In what format you added(shortCode or unicode)?

**Comment by nolanlawson** [comment]
You may want to look into [emoji-regex](https://github.com/mathiasbynens/emoji-regex).
