### ISSUE TITLE
steps to run the app locally + PR template

### ISSUE THREAD

**Issue by hozefaj** [missive/emoji-mart#227]
the Readme does not detail out steps to run the app locally. Also having some steps detailing on what's expected in a PR would be helpful.

**Comment by nolanlawson** [comment]
Yep this would be a nice feature

**Comment by nolanlawson** [comment]
The docs are here, but you're right that they could be clearer: https://github.com/missive/emoji-mart#development

**Comment by hozefaj** [comment]
Will send PR

**Comment by nolanlawson** [comment]
Ah sorry, beat you to it. Please take a look and let me know if it covers everything! :)

**Comment by hozefaj** [comment]
Yeah look good to me 👍
