### ISSUE TITLE
Can't resolve babel-runtime - doesn't work with Babel v7

### ISSUE THREAD

**Issue by saltire** [missive/emoji-mart#228]
Building a project that includes `emoji-mart` but not `babel-runtime` fails:

```
ERROR in ./node_modules/emoji-mart/dist-es/utils/index.js
Module not found: Error: Can't resolve 'babel-runtime/core-js/object/keys' in '[...]/node_modules/emoji-mart/dist-es/utils'

ERROR in ./node_modules/emoji-mart/dist-es/components/skins.js
Module not found: Error: Can't resolve 'babel-runtime/helpers/classCallCheck' in '[...]/node_modules/emoji-mart/dist-es/components'

...etc.
```

I see in `.babelrc` that some Babel imports are aliased to polyfills by the `module-resolver` plugin, but not all of them, so the dist files depend on packages that aren't necessarily installed.

For example, this can happen if a project is using Babel v7, which has different package names.

Perhaps the project should explicitly include Babel in `dependencies` instead of `devDependencies`, or else make sure all the imports are covered by polyfills?

**Comment by NikolasStelmah** [comment]
Did anyone fix this trouble in any way? I faced it with Babel 7, and find no way to resolve uncompability, except make a fork of  `emoji-mart` and try to update Babel.

**Comment by Jikstra** [comment]
> Did anyone fix this trouble in any way? I faced it with Babel 7, and find no way to resolve uncompability, except make a fork of emoji-mart and try to update Babel.

Currently i have this on one of the projects i'm working on. A quick fix is to just require the `babel-runtime` dependency in the `package.json`.

**Comment by nolanlawson** [comment]
It seems like another reasonable fix would be for emoji-mart to not bundle babel-runtime in its `dist` files.
