### ISSUE TITLE
Could we hide a specific list of emojis?

### ISSUE THREAD

**Issue by sinner** [missive/emoji-mart#230]
I'm working with a client that is requesting us to avoid showing a specific list of emojis, but, I'm not able to see how to make that.

@EtienneLem Sorry, could you help me.

**Comment by EtienneLem** [comment]
Hey @sinner! You can use the `emojisToShowFilter` function prop. It receives an object containing the data of each emoji in the picker. Return `true` to display it and `false` to hide it.
