### ISSUE TITLE
Angular 7 compatibility 

### ISSUE THREAD

**Issue by JonesM87** [missive/emoji-mart#234]
Any idea when you'll make the update?

**Comment by nolanlawson** [comment]
I'm not sure what is needed for Angular 7 compatibility? Also, this is a React library... ;)

In any case, emoji-mart can be used within any non-React framework as a standard web component, using something like [remount](https://www.npmjs.com/package/remount) to wrap it. I've successfully done this inside of a SvelteJS project, so it should be possible within Angular as well, no problem.
