### ISSUE TITLE
Can anyone help me setup this package for react app ?

### ISSUE THREAD

**Issue by Rahulkr204** [missive/emoji-mart#236]
Any code snippet would be appreciated. I have tried but I'm getting following error: 
![screen shot 2018-10-21 at 6 38 51 pm](https://user-images.githubusercontent.com/8544323/47288548-3283f980-d614-11e8-90e5-d16539cd7acb.png)

**Comment by Rahulkr204** [comment]
![screen shot 2018-10-22 at 7 09 32 pm](https://user-images.githubusercontent.com/8544323/47295743-0b3a2600-d62e-11e8-86bc-7cb528a80dc8.png)
This warning is shown in console.

**Comment by EtienneLem** [comment]
GitHub shouldn’t be used as a direct source. Here’s how you should import the CSS file, it will be bundled with the rest of your application.

```js
import 'emoji-mart/css/emoji-mart.css'
import { Picker } from 'emoji-mart'
```

You could alternatively use this file: https://unpkg.com/emoji-mart@2.8.1/css/emoji-mart.css
