### ISSUE TITLE
 is there any bundle version ?

### ISSUE THREAD

**Issue by GlauberF** [missive/emoji-mart#237]
I have an application, but I do not use webpack or babel so I can not use import

**Comment by vs-ryann** [comment]
You should be able to require it. For example, I can require the nimble picker by doing 
`const NimblePicker = require( 'emoji-mart/dist-es/components/picker/nimble-picker' ).default;`

and then use it like any other react component 
`<NimblePicker 
                            autoFocus={true}
                            onSelect={this.emojiSelected}
                            native={true}
                            showPreview={false}
                            set='messenger'
                            data={data}
                            title="Select Emoji" />`

**Comment by rugk** [comment]
Seems to be a dupe of https://github.com/missive/emoji-mart/issues/305 (when creating it, I made https://github.com/rugk/emoji-mart-embed/)
