### ISSUE TITLE
Passing an empty array for `recent` on Picker breaks the component

### ISSUE THREAD

**Issue by attaboy** [missive/emoji-mart#238]
I want to omit the "recent" (aka "Frequently Used") section on the picker.

I tried passing an empty array for the `recent` prop on `Picker`, but when I do that, there's a TypeError on category.js because it tries to check `emojis.length` even though it's not set in `Category.getEmojis`.

**Comment by PqBenoit** [comment]
I came up with this solution to hide `Frequently used`:

```
<Picker recent={['']} />
```

I know it's not the most beautiful, but still, it works. Hope it will come with a nicer way some times later

**Comment by EtienneLem** [comment]
Indeed, that would be the proper way to exclude a category 😄
