### ISSUE TITLE
How to get base64 image as output?

### ISSUE THREAD

**Issue by shyamal890** [missive/emoji-mart#239]

**Comment by ivan-rey-c-v** [comment]
I hope emoji-mart caters this feature.
As of now, `EmojiMart.Emoji` renders a span wherein the background is set to the fetched image sheet. Unfortunately, you can not see in advance the background size nor the position of the emoji within the fetched image sheet.

Is there a possible way to get the background size/position in advance? Or perhaps get the base64 image directly?

**Comment by nolanlawson** [comment]
I'm not sure I understand this issue, or what is desired. What is the use case you're trying to satisfy where you need to know the background size/position? Also, what does this have to do with "getting the base64 image as output"? :)

**Comment by ivan-rey-c-v** [comment]
It was for using the emoji image itself to be drawn in the canvas. The
rendered Emoji have background image of the whole sheet, I was hoping to
get the specified position of that specific emoji. Or possibly get the
image itself.
Nonetheless, I just used the native one.

**Comment by nolanlawson** [comment]
OK, it sounds like this issue has been resolved please reopen as necessary! Thanks. :)
