### ISSUE TITLE
Small space for 4 levels emoji description

### ISSUE THREAD

**Issue by ai** [missive/emoji-mart#24]
![1](https://cloud.githubusercontent.com/assets/19343/20329856/cca0d636-abab-11e6-88a1-2624e90e2e9a.png)

**Comment by EtienneLem** [comment]
Ah yes, I’ve had to overwrite the description `line-height` when I added EmojiMart to Missive. I suppose you’ve already figured a way to fix that on your end, but I’ll make sure the `line-height` isn’t easily changed by the body’s

**Comment by ai** [comment]
Thanks for quick fix and great project 👍😊

**Comment by EtienneLem** [comment]
Let me know if it doesn’t work, `line-height` can be a mess to deal with sometimes 😄
