### ISSUE TITLE
EmojiOne :knife_fork_plate: should be :fork_knife_plate:

### ISSUE THREAD

**Issue by austenpayan** [missive/emoji-mart#242]
In emoji-mart data, it seems that :fork_knife_plate: shortcode is :knife_fork_plate: on accident.

The correct shortcode is :fork_knife_plate: according to EmojiOne's website:

https://www.emojione.com/emoji/1f37d

**Comment by EtienneLem** [comment]
There’s unfortunately no standard in short names. EmojiMart uses https://github.com/iamcal/emoji-data as the data source, so data should be handled there.

Note that [EmojiOne has however been removed from emoji-data](https://github.com/iamcal/emoji-data/pull/142) as per EmojiOne request (👎). I fear this isn’t going to a be popular move amongst EmojiMart users… so I’ve been postponing upgrading dependencies. But one day we’ll have to support new emoji versions and we’ll need to upgrade but at the cost of losing EmojiOne set.
