### ISSUE TITLE
blur in order to intercept lost focus event

### ISSUE THREAD

**Issue by dario-frongillo** [missive/emoji-mart#244]
hi all,
i need to close the picker if the picker lost focus. how can implement it ? i need onblur event

**Comment by amickael** [comment]
Just in case you still need this, I left a comment on a similar issue in here explaining how I did this: https://github.com/missive/emoji-mart/issues/249#issuecomment-443079971

**Comment by nolanlawson** [comment]
Yes, unless I'm mistaken, this can be solved outside of emoji-mart itself. Since you have access to the DOM, you can place focus/blur events wherever you like and react accordingly.
