### ISSUE TITLE
Selected category does not always match scroll position

### ISSUE THREAD

**Issue by tg2dex** [missive/emoji-mart#246]
The counter of active emoji is broken.
GIF => https://ibb.co/hUm5AL
But if type in search input any text, counter fixed

**Comment by nolanlawson** [comment]
Yep, looks like a bug to me

**Comment by nolanlawson** [comment]
I cannot reproduce this using the storybook. Which browser was this in? Which scrolling method were you using? Is there a certain set of emoji-mart parameters that causes this?

**Comment by nolanlawson** [comment]
OK I managed to reproduce, but it's really unpredictable. What seems to be happening is that the `top` value calculated here can be wrong sometimes (it's too large, then it scrolls way too far down):

https://github.com/missive/emoji-mart/blob/7e207ba851fcf1bfb6e928cd61fb627d249eb047/src/components/category.js#L67-L72

**Comment by nolanlawson** [comment]
It looks like instead we could use [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView), and that should be quite a bit more predictable.

**Comment by reznikGit** [comment]
Hello, I using electronJS (4.1.0), can u fix it?

**Comment by miguelrcDEV** [comment]
Any update on this?? I have the same behavior. But if i search, and clean, then click on categories work.
