### ISSUE TITLE
spritesheets for custom emojis?

### ISSUE THREAD

**Issue by alexpmorris** [missive/emoji-mart#247]
we created a custom spritesheet just for custom emojis, however it doesn't seem there's an easy way to pass in the associated css class for them, as opposed to using `imageUrl`.  Is there some easy way we may have overlooked to accomplish this?  If not, perhaps this would be a nice addition for an upcoming release.

This is the tool we used to create our spritesheet: https://github.com/draeton/stitches

The following is a sample of the associated CSS:

```
.custom_emojis {
    background-image: url(custom_spritesheet.png);
    background-repeat: no-repeat;
    display: block;
}

.custom_emojis-custom_angry {
    width: 32px;
    height: 32px;
    background-position: -2px -2px;
}
```

Thanks for any guidance you can offer with this, and for this terrific widget as well! :)

**Comment by EtienneLem** [comment]
Custom emojis only work with specific image URL at the moment, unfortunately.

Is using CSS classes important for your use case, or setting the position via the `custom` param works for you? The only thing missing would be to support `position: [row, column]` to custom emojis and EmojiMart would take care of the rest (like it currently does for built-in emojis).

**Comment by alexpmorris** [comment]
The only reason for the CSS is positioning, so if the whole process could be streamlined internally by EmojiMart via the `custom` param that way, that should work great too!  

{ name: 'Blush',
      short_names: ['my_blush'],
      keywords: ['myblush'],
      spriteUrl: 'custom_spritesheet_32px.png',
      position: [row, column]
},

That would definitely make for a terrific addition!

**Comment by alexpmorris** [comment]
great work @Kennybll, definitely speeds things along... and hopefully this can be merged in short order! 👍 😁

**Comment by EtienneLem** [comment]
v2.9.2 has just been released 😄
