### ISSUE TITLE
how to close emoji box when user clicks outside 

### ISSUE THREAD

**Issue by mwinner313** [missive/emoji-mart#249]
currently user has to click the picker button to close the emoji box how can i close it when user clicks outside of the box ?

**Comment by amickael** [comment]
I also had a hard time with this. I found a solution, while not elegant, that works.

First, create a ref in the constructor, bind your click handler, and include `ReactDOM`:
```JavaScript
import React from 'react'
import ReactDOM from 'react-dom'

class YourClass extends React.Component {
    constructor(props) {
        super(props);
        this.emojiPicker = React.createRef();
        this.handleClick = this.handleClick.bind(this);
    }
// Class continues below...
```

Then add an event listener for the `mousedown` event:
```JavaScript
componentDidMount() {
    document.addEventListener('mousedown', this.handleClick, false);
}

componentWillUnmount() {
    document.removeEventListener('mousedown', this.handleClick, false);
}
```

Write your handleClick method, depending on how you choose to hide/show the picker. It might be a good idea to wrap this in a try/catch block depending on how you handle things:
```JavaScript
handleClick(event) {
    try {
        let node = ReactDOM.findDOMNode(this.emojiPicker.current);
        if (!node.contains(event.target)) {
            // Handle outside click here
            this.hideEmojiPicker()
        }
    } catch(error) {
        return null
}
```

Finally pass the ref as a prop to the `<Picker>` component:
```JavaScript
render() {
    return (
        <Picker ref={this.emojiPicker} />
    )
}
```

Again, pretty ugly, but it gets the job done. It would be nice to get an `onBlur` prop so a workaround isn't necessary.

**Comment by adambowles** [comment]
FYI: https://github.com/Pomax/react-onclickoutside

**Comment by nolanlawson** [comment]
I think this is not an issue with emoji-mart per se, but with whatever dialog library/wrapper you're using around it. I used [a11y-dialog](https://github.com/edenspiekermann/a11y-dialog) and have no problems with emoji-mart, since it's a11y-dialog that handles that behavior.

**Comment by androane** [comment]
@mwinner313 why have you closed this? the author has a good question that hasn't been answered

**Comment by sallamTanna** [comment]
1. I added a `p` tag  with  `id="emojis-btn"` when. When it clicked I show the emojis picker. 
```
      <p
            id="emojis-btn"
            style={{ alignSelf: "center", marginRight: "1%" }}
            type="button"
            className="toggle-emoji"
            onClick={() => setShowEmojiPicker(!showEmojiPicker)}
          >
            {String.fromCodePoint(0x1f600)}
          </p>
```
2. Then I added a `handleDocumentClick` function inside `useEffect` like this:
```
  useEffect(() => {
    document.addEventListener("click", handleDocumentClick, false);
  });
```
3. Inside `handleDocumentClick` I added a condition to check if the `p` tag is clicked or not, if not then hide the picker 
```
  const handleDocumentClick = event => {
    if (event.target.id !== "emojis-btn") {
      setShowEmojiPicker(false);
    }
  };
```

**Comment by benbieler** [comment]
Any elegant solution to this issue?

**Comment by benbieler** [comment]
So I solved this with refs. I think this is pretty elegant:
```
let ChatForm: any = ({ handleChange, handleSubmit, value, chat = '' }) => {
  const ref = useRef();
  const [isOpen, setIsOpen] = useState(false);
  useOnClickOutside(ref, () => setIsOpen(!isOpen));

  const dispatch = useDispatch();

  return (
    <form onSubmit={handleSubmit}>
      {isOpen ? (
        <div ref={ref}>
          <Picker
            set="apple"
            style={{
              position: 'absolute',
              zIndex: 1000,
              bottom: '50px',
            }}
            onSelect={(s: any) => dispatch(change('chatForm', 'chat', chat + s.native))}
          />
        </div>
      ) : null}
{reduxForms forms...}
 </form>
  );
};


function useOnClickOutside(ref, handler) {
  useEffect(() => {
    const listener = event => {
      if (!ref.current || ref.current.contains(event.target)) {
        return;
      }

      handler(event);
    };

    document.addEventListener('mousedown', listener);
    document.addEventListener('touchstart', listener);

    return () => {
      document.removeEventListener('mousedown', listener);
      document.removeEventListener('touchstart', listener);
    };
  }, [ref, handler]);
}

ChatForm = reduxForm<any, any>({ form: 'chatForm' })(ChatForm);

const selector = formValueSelector('chatForm');
ChatForm = connect(state => ({
  chat: selector(state, 'chat'),
}))(ChatForm);

export default ChatForm;
```

**Comment by sallamTanna** [comment]
@benbieler This is how it works with me:
1. Add this `p` tag to show the bellow smile emoji and give it `id="emojis-btn"`. When this tag is clicked it will set `showEmojiPicker` to `true` using the function `setShowEmojiPicker`, and then the picker will appear. 
![image](https://user-images.githubusercontent.com/30619876/101652680-34ed7b80-3a47-11eb-84db-ee449ac4c3da.png)

```
  <p
          id="emojis-btn"
          type="button"
          className={classnames("toggle-emoji", classes.emojiBtn)}
          onClick={() => setShowEmojiPicker(true)}
        >
          <span style={{ fontSize: "20px" }}>{String.fromCodePoint(0x1f600)}</span>
        </p>
```
2. Add `useEffect` hook that will execute `handleDocumentClick` function when the user clicks any place. 
```
  useEffect(() => {
    document.addEventListener("click", handleDocumentClick, false);
  });
```
3. The function will make sure that that the clicked area is outside the picker, then hide the picker by setting `ShowEmojiPicker` to `false`
```
  const handleDocumentClick = event => {
    let isEmojiClassFound = false;

    event &&
      event.path &&
      event.path.forEach(elem => {
        if (elem && elem.classList) {
          const data = elem.classList.value;
          if (data.includes("emoji")) {
            isEmojiClassFound = true;
          }
        }
      }); // end
    if ( isEmojiClassFound === false && event.target.id !== "emojis-btn")
      setShowEmojiPicker(false);
  };
```
Hope to find this helpful :)

**Comment by amitpatil321** [comment]
This is what worked for me

```
  onToggleEmojiWindow = () => {
    const { showEmoji } = this.state;
    this.setState({ showEmoji: !showEmoji });
  };

  componentDidMount() {
    document.querySelector(".main-content").addEventListener("click", event => {
      // Get parent element and check if click happened outside parent only
      const parent = document.querySelector(".emoji-mart");
      const { showEmoji } = this.state;
      if (showEmoji && !parent.contains(event.target)) {
        this.onToggleEmojiWindow();
      }
    });
  }
```

**Comment by JonathanXu1** [comment]
Thanks @sallamTanna ! I couldn't get it working with the other suggestions or libraries like [react-onclickoutside](https://www.npmjs.com/package/react-onclickoutside), getting errors such as Ref.current is undefined (on React hooks). This approach finally worked for me.

**Comment by sallamTanna** [comment]
@JonathanXu1 You're welcome 👍🏻

**Comment by neurocome** [comment]
#Angular

`  @HostListener('document:click', ['$event'])
  clickout(event) {
    let emojiPanel = document.getElementById("emoji-palette"); // this is emoji panel element
    let buttonEmoji = document.getElementById("button-emoji"); //this is button to triggered emoji panel
    if(emojiPanel && !event.path.includes(buttonEmoji)){
      if(!event.path.includes(emojiPanel)){
        emojiPanel.style.display = "none";
      }
    }
    
  }
`

**Comment by neurocome** [comment]
`  @HostListener('document:click', ['$event'])
  clickout(event) {
    let emojiPanel = document.getElementById("emoji-palette"); // this is emoji panel element
    let buttonEmoji = document.getElementById("button-emoji"); //this is button to triggered emoji panel
    if(emojiPanel && !event.path.includes(buttonEmoji)){
      if(!event.path.includes(emojiPanel)){
        emojiPanel.style.display = "none";
      }
    }
  }`

**Comment by shoaibhassan** [comment]
Better to use for controlling the behavior.
https://javascript.plainenglish.io/detect-a-click-outside-of-a-react-component-with-a-reusable-hook-and-useref-a0c282171c3f

**Comment by shoaibhassan** [comment]
Better to use this hook.
https://javascript.plainenglish.io/detect-a-click-outside-of-a-react-component-with-a-reusable-hook-and-useref-a0c282171c3f

**Comment by malcolmswaine** [comment]
Had better luck with event.composedPath() - event.path stopped working after a browser update

```
 @HostListener('document:click', ['$event'])
  public onGlobalClick(event) {
    
    let path = event.composedPath();
    let emojiPanel = document.getElementById("emoji-palette"); // this is emoji panel element
    let buttonEmoji = document.getElementById("button-emoji"); //this is button to trigger the emoji panel

    if(emojiPanel && !path.includes(buttonEmoji)){
      if(!path.includes(emojiPanel)){
        this.emojiPickerOpen = false;
      }
    }
  }
```
```
<button class="emoji_opener">
                            <i class="fa-solid fa-face-smile" (click) ="toggleEmojiPicker()" id="button-emoji"></i>
                            <emoji-mart #emoji_picker id="emoji-palette" *ngIf="emojiPickerOpen" emoji="point_up" (emojiSelect)="emojiSelect($event)" class="emoji-picker"></emoji-mart>
                        </button>
```

**Comment by CMara14** [comment]
Hello! I found this solution to avoid refs, using local states in react, the prop "onClickOutside" that the library already provides (although it doesn't work very well) and adding an Event.stopPropagation() in the button that opened it, to stop the click event from propagating to the Picker component. So far it works well.

```
  const [showEmojiPicker, setShowEmojiPicker] = useState<boolean>(false); 


 <button
        type="button"
        onClick={(event) => {
          event.stopPropagation();
          setShowEmojiPicker(!showEmojiPicker);
        }}
      >
        { showEmojiPicker
         && (
           <Picker
             perLine={8}
             onEmojiSelect={addEmoji}
             onClickOutside={() => setShowEmojiPicker(false)}
           />
         )}
      </button>
```

**Comment by CMara14** [comment]
Hello! I found this solution to avoid refs, using local states in react, the prop "onClickOutside" that the library already provides (although it doesn't work very well) and adding an Event.stopPropagation() in the button that opened it, to stop the click event from propagating to the Picker component. So far it works well.

 ```
 const [showEmojiPicker, setShowEmojiPicker] = useState<boolean>(false); 


   <button
        type="button"
        onClick={(event) => {
          event.stopPropagation();
          setShowEmojiPicker(!showEmojiPicker);
        }}
     />
        { showEmojiPicker
         && (
           <Picker
             perLine={8}
             onEmojiSelect={addEmoji}
             onClickOutside={() => setShowEmojiPicker(false)}
           />
         )}
```
