### ISSUE TITLE
Split emoji rendering

### ISSUE THREAD

**Issue by adambowles** [missive/emoji-mart#252]
Emoji Mart is rendering emojis that are a sequence of other emojis on multiple lines (in the case of this screenshot ['male student' is 'man' + 'graduation cap'](https://emojipedia.org/male-student/)).

Screenshot taken on macOS 10.14.1, Firefox 63.0.3.

![image](https://user-images.githubusercontent.com/10128574/49510401-fa610f00-f87f-11e8-94a7-756b802e6f53.png)

**Comment by adambowles** [comment]
Safari 12.0.1 on macOS 10.14.1 is rendering the component emojis:
![image](https://user-images.githubusercontent.com/10128574/49511606-83c61080-f883-11e8-9eb9-f7b6c1bc0d2d.png)

**Comment by AaronGoodrum** [comment]
Seeing the same thing on Win 10 pro, Firefox 64.
![firefox](https://user-images.githubusercontent.com/30958265/50702154-efc3a200-1004-11e9-9f6a-836fab97812c.jpg)

**Comment by nolanlawson** [comment]
fixed in https://github.com/missive/emoji-mart/pull/261
