### ISSUE TITLE
Native Emoji Looks Different

### ISSUE THREAD

**Issue by aniketparab4** [missive/emoji-mart#255]
I am using the OS Ubuntu 18.10, the emoji looks different on my screen. I have also tried by different emoji set but it still shows the same. I have attached the screenshot.
And am not getting any idea to make emoji looks in orignal pattern.

![screenshot from 2018-12-18 13-18-27](https://user-images.githubusercontent.com/30366021/50139583-1c1eb500-02c8-11e9-8685-19eed7933039.png)

**Comment by nolanlawson** [comment]
I'm on Ubuntu 18.04 and I'm not seeing this at all. Which browser are you in? Firefox ships with its own set of Twemoji, but the other browsers should use the built-in Emoji One set.

Firefox:

![screenshot from 2018-12-18 09-50-53](https://user-images.githubusercontent.com/283842/50172723-7d379000-02aa-11e9-92aa-2d311a07a646.png)

Chrome:

![screenshot from 2018-12-18 09-51-13](https://user-images.githubusercontent.com/283842/50172717-7a3c9f80-02aa-11e9-9cf6-b46b2f97b843.png)

**Comment by nolanlawson** [comment]
Aha, perhaps you are using GNOME Web (aka Epiphany Browser)?

![screenshot from 2018-12-18 09-53-23](https://user-images.githubusercontent.com/283842/50172847-d0114780-02aa-11e9-8c8a-cf0b82f7b2f0.png)

This is fixable; I'll try to submit a PR
