### ISSUE TITLE
Is there a method to parse a string to look for emojis?

### ISSUE THREAD

**Issue by Sewdn** [missive/emoji-mart#264]
Hi,

Is there any internal available parsing method to look for emojis in a text string, looking for all the supported encodings (unicode, colons, ascii, ...)?

Something like https://www.npmjs.com/package/react-emoji-render, but for all of the supported emojis in your set(s).

If not, I'm willing to contribute with a PR.

When I combine `emoji-mart` (for picking emojis) and `react-emoji-render` (for finding emojis in strings, ans parsing them to React comps), some of the selected emojis from emoji-mart cant be found by react-emoji-render. It would make sense to me, using the same package for both purposes.

Thanks!

**Comment by Sewdn** [comment]
@EtienneLem Could you please look into this? Thanks!

**Comment by nolanlawson** [comment]
You may want to look into [emoji-regex](https://github.com/mathiasbynens/emoji-regex), which should handle this use case. Thanks!

**Comment by 0xdevalias** [comment]
> You may want to look into [emoji-regex](https://github.com/mathiasbynens/emoji-regex), which should handle this use case.

For anyone that ends up here from Google like I did, `emoji-regex` is the same underlying dependency that `react-emoji-render` uses:

- https://github.com/tommoor/react-emoji-render/blob/master/package.json#L50
- https://github.com/tommoor/react-emoji-render/blob/master/src/renderer.js#L15

Along with its own `aliasRegex`:

- https://github.com/tommoor/react-emoji-render/blob/master/src/aliasRegex.js
- https://github.com/tommoor/react-emoji-render/blob/master/src/renderer.js#L68-L101
