### ISSUE TITLE
"Frequent" emoji can change position seemingly at random

### ISSUE THREAD

**Issue by satyapendem** [missive/emoji-mart#265]
#How to block change of emoji in frequents

Emoji mart emoji picker is very nice. And I want to make one change on click of emoji in frequents the clicked emoji position was changing if I want to select the the same emoji again it is hard for me. How I can block the position change.

https://cl.ly/8d83b1962fcc

**Comment by nolanlawson** [comment]
This seems like a bug to me

**Comment by nolanlawson** [comment]
Actually wait, this behavior is intentional. As you click the emoji, it becomes more frequently used, and thus moves to the start of the line. Closing, please reopen if I missed something. Thanks!

**Comment by edgesinghkataria** [comment]
> Actually wait, this behavior is intentional. As you click the emoji, it becomes more frequently used, and thus moves to the start of the line. Closing, please reopen if I missed something. Thanks!

yeah but it's hard if I want to add one emoji more than once coz it jumps to difference positions.
Or we can give a property to enable/disable this functionality.
Let me know what suits best. 
I fix this In my current project, will be happy to submit a PR.
