### ISSUE TITLE
Skin tone ignored when selecting emoji with pressing enter in search

### ISSUE THREAD

**Issue by johnsenpeder** [missive/emoji-mart#267]
Can be seen on the official demo page: https://missive.github.io/emoji-mart

Select any skin tone other than the default one, then search for `hand` and press the enter key, the emoji object returned doesn't match the selected skin tone, if you select the emoji with the mouse the emoji object returned matches the selected skin tone.

**Comment by dwijesingheWR** [comment]
Am also seeing this issue

**Comment by dwijesingheWR** [comment]
I fixed this issue myself and created a pull request here:
https://github.com/missive/emoji-mart/pull/270

@johnsenpeder and anyone else who is dealing with this bug, feel free to use my fork of the repo in the meantime, until the pull request is merged in :)

https://github.com/dwijesingheWR/emoji-mart

**Comment by nolanlawson** [comment]
fixed in https://github.com/missive/emoji-mart/pull/270
