### ISSUE TITLE
Emoji version 11+

### ISSUE THREAD

**Issue by emilbruckner** [missive/emoji-mart#269]
Are there any plans for adding newer Emojis?
Where are they pulled in from?

**Comment by EtienneLem** [comment]
Our Emoji data provider isn’t supporting Emoji 11 yet, see https://github.com/iamcal/emoji-data/pull/146

Even if they did, another current blocker for us is that EmojiOne has been removed from emoji-data, see https://github.com/iamcal/emoji-data/pull/142 (+ #262). From what I see when spotting EmojiMart in the wild, EmojiOne seems to be the go-to set used. We’d need to find a way to keep supporting EmojiOne.

**Comment by nolanlawson** [comment]
I think removing EmojiOne in a major release would be reasonable.

FWIW, I am using native emoji in Pinafore, and Mastodon is using Twemoji. (And both projects are using all.json.)

**Comment by rugk** [comment]
Upstream i.e. emoji-data, merged https://github.com/iamcal/emoji-data/pull/152, so they support Emoji v11 now.

**Comment by rugk** [comment]
Is there any plan for a release? @nolanlawson

**Comment by lincolndbryant** [comment]
Looks like this is now released in `emoji-datasource@4.1.0` [here](https://github.com/iamcal/emoji-data/compare/v4.1.0...master), can we bump?

**Comment by rugk** [comment]
Any news, @nolanlawson? It may really just need bumping…

**Comment by EtienneLem** [comment]
As a matter of fact I looked into that yesterday, but `emoji-datasource` still hasn’t released to NPM the “new” emojis. We rely on that for the hosted spritesheets. I’ll look into publishing a fork.

**Comment by rugk** [comment]
Maybe it is time to look for alternatives: https://github.com/missive/emoji-mart/issues/384

**Comment by rugk** [comment]
[v5.0.0](https://github.com/iamcal/emoji-data/releases/tag/v5.0.0) of emoji-data has been released!

Now we should have up-to-date emojis! :smiley:

**Comment by rugk** [comment]
@nolanlawson Any news? 😃

**Comment by rugk** [comment]
Another month later? Soon Unicode 13 will be released... 😆

**Comment by EtienneLem** [comment]
Emoji 12.1 now available in v3.0.0
