### ISSUE TITLE
Can we get emoji sprite sheet as SVG?

### ISSUE THREAD

**Issue by satyapendem** [missive/emoji-mart#272]
Hi,

I'm using **emoji mart**. It was very nice. But, I'm using **apple** set and the sheet size is **64** but still the image quality of emojis are not that much good. Can I get svg images.

**Comment by nolanlawson** [comment]
This issue may be more appropriate for [emoji-data](https://github.com/iamcal/emoji-data), which is upstream from this project. It seems they only distribute PNGs.

**Comment by mikecann** [comment]
Seems like there is a PR to fix this but it hasnt been merged for some reason: https://github.com/iamcal/emoji-data/pull/175

**Comment by EtienneLem** [comment]
I’m afraid this is not possible, sorry.
