### ISSUE TITLE
Emoji onClick always provided. Is there a way to disable it?

### ISSUE THREAD

**Issue by dominikbulaj** [missive/emoji-mart#273]
Hi,
I use [Emoji](https://github.com/missive/emoji-mart#emoji) inside [Material-UI](http://material-ui.com) ImageButton and I have noticed it warns about onClick used inside that component:

> Warning: Failed prop type: Material-UI: you are providing an onClick event listener to a child of a button element.
Firefox will never trigger the event.
You should move the onClick listener to the parent button element.
https://github.com/mui-org/material-ui/issues/13957

I've investigated source code of Emoji and I've found that some handlers are passed even if they're not explicit provided by a developer:
https://github.com/missive/emoji-mart/blob/master/src/utils/shared-props.js#L40

What is reason for this? Why not check if provided property (e.g. onClick) is a function and trigger it when needed?

**Comment by nolanlawson** [comment]
emoji-mart should render its `<Emoji>` components as `<button>`s with `onClick`s. now. So this warning should go away. OTOH you probably won't want to wrap a button inside of another button
