### ISSUE TITLE
Can we export an object such that it gives me emoji unicode to all the emojis map?

### ISSUE THREAD

**Issue by daiict218** [missive/emoji-mart#275]
Hi, I'm using this module in my project. I have a text area and whenever I'm adding an emoji from Emoji Picker, I'm putting the emoji unicode so that browser can determine and show that appropriately so rendering the emoji, I need to send an emoji object to the EmojiIcon component which is been exported from this repo. So, if I'll have a map of emoji utf-8 codes to it's object, that'd be really great. Now, I'm having issues with converting emojis to unicode and some emojis can be of multiple code points

**Comment by nolanlawson** [comment]
Does importing the JSON file directly from https://github.com/missive/emoji-mart/tree/master/data solve this issue for you?

**Comment by daiict218** [comment]
Actually I wanted a behaviour something like [emoji-dictionary](https://github.com/IonicaBizau/emoji-dictionary#readme) but instead **name**, I wanted the unified value from the data but I guess this is not possible because few emojis are made up of multiple code points (hence multiple unified values). Should we implement some function like `emoji-dictionary` in `emoji-mart` as well where I can get the name of the emoji from the utf-8 values?

**Comment by nolanlawson** [comment]
What do you mean by "unified value from the data"? Does this data not exist in [the JSON files](https://github.com/missive/emoji-mart/tree/master/data)?

**Comment by daiict218** [comment]
This is resolved after the function `getEmojiDataFromNative` is added to the library

**Comment by daiict218** [comment]
We can close this issue
