### ISSUE TITLE
Emoji not showing if font size >= 325px

### ISSUE THREAD

**Issue by jimsheen** [missive/emoji-mart#291]
Hi there, 

Emoji is not showing past the font size 324px is this a bug or this intended behaviour? 

Thanks

**Comment by nolanlawson** [comment]
How are you modifying the font size? Could you provide some sample code to help reproduce the bug? Thanks!

**Comment by nolanlawson** [comment]
Closing for now, please reopen if there is a good repro or code snippet you can share. Thanks!
