### ISSUE TITLE
Provide i18n for multiple languages within emoji-mart itself

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#303]
https://github.com/missive/emoji-mart/issues/20 added i18n support, but unfortunately this way by letting devs configure it poses two problems:
1. Each app that uses this module has to provide translations for the strings again and again. IMHO, it would be preferable to ship the translations with this component here, so this translation work is done once and not again and again.
2. The Emojis itself are not translated. So you cannot search for "Lachend" as a German user e.g. and get Emojis like 😆.
   E.g. check out Twitter: They do translate Emojis in their Emoji picker, which sometimes is annoying, but sometimes can be helpful. Especially for non-devs or users that hardly speak English. For them, the search is basically not usable.

Note that if 2. is solved, 1. may get an even bigger problem, as you'll have to translate each Emoji (or more, with alternatives etc.).

**Comment by nolanlawson** [comment]
> Each app that uses this module has to provide translations for the strings again and again. IMHO, it would be preferable to ship the translations with this component here, so this translation work is done once and not again and again.

This is an interesting idea, but it potentially introduces a maintenance burden. Perhaps we could use something like [weblate](https://weblate.org/en/) to lessen the burden, though.

> The Emojis itself are not translated.

This may be a limitation of https://github.com/iamcal/emoji-data which is where the emoji data comes from.

**Comment by rugk** [comment]
> Perhaps we could use something like weblate to lessen the burden, though.

Obviously, choose whatever translation platform you want/you are comfortable with. That's why these are there... 😄

**Comment by Haraldson** [comment]
@rugk The tip about CLDR is a step on the way, but I’m always mega confused when arriving at their website. I’ve sifted through available `cldr-*-modern` repos on npmjs.com, but didn’t find which package includes the specified set of strings. Would you consider elaborating on this in the docs?

**Comment by rugk** [comment]
@Haraldson Do the following instructions from my downstream browser add-on using this lib here help?
See https://github.com/rugk/awesome-emoji-picker/blob/master/CONTRIBUTING.md#translating-emoji-terms-categories-skin-names-etc

**Comment by srl295** [comment]
I know this is old but for the record…

> IIRC you can download a ZIP and just do it locally, that might be easier.

Don't scrape the site, use the download forms.

> I’ve had a look at `cldr-annotations-modern`, but was only able to find annotations for each emoji, and not for the categories they belong to – the same strings the documentation claims exist _somewhere_.

You can use https://www.npmjs.com/package/cldr-annotations-derived-full instead which has the full derived data, in JSON form

> Also, the names available in [`main`](https://github.com/unicode-org/cldr/blob/latest/common/main/en.xml) sometimes use other keys than what is specified in emoji-mart, and sometimes the same – and the category names are uncapitalized. :/

You need to use a release, not the source repository.  

The category names, etc, from CLDR are coordinated with the Unicode emoji subcommittee.
