### ISSUE TITLE
100% width

### ISSUE THREAD

**Issue by drizki** [missive/emoji-mart#31]
Is there a way I can make the width fluid? I need to implement this to a responsive layout.

**Comment by EtienneLem** [comment]
Well any styles can easily be overwritten: [css/emoji-mart.css](https://github.com/missive/emoji-mart/blob/master/css/emoji-mart.css).

To make it 100% width you’d need to add `.emoji-mart { width: 100% !important }`. For performance reason, the categories size and anchors are memoized, so after resizing the window you’ll need to make sure that [`Picker#updateCategoriesSize`](https://github.com/missive/emoji-mart/blob/master/src/components/picker.js#L227-L232) gets called. `forceUpdate()` on the picker should do the trick.

i.e.
```js
window.addEventListener('resize', () => {
  let { picker } = this.refs
  picker.forceUpdate()
})
```

**Comment by smeijer** [comment]
This should now be possible, because #45 has been merged :smile:

**Comment by drizki** [comment]
@smeijer Thank you!
