### ISSUE TITLE
Native emoji preview of some emojis overlays text

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#310]
If you hover over 👨‍👩‍👦‍👦  and use the native Emoji set on Windows 10, the Emoji is too big (has too much width), so it overlays the actual text in the preview:

![grafik](https://user-images.githubusercontent.com/11966684/54708076-d41b6280-4b42-11e9-94e6-5358a8e01d34.png)

In general the space is quite limited there, and also not "overly" big Emojis scratch the edge of the text there:
![grafik](https://user-images.githubusercontent.com/11966684/54708264-4e4be700-4b43-11e9-9981-121712771860.png)

**Comment by rugk** [comment]
Okay, I have an excuse for you: The same issue happens on GitHub (yes, I've placed a space after the Emoji):

![grafik](https://user-images.githubusercontent.com/11966684/54708301-66236b00-4b43-11e9-9370-adbbfecd940b.png)

**Comment by nolanlawson** [comment]
I think this is related to #319

**Comment by pgonzalez-santiago** [comment]
Hello, Any news?

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
