### ISSUE TITLE
Searching with the emoji itself does not find anything

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#311]
I e.g. to search with `👦` it cannot find any emoji:
![grafik](https://user-images.githubusercontent.com/11966684/54738784-eaaed180-4bb5-11e9-9248-a8b47958ed33.png)

Now it may seem strange to search for an emoji, if you already have one, but IMHO, it is useful in one case: (use case:) **If I want to show related Emojis**.

Or, in this example, e.g. all family emojis where the boy (`👦`) is part of. This could result in the same result as this e.g.
![grafik](https://user-images.githubusercontent.com/11966684/54738877-52651c80-4bb6-11e9-9292-255bc8f45ccb.png)

**Comment by EtienneLem** [comment]
This is supported in latest version.
