### ISSUE TITLE
showSingleCategory option

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#312]
ngx-emoji-mart [does have an option](https://github.com/TypeCtrl/ngx-emoji-mart#user-content-picker) to show only a single category (`showSingleCategory`).

Maybe it is useful to have in the upstream project here, too?

It also seems to be quite easy to implement:
https://github.com/TypeCtrl/ngx-emoji-mart/blob/1e0406e11297d22092d7ba5a830be2562d33fc94/src/lib/picker/picker.component.ts#L248-L254

**Comment by EtienneLem** [comment]
Interesting, that is a good idea!

**Comment by EtienneLem** [comment]
Latest version uses virtualized list, it shouldn’t be needed anymore.
