### ISSUE TITLE
docs: document how to remove footer entirely

### ISSUE THREAD

**Issue by evnix** [missive/emoji-mart#325]
I feel the anchor/footer/ bar (css: emoji-mart-bar) takes too much screen real-estate  on smaller screens with very little added value.

I tried the showPreview={false} but it only seems to disable preview but not remove the anchor/footer bar which I feel is a bug.

The intended old code/functionality/issue that I found:
https://github.com/missive/emoji-mart/issues/42
https://github.com/missive/emoji-mart/commit/c607fd88641625618c33ea8fa5783c21902cbf16

workaround for now is:
```
.emoji-mart-preview {
  display: none;
}
```

**Comment by nolanlawson** [comment]
You have to disable `showPreview` and `showSkinTones` to remove the footer entirely. We could do a better job of documenting this.

**Comment by hankeliu2015** [comment]
Hi, I am still having issue disable the emoji footer in my react app. In Picker, set both showPreview={false) and showSkinTones={false}, the footer and preview still show. Have to use above workaround solution again. Anyone could help take a look? thanks!

**Comment by ArifDev99** [comment]
you have to write {previewPosition="none"}
