### ISSUE TITLE
Realise date

### ISSUE THREAD

**Issue by nm1l0serd0v** [missive/emoji-mart#326]
Hello can you release the latest functionality you added in last 3 pr's? I found that `getEmojiDataFromNative` is not available in the latest release available from npm

**Comment by nolanlawson** [comment]
This is a request to update. Yes, we should do that.

@EtienneLem Could you please push out a minor release?

**Comment by nolanlawson** [comment]
Ah nevermind, looks like this is in 2.11.0 now.
