### ISSUE TITLE
Fails for more than 17 emojis per line

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#331]
### Setup

emoji mart settings:
```
{
  "perLine": 17
}
```

It is independent of the size and emoji set. (I've tried and reduced the test case to this already.)

Reproducible in: Firefox 66 and Firefox 68

I do use https://github.com/rugk/emoji-mart-embed/, which – [very similar to your example code](https://github.com/nolanlawson/emoji-mart-outside-react) – uses preact & remount. (I do use the exact build in the included `dist` dir.)

## What happens

Nothing is displayed. Exception is thrown.

\>= 17 emojis per line result in an exception and nothing being shown, I've selected the line that Firefox says was the one, where the error happened (only the last error in the console is important)
![17error](https://user-images.githubusercontent.com/11966684/55351731-5c90f000-54bf-11e9-8dbf-bfc9104ba375.png)

Error is this one (note that i only have sourcemaps there, so that's why the error itself still used these shortened identifiers):
```
TypeError: e is undefined
index.js:84:3
    b index.js:84
    i category.js:112
    filter self-hosted:318
    getEmojis category.js:112
    render category.js:155
    Preact 13
    h remount.es6.js:361
    mount remount.es6.js:347
    onMount remount.es6.js:461
    connectedCallback remount.es6.js:86
    init EmojiPicker.js:74

```

One time, I was able to catch a more descriptive error:
```
ReferenceError: emoji is not defined
debugger eval code:1:1
20:48:10.845
TypeError: e is undefinedindex.js:84:3
    b index.js:84
    i category.js:112
    filter self-hosted:318
    getEmojis category.js:112
    render category.js:155
    Preact 13
    h remount.es6.js:361
    mount remount.es6.js:347
    onMount remount.es6.js:461
    connectedCallback remount.es6.js:86
```
: 
## What should happen

Show emojis.

**Comment by rugk** [comment]
Hmm, cannot reproduce anymore… :thinking:

**Comment by rugk** [comment]
Can reproduce again. This is really strange and seems to happen only sometimes, but I clearly see that it works for 16, but fails for 17…

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
