### ISSUE TITLE
Function to manually set emoji in preview pane

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#333]
## Use case

I have an emoji picker, and after clicking on an emoji I want it to stay visible and display the just "selected" emoji at the bottom panel (the preview), as it was when hovering over the emoji.

## Proposed solution

It would be great to have a kind of `setPreviewEmoji` function, where I can override what emoji is to be shown in the preview.
Also, it/I should obviously then (be able to) disable the hovering effect that changes the emoji, so the user can actually select text (like the shortcode or so) there. 

And yes, I also want to be able to revert both things to the "default behaviour".

**Comment by EtienneLem** [comment]
This should be possible by configuring which preview emoji is displayed.
