### ISSUE TITLE
getEmojiDataFromNative function returning null for emoji 1⃣

### ISSUE THREAD

**Issue by daiict218** [missive/emoji-mart#334]
Hi,

I'm using `getEmojiDataFromNative` to find the emoji and I'm passing it the correct arguments. However it is returning me null for set `twitter`. I'm attaching the screenshot for the issue. 

<img width="881" alt="Screenshot 2019-04-13 at 10 28 48 PM" src="https://user-images.githubusercontent.com/5678132/56082889-f0f23f80-5e3b-11e9-9af6-5f9a2ffdd319.png">

**Comment by pederjohnsen** [comment]
@daiict218 this works fine for me
<img src="https://i.imgur.com/b91XT93.png?1" width="500" height="auto" style="max-width: 100%;">

Are you sure the unicode isn't "polluted"? :thinking:

**Comment by nolanlawson** [comment]
Closing for now, please reopen if it's possible to repro this using the storybook or another repro method (instructions for running the storybook are in the readme). Thanks!
