### ISSUE TITLE
Cannot use within redux form due to emoji categories

### ISSUE THREAD

**Issue by The-Code-Monkey** [missive/emoji-mart#337]
The emoji categories are missing the type="button" so they are causing my redux form to submit and i can't see a reason why type="button" doesn't need to be there i will happily make a pr for this if you would like.

**Comment by nolanlawson** [comment]
I'm confused as to what you mean... it seems to me that the categories do have `type=button`?

![Screenshot from 2019-06-29 08-17-40](https://user-images.githubusercontent.com/283842/60386160-65557b80-9a46-11e9-8661-fc317419924f.png)

**Comment by nolanlawson** [comment]
Closing for now, please reopen if this is still an issue!
