### ISSUE TITLE
onClick handler also triggers for keyboard selection

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#342]
## STR

0. Have the `onClick` handler bound.
1. Use tab to navigate to a random emoji.
2. Press space or enter.

## What happens

The `onClick` event is triggered, although it was not actually a click that triggered this:
It receives this event:
![grafik](https://user-images.githubusercontent.com/11966684/57225456-af088380-700c-11e9-8f21-676d633101d2.png)

```js
click { target: button.emoji-mart-emoji.emoji-mart-emoji-native, buttons: 0, clientX: 0, clientY: 0, layerX: 0, layerY: 0 }
```

This looks like a fake ClickEvent… (with 0/0 as coordinates)

## What should happen

No event. The doc says this only triggers for clicks…

## System

emoji-mart 2.11
Firefox 66

**Comment by nolanlawson** [comment]
For accessibility reasons, isn't this the proper behavior?

**Comment by rugk** [comment]
Hmm, possibly. But maybe not. It looks like a custom implementation.

So here are the problems I am having with that:
* The doc is wrong. `onClick` literally says "Not called when emoji is selected with `enter`", which is literally wrong… :thinking: 
* If this behaviour is intended, why do we have an `onSelect` callback at all? I mean, we could then drop one of these two…
* Actually the `event` parameter (with 0/0 coordinates) is bad, because…
  1. it's faked/lying: I would have expected a different input event or so, because it's literally lying as there was no click.
  2. it complicates implementation: I wondered about this, and first needed to figure out why this unexpected callback was called. Also I first blindly trusted the `event` parameter. (I did not expect a faked value, after all.) And if you get `0` values for the mouse position there, this can lead to pretty annoying bugs!
  3. it does not actually bring any benefit: The `event` parameter is literally useless. It consists only of "null"/0 values, which are all fake – obviously, because there was no click.

The use cases I saw for these two callbacks are:
* Because I mind accessibility as a web dev, I'd usually always use `onSelect`, so that it also triggers for the things I need. 
* When I actually need to get the click event (e.g. for the click position!, which could be very useful) I use `onClick`.

## Solutions

Actually, if we mind accessibility I would argue to deprecate/remove `onClick` all-together and instead add the `event` parameter to `onSelect`? (Maybe with a custom value/event for keyboard triggers, so one can differentiate them and not run into the issues mentioned above?)

If that is too drastic, we could remove that fake-triggering for `onClick`. Then we could mind devs in the doc to use `onSelect` for "usual" emoji handling. (if that's not obvious?)

The thing we should do **at a very minimum** is to adjust the doc. (And actually, we would have to document this faking/wrong value that is sent and mind devs to check the value when implemented, if that is not changed. Ugh… that's not really a good API.)

**Comment by nolanlawson** [comment]
I agree that the docs/existing code should probably be fixed if we are doing different behavior for clicks versus enter/space to select. It shouldn't matter whether someone is using a mouse, keyboard, screen reader, touchpad, whatever.

**Comment by EtienneLem** [comment]
This shouldn’t be a concern anymore in latest version.
