### ISSUE TITLE
Emojis are misplaced at different sections

### ISSUE THREAD

**Issue by hetpatel33** [missive/emoji-mart#346]
When compared to the standard Facebook emoji keyboard, some of the emojis are misplaced at different sections in the emoji-mart keyboard. 

Example: Some of the Objects emojis are displayed in Travels & Places section,

<img width="464" alt="Screenshot 2019-06-20 at 3 03 45 PM" src="https://user-images.githubusercontent.com/13877514/59838734-0f5d4580-936d-11e9-83ba-4f2a9bf3b269.png">

**Facebook Emoji Picker**

<img width="315" alt="Screenshot 2019-06-20 at 3 04 08 PM" src="https://user-images.githubusercontent.com/13877514/59838752-171cea00-936d-11e9-9bb9-1ebc2e76c889.png">

**Comment by nolanlawson** [comment]
This looks like an issue with [emoji-data](https://github.com/iamcal/emoji-data), not emoji-mart. Could you please file the issue over there?
