### ISSUE TITLE
Gender specific emojis are rendered weirdly in Edge

### ISSUE THREAD

**Issue by pnagy** [missive/emoji-mart#350]
When an emojis is the composition of an emoji and a gender sign it's being rendered separately in Edge. When it's hovered it's shown correctly in the preview field. Check the attached image for more info:

![image](https://user-images.githubusercontent.com/4050025/60188885-ec78d880-9827-11e9-9044-6e5e627fa15a.png)

(In the above image the emoji being in the preview square is shown nowhere in the list, the woman emoji with the male sign is hovered.)

**Comment by rugk** [comment]
Which Edge version? (the Chromium-based or the old one?)

**Comment by nolanlawson** [comment]
On Windows 10 1809, I can repro in Edge but not Chrome or Firefox. Nor can I repro in the Edge Dev version (using the Chromium engine). So I'd say this will be fixed when Edge moves to Chromium.

**Comment by nolanlawson** [comment]
I'm also closing because I don't see what emoji-mart can do about this. In "native" mode, we explicitly defer to the native emoji provided by the browser and OS. If those native emoji are rendered incorrectly, there's little we can do.
