### ISSUE TITLE
We should modify Nimble-Picker for supporting React 17.x

### ISSUE THREAD

**Issue by h6ak** [missive/emoji-mart#356]
`componentWillReceiveProps` will be removed in React 17.x.
We should modify Nimble-Picker component for supporting React 17.x.

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by viiiprock** [comment]
Vote !

**Comment by MateuszDev96** [comment]
I'm waiting too :(

**Comment by nolanlawson** [comment]
Seems fixed by #372, please reopen if I'm wrong
