### ISSUE TITLE
how can i integrate emoji-mart with quill or react-quill

### ISSUE THREAD

**Issue by phoenixrever** [missive/emoji-mart#357]
Does any one know how to do it?

**Comment by krvajal** [comment]
I have done it here https://codesandbox.io/s/eloquent-leftpad-dum5z

**Comment by nolanlawson** [comment]
Thanks for helping out! :)

**Comment by alxvallejo** [comment]
> I have done it here https://codesandbox.io/s/eloquent-leftpad-dum5z

No longer works ..
