### ISSUE TITLE
React DOM tree root should always have a node reference

### ISSUE THREAD

**Issue by apasquelin** [missive/emoji-mart#36]
Hello,

I have an error when I use a category and I click on a smiley:

> Uncaught Error: React DOM tree root should always have a node reference.
>     at invariant (bundle.js?v=1:10302)
>     at Object.getNodeFromInstance (bundle.js?v=1:15812)
>     at Object.didPutListener (bundle.js?v=1:29212)
>     at Object.putListener (bundle.js?v=1:14889)
>     at Object.putListener (bundle.js?v=1:23009)
>     at CallbackQueue.notifyAll (bundle.js?v=1:17958)
>     at ReactReconcileTransaction.close (bundle.js?v=1:27837)
>     at ReactReconcileTransaction.closeAll (bundle.js?v=1:18329)
>     at ReactReconcileTransaction.perform (bundle.js?v=1:18276)
>     at ReactUpdatesFlushTransaction.perform (bundle.js?v=1:18263)

Do you have a solution ?

Thank you

PS : `"react": "latest"`

**Comment by ningo-agilityio** [comment]
I got the same error when follow this guideline https://gist.github.com/robertgonzales/e54699212da497740845712f3648d98c#file-getuserconfirmation-jsx-L9

**Comment by nolanlawson** [comment]
This issue does not reproduce in the latest version of React AFAIK. Please reopen if I'm incorrect about this. Thanks!
