### ISSUE TITLE
Cannot read property 'value' of null

### ISSUE THREAD

**Issue by minhtranite** [missive/emoji-mart#360]
I use Sentry to log errors and there is an issue with emoji-mart:

![Screen Shot 2019-09-04 at 5 31 01 PM](https://user-images.githubusercontent.com/5418628/64265501-3a633880-cf5d-11e9-8277-70ba69aa5054.png)

**Comment by nolanlawson** [comment]
Hm, I'm not sure how this could possibly happy. It can only happen if the `input` (`this.input`) doesn't exist, but the search somehow happens. Do you have a test to reproduce? Are you using some React-alike (such as Preact or Inferno)?

**Comment by theopak** [comment]
reported as closed by #419

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
