### ISSUE TITLE
Problems with the flags country 

### ISSUE THREAD

**Issue by DanielHerreraC** [missive/emoji-mart#365]
Hello guys

I have problems with the flags country emoji’s that are not displayed in Windows. The images are replaced by the 2-letter code, for example: Canada = CA, Spain = ES, USA = US.  (see the image.)

![errors_flags](https://user-images.githubusercontent.com/23225960/65054972-6d81d080-d93c-11e9-862c-9c34b6d5bbd0.png)

The same problems happens in all browsers that I have tested.

Do any of you have an idea of how I can fix this problem?

Thanks,

**Comment by MaximeTroiano** [comment]
Same problem

**Comment by nolanlawson** [comment]
I believe this is just an issue with how native emoji are displayed on Windows:

- https://stackoverflow.com/a/54663926
- https://blog.emojipedia.org/emoji-flags-explained/

> Microsoft doesn't support any country flags on Windows, instead showing the two-letter country codes

**Comment by nolanlawson** [comment]
There's nothing we can do, as it's up to the OS to decide how to show various emoji.

**Comment by bigCongee** [comment]
赞
