### ISSUE TITLE
Disable sorting of frequently used emojis on click

### ISSUE THREAD

**Issue by vrizo** [missive/emoji-mart#366]
Hi, @EtienneLem !

Thanks for Emoji Mart — an excellent project which we use on our project!

We faced a problem reported by our users. Sorting of frequently used emojis is annoying because it fires when the user clicks on the emoji.

<img src="https://media.amplifr.com/images/social_images/013/286/618/img.gif" alt="Catch me if you can" width="402" height="412" />

What do you think about disabling sorting on the fly in favor of sorting after component mounting?

I found the same issue here, but the author decided to close it: https://github.com/missive/emoji-mart/issues/265. I don't think that it is a bug, but I think it might be improved.

Thank you!

**Comment by vrizo** [comment]
Hey, @EtienneLem @nolanlawson !

Do you have any thoughts on this?

I noticed that there is the same behavior on macOS in the native mini picker. But it works in full-size native picker in another way. 1:1. Attaching a GIF.

<img src="https://media.amplifr.com/images/social_images/013/477/642/img.gif" alt="macOS emoji picker" />

Thank you!

**Comment by vrizo** [comment]
Hi, @EtienneLem @nolanlawson ! Do you have any ideas about this feature? Thanks!

**Comment by edgesinghkataria** [comment]
We can give a property to enable/disable this functionality.
Let me know what suits best.
I've fixed this In my current project, will be happy to submit a PR

**Comment by EtienneLem** [comment]
I feel like this should be the default and be re-sorted only when mounting

**Comment by nolanlawson** [comment]
I agree, having the icons move out from under your mouse is confusing, even if the native macOS emoji picker also does this.

**Comment by SaraRandolph** [comment]
Hi all! I have been working on a solution for this and I'm wondering if you guys would be open to reviewing a PR for this issue. This will be my first PR for an open source project so it won't be perfect but it will at least be on the road to a solution for this enhancement!

**Comment by EtienneLem** [comment]
@SaraRandolph Absolutely! You will notice that we’ve been pretty slow on reviewing/implementing lately. I will have some time to allocate on this very soon ✌️

**Comment by SaraRandolph** [comment]
@EtienneLem sounds good! no rush! I'll make the pr this afternoon. thank you!

**Comment by EtienneLem** [comment]
Fixed with #417
