### ISSUE TITLE
Use custom icon as emoji for emoji-mart-preview-emoji

### ISSUE THREAD

**Issue by ssudekum** [missive/emoji-mart#369]
After loading my custom emoji, it seems that referencing its name in the emoji property does not render my custom emoji in the preview area. I would like to load a specific image to that preview.

**Comment by nolanlawson** [comment]
Could you provide some code to show the issue you're running into? I'm not quite understanding from the description here. Thanks!

**Comment by kafinsalim** [comment]
I think I just made a duplicate issue, but I have an example here https://github.com/missive/emoji-mart/issues/456

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
