### ISSUE TITLE
(Improve) RTL language support

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#370]
## Background

After we can localize the picker (see https://github.com/missive/emoji-mart/issues/20), of course people localized it to RTL languages.

I am using this and noticed an issue in my downstream project here: https://github.com/missive/emoji-mart/issues/318
There is the full writeup, and all details, so I'll just summarize it here.

Basically I set the CSS [`direction`](https://developer.mozilla.org/docs/Web/CSS/direction) property. This is done as in [this example code](https://developer.mozilla.org/de/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Predefined_messages) for my add-on.
And as far as I see, it is indeed intended top be set as a global style…

And IMHO that's useful, because it should apply to _everything_, because _everything_ is localized there then. And actually, **it already works quite great**, because the top part of the picker works flawlessly…

However…

## Symptom

This is from https://missive.github.io/emoji-mart/ just with the applied CSS property via devtools:
```diff
body {
+ direction: rtl;
}
```

![grafik](https://user-images.githubusercontent.com/11966684/67146919-55310880-f290-11e9-912b-afd8f8d7382c.png)

So what's wrong:
1. the emoji preview should be at the right
2. the skin selector should be on the left

## Problem

The underlying problem though is of course is missing/proper RTL language support.

### Worse

In my case, it was worse and the skin selector [overlapped](https://github.com/rugk/awesome-emoji-picker/issues/63#issue-509460778) the text.

I guess this is because if you actually use RTL languages, they automatically, _always_ switch to `text-align` to `right`, so I've emulated this here in the dev tools on the website to reproduce:

![grafik](https://user-images.githubusercontent.com/11966684/67147373-b529ae00-f294-11e9-828a-d3a4c921aed3.png)

Funnily enough, I've noticed I've already reported this, but there in https://github.com/missive/emoji-mart/issues/318, but now this is not a rogue style I can just unset, because it is part of the translated version.

## Solution

As you can see, it works quite well, but these two issues may still be fixed.

As said, I've noticed this before in https://github.com/missive/emoji-mart/issues/318 somewhat, but 1. this here is about the `direction` property and not the `text-align` (which I do not manually set) and 2. is a internationalization (i18n) issue in this project, because (only) RTL language users experience this bug.

## System

Firefox 69

**Comment by EtienneLem** [comment]
Latest version has a basic support for RTL languages (see Persian and Arabic for examples).
