### ISSUE TITLE
Emojis are black and white

### ISSUE THREAD

**Issue by JavaJamie** [missive/emoji-mart#373]
Hi all.

I'm just dabbling with this emoji picker and whenever I select and render one using the .native field it's black and white and not the coloured version I see inside the picker. This is probably a really obvious issue but I haven't seen it mentioned in the documentation. Does anybody know how to resolve this?

Thanks all

**Comment by JavaJamie** [comment]
Native flag was the issue.

**Comment by rafael90cr** [comment]
Could you, please, be more specific? I'm struggling with this for days...

**Comment by Libron** [comment]
Hi there. I had same issue. How did you fix this ? Need help

**Comment by JavaJamie** [comment]
It turns out I wasn't using the native flag. I'm using Ubuntu so the emojis render in black and white and that is the expected result (I wasn't aware of this at the time). I checked the emojis in Edge on Windows and Chrome on am Android device and they render in colour.

**Comment by kishan-chauhan** [comment]
![image](https://user-images.githubusercontent.com/12165360/94654797-31d56100-031b-11eb-8268-d52bd39928a3.png)
Black and white issue in some of emoji icon and some of display in colorful anyone have to know how resolved this issue please.
`<emoji-mart class="emoji-mart" set="{{set}}"  title="Pick your emoji…" sheetSize="32"></emoji-mart  >`
and set is google `set = 'google';`

**Comment by MeiJunNa** [comment]
I still didn't understand how to solve this problem, throughemoji.native get the expression is still black border. Can you be more specific?
![image](https://user-images.githubusercontent.com/30679487/100203704-e9fb4080-2f3d-11eb-834b-fd92dd7b9f0e.png)


import './App.css';
import React, { Component } from 'react'
import 'emoji-mart/css/emoji-mart.css'
import { Picker } from 'emoji-mart'
import { Input } from 'antd';
import "antd/dist/antd.css";
import { SmileOutlined } from '@ant-design/icons';
import _ from "lodash"
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      chatContent: "",
      showEmojiModal:false
    }
  }
  onChatContentChange = (value) => {
    this.setState({ chatContent: value })
  };
  searchEmoji(emoji, event) {
    console.log("emoji=====", emoji)
    emoji.unified="google";
    this.setState({ emoji: emoji, showEmojiModal: false })
    let { chatContent } = this.state;
    chatContent = !_.isEmpty(chatContent) ? (chatContent + emoji.native) : emoji.native;
    this.setState({ chatContent });
  }
  render() {
    return (
      <div className="App">
        <div className="emoji_container">{this.state.showEmojiModal&&<Picker 
          set='apple'
          emoji=''
          showPreview={false}
          showSkinTones={false}
          native={false}
          onClick={(emoji, event)=>this.searchEmoji(emoji, event)}/>}
        </div>
        {/* emoji=''作用：Hide default preview image;
        native={true}可以优化和加速组件,但是设置之后，有些表情不显示;
        showPreview={false}和showSkinTones={false}一起 ，可以隐藏下方的preview
        */}
        <div style={{ padding: 15, paddingBottom: 10, cursor: 'pointer' }} onClick={() => this.setState({ showEmojiModal: !this.state.showEmojiModal })}>
            <SmileOutlined style={{ fontSize: 20, color: '#787878' }} />
        </div>
        <div style={{ display: 'flex', flex: 1, alignItems: 'center', paddingLeft: 10, paddingRight: 10, paddingBottom: 10 }}>
          <Input.TextArea
            style={{ display: 'flex', flex: 1, height: '100%', boxShadow: "none", fontSize: 16 }}
            placeholder="请输入...您可按Enter键发送消息"
            value={this.state.chatContent}
            onPressEnter={e => { }}
            onKeyUp={this.onKeyUp}
            onChange={e => this.onChatContentChange(e.target.value)}
          />
        </div>
      </div>
    );
  }
}

export default App;
