### ISSUE TITLE
When I switch new language, the object `i18n` has update, but the component's UI not update

### ISSUE THREAD

**Issue by edward-tes** [missive/emoji-mart#379]
Hello,
    I use `i18n` to control my internal. When I set a new language,  I will change the `i18n`. The `i18n` has changed, but the component's UI not update.
![image](https://user-images.githubusercontent.com/4544349/69038673-42435c80-0a25-11ea-9851-83da7f18f3d9.png)

**Comment by nolanlawson** [comment]
Which version of React are you using?

**Comment by luyc** [comment]
> Which version of React are you using?

React ^16.12.0

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
