### ISSUE TITLE
[Discussion] Retry mechanism when sprite image broken

### ISSUE THREAD

**Issue by li6834300** [missive/emoji-mart#381]
This issue usually happens when image transporting, usually due to network turbulence. 
Some when user download emoji sprite map, the image broken and show as a half completed image. Some emoji will be missing. Please see attached. The problem is, the browser caches the image, and will not trigger a re-download. That means if one user meet this issue, it will not be fixed until he clear his cache. 

Does anyone know some solution? 
![image](https://user-images.githubusercontent.com/1820864/69508036-8a0b3c00-0f6f-11ea-820b-1df1ce1278d0.png)

**Comment by nolanlawson** [comment]
There are several potential solutions:

- Cache the sprites in Service Worker or IndexedDB to ensure it's always available
- Use native emoji instead
- Ensure the file is fully downloaded before loading emoji-mart, or else fall back to native emoji

**Comment by nolanlawson** [comment]
Hope that helps! In any case I don't believe it's within emoji-mart's scope to handle network retries directly.
