### ISSUE TITLE
TextArea insert native emoji

### ISSUE THREAD

**Issue by mks1948** [missive/emoji-mart#382]
Hi !
I have a big problem because, i want to insert native emoji in textarea , in firefox 90% emoji works fine but base like faces are black-white. 
In chrome and opera, worked emoji likes faces but are black and white, others all are empty rectangle.
![a](https://user-images.githubusercontent.com/26583244/69550871-14699500-0f9c-11ea-89f2-998c2ad17b18.png)
My code : 
`let sym = e.unified.split('-');
    let codesArray = [];
    sym.forEach(el => codesArray.push('0x' + el));
    let emoji = String.fromCodePoint(...codesArray);
    this.setState(prevState => {
      return {
        message: prevState.message + emoji,
      };
    });
`
How makes displays in textarea emoji ?

**Comment by nolanlawson** [comment]
Instead of using `e.unified`, you should be able to directly use `e.native`:

```js
var textarea = document.createElement('textarea')
textarea.value = e.native
document.body.appendChild(textarea)
```

I tested this in the storybook and it works. :)
