### ISSUE TITLE
Picker's icons props always throw ts error

### ISSUE THREAD

**Issue by jiangpingshendd01** [missive/emoji-mart#383]
Likes the doc example:

![屏幕快照 2019-11-26 上午10 52 22](https://user-images.githubusercontent.com/53250925/69595569-e71ff400-103a-11ea-88ed-536cecc3bd0f.png)
![屏幕快照 2019-11-26 上午10 53 10](https://user-images.githubusercontent.com/53250925/69595589-f56e1000-103a-11ea-8b2a-62023f4d8518.png)

I has spend much time but I was blocked...Anyone know how to fix it?

**Comment by nolanlawson** [comment]
Since emoji-mart does not host its own type definitions, maybe this is an issue with [@types/emoji-mart](https://www.npmjs.com/package/@types/emoji-mart)?

**Comment by nolanlawson** [comment]
Closing for now as we do not host our own TS definitions and I'm not sure it's within our scope to do so.
