### ISSUE TITLE
Implicit dependency on core-js

### ISSUE THREAD

**Issue by nolanlawson** [missive/emoji-mart#393]
Unfortunately, it looks like we allowed `core-js` to sneak into our dependencies, due to `Object.values()` (#351) and `JSON.stringify` (#392).

This adds about ~5kB extra to the bundle size, and of course will break if someone doesn't have `core-js` in their dependencies, since it's an implicit dependency.

**Comment by Mefu** [comment]
Can you please release a version that includes this fix?

**Comment by EtienneLem** [comment]
Will do very soon

**Comment by lastnigtic** [comment]
It seems that the new version has not been released yet
