### ISSUE TITLE
Lazily build emoji index

### ISSUE THREAD

**Issue by nolanlawson** [missive/emoji-mart#396]
Currently, when you mount `emoji-mart`, it runs `buildIndex` which builds the search index, and can be an expensive operation:

![Screenshot from 2019-12-24 09-37-57](https://user-images.githubusercontent.com/283842/71421682-46205b00-2631-11ea-9083-ae81e056c7c8.png)

(The above screenshot is in Chrome on 4x slowdown using Preact and several custom emoji – buildIndex takes ~300ms.)

It seems we should be able to run `buildIndex` on-the-fly only when the user actually starts searching for something. If the user opens up the emoji picker and only intends to scroll and click, then `buildIndex` is wasted work.

**Comment by JailBreakC** [comment]
same issue with me, it takes about 1000ms to open the picker on my computer using react@16.9.43
