### ISSUE TITLE
Optimize sheet size for retina / not-retina

### ISSUE THREAD

**Issue by EtienneLem** [missive/emoji-mart#4]
- [x] Make `sheetURL` optional and fallback to unpkg with current [emoji-data](https://github.com/iamcal/emoji-data) version
- [x] Add `set` prop (apple|google|twitter|emojione)
- [ ] Detect if current device is retina
- [ ] Serve dynamic sheet size (16|20|32|64)

**Comment by wmdmark** [comment]
Hi, I'm having trouble with emoji's showing up fuzzy on retina screens... assuming this would fix that issue but in the mean time, is there a workaround for this?

**Comment by EtienneLem** [comment]
You’re right, I do see them blurry there https://missive.github.io/emoji-mart on Chrome when the size is 24px. It looks like a browser resampling issue, they look better on Safari. If you set the size to 32px (the sheet is 64px), they look crisp on Chrome.

Knowing that, you could try to serve a sheet that has exactly @2x of your emoji size until I figure out the right way to calculate the `backgroundSize` dynamically.

I haven’t tested, but if you take that sheet https://unpkg.com/emoji-datasource@2.4.4/sheet_apple_64.png (2624px) — with the rule of three — I guess if you make it 1968px wide it should work.

`(YOUR_EMOJI_SIZE * 2) * 2624 / 64 = @2x sheet size`

Let me know if that changes something.
