### ISSUE TITLE
darkMode default behaviour

### ISSUE THREAD

**Issue by alexandr-bbm** [missive/emoji-mart#404]
Hi there, and thanks for the library and recent update with darkMode.

I wanted to report very possible undesired effect of current default `darkMode` property value. Now, as per readme, it is set to `true`  if the browser reports  if the browser reports `prefers-color-scheme: dark`. I think that a huge amount of projects using this nice lib doesn't support theming (like mine). Then, if a user of the app has dark theme enabled in OS, but site has white background,  emoji-mart would lead to regression

The pictures below show what happened in my project

before
![image](https://user-images.githubusercontent.com/11938458/72139143-e2b75c80-3396-11ea-968b-063c04c69951.png)

after
![image](https://user-images.githubusercontent.com/11938458/72139164-ea770100-3396-11ea-813b-91a98accb81b.png)

I think emoji-mart shouldn't get default value for the darkMode from the browser/OS settings, as it seems to much responsibility for the widget lib and it can cause significant visual regression in the apps which do not support theming.

**Comment by EtienneLem** [comment]
Good point. `darkMode` probably is more of a “breaking” change than we anticipated. I think it could be 2 props:

- `autoDarkMode`: False by default. When true, it’ll use `prefers-color-scheme: dark`
- `darkMode`: False by default. When true, forces dark theme. Could even be `theme: 'dark'` which would be a first step at providing more themes.

**Comment by rugk** [comment]
IMHO your screenshots look not that bad. It's a little unexpected to have a dark/themed version there, but well...
