### ISSUE TITLE
Rendering strings with emoticons

### ISSUE THREAD

**Issue by TheDanielMoli** [missive/emoji-mart#405]
Is there a function or library to properly render strings according to `emoji-mart` shortcodes and emoticons? `react-emoji-render` almost does a good job but gets most of the emoticons wrong.

**Comment by TheRav3n** [comment]
@missive

Since `emoji-mart` is licensed under BSD 3-Clause "New" or "Revised" License, I would like to request permission to develop and publish an `emoji-mart-render` module. Also, would like to know if I have to stick to this license for the new package or if I can provide a more open license.
