### ISSUE TITLE
Problems with native icons

### ISSUE THREAD

**Issue by Pastov** [missive/emoji-mart#406]
Hello 

i have some probles with the icons in the text area and the body in my chat, the icons show in black but in the box everything is alright.

![Captura de pantalla de 2020-01-17 00-55-18](https://user-images.githubusercontent.com/26732348/72583312-92735980-38c4-11ea-9ed0-de0b7a044c2b.png)

**Comment by Libron** [comment]
I have always black and white output. How to get colored same as picked on ?

**Comment by rugk** [comment]
How you insert emojis into your native app is your own task. If you use the native emoji code that is just an Unicode char,  i.e. it depends on how the browser/OS displays them.

Alternatively you could use the Emoji tag of this lib to render it as an image: https://github.com/missive/emoji-mart#emoji
