### ISSUE TITLE
Navigation items not clickable after window onclick event checker

### ISSUE THREAD

**Issue by adventurini** [missive/emoji-mart#407]
Making the emoji picker into a modal has created some funky bugs. I am not really sure another way to target the picker other than through the event path, using the window click event. I got everything to work, except for the navigation items are now disabled when I run the window event checker.

 I have tried several ways of running the for loop, including breaking out of it, but nothing seems to work.

```export default function EmojiPicker() {
    return (
        <div className="emoji-picker">
            <Picker className="emoji-picker" set='emojione' style={{ zIndex: 1,
                  position: "absolute",
                  top: "230px",
                  left: "34%" }}/>
        </div>
    )
}

 {emojiClick &&
              <div
                style={{
                  zIndex: 1
                }}
              ><EmojiPicker />
              </div>}

  useEffect(() => {
    window.onclick = e => {
      var classNameArray = [];
      if (e.target.className.baseVal === "create-post-icon smile-icon") {
        {
          setEmojiClick(!emojiClick);
        }
      } else {
        for (let i = 0; i < e.path.length; i++) {
          if (e.path[i].className === "emoji-picker") {
            classNameArray.push("match");
          } else {
            null;
          }
          if (classNameArray.length > 0) {
            setEmojiClick(true);
          } else {
            setEmojiClick(false);
            classNameArray = [];
          }
        }
      }
    };
  });```

**Comment by panalgin** [comment]
I somewhat have a similar problem too, upon using emoji-mart inside a modal container, my navigation items are no-longer clickable until I manually click one of the emojis in the scrolled-container. This happens only at the first time the component supposed to be mounted. And the problem happens after an full-refresh (f5) has happened.

**Comment by kenpaxtonlim** [comment]
Has a solution been found for this? I am using this picker inside a dropdown popover, and my categories buttons (i.e. navigation items) does not work when I click them. The anchor only changes when I select an emoji from a different category.

**Comment by mlshv** [comment]
I had a similar problem too. Switching from display: block/none to visibly: visible/hidden fixed it for me

**Comment by glidepro** [comment]
> I had a similar problem too. Switching from display: block/none to visibly: visible/hidden fixed it for me

thank you for your suggestion, that fixed it for my case as well

**Comment by Dikshakalbhor** [comment]
> I had a similar problem too. Switching from display: block/none to visibly: visible/hidden fixed it for me

Where to set visibility:visible/hidden

**Comment by Dikshakalbhor** [comment]
> I had a similar problem too. Switching from display: block/none to visibly: visible/hidden fixed it for me

Where to set visibility:visible/hidden?

**Comment by glidepro** [comment]
@Dikshakalbhor I wrapped the EmojiPicker component in a div and put the visibility property on that.

**Comment by Dikshakalbhor** [comment]
> @Dikshakalbhor I wrapped the EmojiPicker component in a div and put the visibility property on that.

okay

**Comment by shabspb** [comment]
@Dikshakalbhor @glidepro could you send the code?

**Comment by SagivAsraf** [comment]
> I had a similar problem too. Switching from display: block/none to visibly: visible/hidden fixed it for me

fixed for me as well! Thanks!!! :)

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.

**Comment by kickbu2towski** [comment]
I am facing this issue when using the picker inside a drawer component.

https://github.com/missive/emoji-mart/assets/122152070/590555e1-5f64-4bc3-94d6-b1abf717c3e2
