### ISSUE TITLE
Get native icon from icon id

### ISSUE THREAD

**Issue by idjuradj** [missive/emoji-mart#408]
Hi all,
I have been looking into the docs, but haven't found something that would match my needs.
Basically, I need to get native icon or emoji object based on emoji id provided

**Comment by adink829** [comment]
You can import the emojiIndex from the library and access it that way...
```
import { emojiIndex } from 'emoji-mart';

const getNativeEmojiFromId = (emojiId) => emojiIndex.emojis[emojiId].native
```
