### ISSUE TITLE
running EmojiMart in production 

### ISSUE THREAD

**Issue by shakesBeardZ** [missive/emoji-mart#412]
I'm trying to implement an emoji picker with a text input, I came across a package called Emojimart it was really good and working effectively, but running it in production makes my bundle size too big, so I'm wondering if there is anyone who used it in production and if there are any tips on how to make it production-ready?
Note: reproducing what I have will take only 2 steps
create react app with create-react-app
install emojimart
then check the bundle size and performance of the app, you will notice the difference.

**Comment by 0xdevalias** [comment]
Semi-related:

- https://github.com/missive/emoji-mart/issues/509

**Comment by 0xdevalias** [comment]
@shakesBeardZ Have you read the 'datasets' section of the README that talks about how to include only a certain set of emoji by using `NimblePicker`?

- https://github.com/missive/emoji-mart#datasets

> **Datasets**
> While all sets are available by default, you may want to include only a single set data to reduce the size of your bundle.

**Comment by amorriscode** [comment]
@0xdevalias that doesn't seem to actually work. Even if you pick one dataset, `all.json` still gets included.
