### ISSUE TITLE
download sheet locally / backgroundImageFn

### ISSUE THREAD

**Issue by babyrusa** [missive/emoji-mart#413]
Hi guys, is there away I can download a sheet locally (maybe from the same unpckg) and the set the Picker to use the local sheet? I've checked the Readme and see that there is `backgroundImageFn` prop but I'm not sure how to use that proper to set local sheet?

Many thanks

**Comment by EtienneLem** [comment]
Yep, `backgroundImageFn` is the prop you need. All you need to do is return a string of where you local sheet is accessible. It could be, for example:

```js
<Picker
  backgroundImageFn={(set, sheetSize) => {
    return '/assets/sheet.png'
  }}
/>
```

**Comment by VictorYeung0725** [comment]
> Yep, `backgroundImageFn` is the prop you need. All you need to do is return a string of where you local sheet is accessible. It could be, for example:
> 
> ```js
> <Picker
>   backgroundImageFn={(set, sheetSize) => {
>     return '/assets/sheet.png'
>   }}
> />
> ```

does this Props still exsit 
i did not found this inside the Read.md 
if not ? is there any others ways to use local image to limited the network request
