### ISSUE TITLE
Anchors stretching through all categories

### ISSUE THREAD

**Issue by yjlo** [missive/emoji-mart#414]
<img width="352" alt="Screen Shot 2020-02-21 at 5 46 56 PM" src="https://user-images.githubusercontent.com/34595328/75084056-54c0ac80-54d2-11ea-9bd7-fe4d0da70bac.png">
How come the anchors of the non-selected categories are also purple?

**Comment by rwhitmire** [comment]
If you're using bootstrap, it has a `button { overflow: visible }` rule. You can work around the issue by adding your own rule: `.emoji-mart-bar button { overflow: hidden; }`

**Comment by EtienneLem** [comment]
This should not be an issue anymore in latest version.
