### ISSUE TITLE
DomException using outside of React

### ISSUE THREAD

**Issue by sparmar-atheer** [missive/emoji-mart#415]
I'm using outside of React in Angularjs. Everything works fine. The issue is...when I launch emoji picker multiple times..i get this error.

`emoji.js:1 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "emoji-picker" has already been used with this registry
    at Object.defineElement (https://demo.atheer.my:3000/third-party/emoji/emoji.js:1:596996)
`

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
