### ISSUE TITLE
Some native emoji renders with another char

### ISSUE THREAD

**Issue by Bilb** [missive/emoji-mart#418]
I'm using your picker in a electron app and I have a weird issue with some emoji.
For example for the :woman-playing-handball: just pasting the emoji.native to my textarea, I get:
![emoji issue](https://user-images.githubusercontent.com/1544279/76039544-dd464f00-5fa0-11ea-92f9-0dc7b5eeea41.png)

But when the native emoji is displayed in the message view it is rendered correctly. 
![correct once sent](https://user-images.githubusercontent.com/1544279/76039678-3ca45f00-5fa1-11ea-8301-078541685973.png)

Do you have any idea where this can come from?

**Comment by StevenFrostwick** [comment]
Hey @Bilb 

Did you figure this out?

**Comment by EtienneLem** [comment]
I recently found that some native emojis aren’t displayed properly with `<button>`  on Chrome. Latest version (v3.0.0) introduced a `useButton` props to be able to disable usage of buttons. That might help solve your issue.

**Comment by Bilb** [comment]
> Hey @Bilb
> 
> Did you figure this out?

not yet

**Comment by jasongrishkoff** [comment]
Tried v3.0.0 with `useButton={false}` and the issue persists.

**Comment by scottwarren** [comment]
See #418 there are some options for fixing this
