### ISSUE TITLE
Refused to load emojis. BUG in production.

### ISSUE THREAD

**Issue by justice-art** [missive/emoji-mart#420]
Hello there! Do you have any idea why this happened ?

Devtools console: **Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' <URL> data: blob:".**

![load_emojises_is_failed](https://user-images.githubusercontent.com/20576092/78988574-fa3ee680-7b39-11ea-8e4a-60d9a7bf89ce.png)

Version app: 3.0.0

**Comment by EtienneLem** [comment]
This is not a bug. Your website CSP is blocking the library from loading the emoji sheet. You should either host the spreadsheet or allow the `https://unpkg.com` in your `img-src` directive.
