### ISSUE TITLE
can't delete emoji on initial backspace key click in content editable div

### ISSUE THREAD

**Issue by hari457627** [missive/emoji-mart#421]
I have integrated emoji mart in content editable div. on deleting emoji its not triggering onChange function of that content editable. First click of backspace key not deleting emoji, for second click its deleting and onChange function is calling. why its not happening on initial click?

Can anyone help me with this issue?

**Comment by EtienneLem** [comment]
> on deleting emoji its not triggering onChange function of that content editable

As far as I know the `change` event is not an event for contenteditable elements. It’s only for inputs. The `input` event however should work, maybe that can work for your use case.

> First click of backspace key not deleting emoji, for second click its deleting and onChange function is calling. why its not happening on initial click?

Hard to tell, sounds like an issue with your application.

Note that none of these is related to EmojiMart itself, you would probably find your answers on StackOverflow

**Comment by hari457627** [comment]
I have used react content editable npm package
npm url : https://www.npmjs.com/package/react-contenteditable,
github url : https://github.com/lovasoa/react-contenteditable

for this package onChange function is provided.
i have tried in all aspects. but still i'm getting the issue...
