### ISSUE TITLE
Invariant Violation: Target container is not a DOM element. bundle.js:504:15

### ISSUE THREAD

**Issue by EsoGenics** [missive/emoji-mart#423]
I have the css in the head and I have the bundle at the body of the page. I am using jQuery as well.

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.

**Comment by EsoGenics** [comment]
Well, that is a very horrible way of addressing an issue. ESP. something that is 2 years old.
