### ISSUE TITLE
Hover on preview seems wrong with native icons

### ISSUE THREAD

**Issue by luanraithz** [missive/emoji-mart#425]
Any other set seems to look fine.
![image](https://user-images.githubusercontent.com/27583162/81210127-d12e3c00-8fa7-11ea-86c7-37cd0eaf5705.png)

Easy to reproduce in the [project's website](https://missive.github.io/emoji-mart/).

**Comment by lordono** [comment]
I also faced the same issue. I just tried to fix it with basic CSS for now.

I'm using emojiSize={20}

Then I added these CSS. It will make the button become flex (default to flex-start) and the key is to make sure the width/height is about 2x of emojiSize. (if you want to change the size in real-time, you can use CSS-in-JS to enable it - but in my case, i don't need to.)

.emoji-mart-emoji-native {
    width: 39px;
    height: 39px;
    display: flex;
  }

**Comment by luanraithz** [comment]
Thanks for your comment @lordono!
I did something similar as a fix, but I thought it is good to warn anyone using this nice library that this action was necessary.
I just may ask to cover your code with the css highlight so it calls the attention of anyone who tries to read this issue 😄.
