### ISSUE TITLE
Way to disable Anchors

### ISSUE THREAD

**Issue by RosenTomov** [missive/emoji-mart#427]
Hello, is it possible to disable the Anchors?

I'm trying to run this in an ASP.NET WebForm app, but the Anchors elements seems to be conflicting with the lifecycle events. 

Attaching the script in Page_Init works, but  Page_Load fails.

`Sys.ParameterCountException: Sys.ParameterCountException: Parameter count mismatch. ScriptResource.axd:22:15`

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
