### ISSUE TITLE
Search results fail to render custom emojis using a sprite sheet

### ISSUE THREAD

**Issue by rishisv** [missive/emoji-mart#428]
I am using custom emojis with emoji-mart (v2.10.0 but looks like issue/fix applies to master too). In search results, I see the emoji render is not using the custom emoji attributes right and isn't using the spriteUrl, sheet_x and sheet_y attributes. Please see the screenshot below, the custom emoji renders right in preview pane but not in search results, the css style does not have the right background-size and background-position property.

Fix appears to be to update sanitize() function to return the spriteUrl, sheet_x and sheet_y data attributes when the emoji is custom. Diff here for context below, happy to share a PR too if the fix looks right.

Thank you!

```
diff --git a/src/utils/index.js b/src/utils/index.js
index 8b230fb..6b71204 100644
--- a/src/utils/index.js
+++ b/src/utils/index.js
@@ -23,6 +23,9 @@ function sanitize(emoji) {
       custom,
       customCategory,
       imageUrl,
+      spriteUrl,
+      sheet_x,
+      sheet_y,
     } = emoji,
     id = emoji.id || short_names[0],
     colons = `:${id}:`
@@ -37,6 +40,9 @@ function sanitize(emoji) {
       custom,
       customCategory,
       imageUrl,
+      spriteUrl,
+      sheet_x,
+      sheet_y,
     }
   }
```

<img width="474" alt="Screenshot 2020-05-19 at 10 36 34 PM" src="https://user-images.githubusercontent.com/59505526/82357239-6f97b400-9a22-11ea-9695-2ea7572cd6d8.png">

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
