### ISSUE TITLE
Allow getEmojiDataFromNative work with emoji without variation selector

### ISSUE THREAD

**Issue by ra3orblade** [missive/emoji-mart#429]
When you pick emoji with picker from Apple MacOS for example and pick emoji that can work without variation selector (FE0F) getEmojiDataFromNative returns null.

Possible solution: 

 `for (var id in data.emojis) {
    var emoji = data.emojis[id];
    var emojiUnified = emoji.unified;
    var emojiNonQualified = emoji.non_qualified;

    if (emoji.variations && emoji.variations.length) {
      emojiUnified = emoji.variations.shift();
    }

    if (skin && emoji.skin_variations && emoji.skin_variations[skinCode]) {
      emojiUnified = emoji.skin_variations[skinCode].unified;
    }

    if (unifiedToNative(emojiUnified) === baseNativeString || (emojiNonQualified && unifiedToNative(emojiNonQualified) === baseNativeString)) {
      emojiData = emoji;
    }
  }`

**Comment by m-andrew-albright** [comment]
Same for Windows, if you use the [windows key]+. emoji selector and choose ☠ `getEmojiDataFromNative` fails to find the emoji data for the native string since it doesn't contain the `65039` character.

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case. While `getEmojiDataFromNative` is not used anymore, you can `await EmojiMart.SearchIndex.search('☠')` to find emoji data from a native emoji.
