### ISSUE TITLE
Add the feature to autocomplete on text edit components.

### ISSUE THREAD

**Issue by lucasoares** [missive/emoji-mart#432]
Hello.

Do you guys have something like this: https://github.com/yuku/textcomplete on the roadmap?

Would be great!

Thanks.

**Comment by Seoudi** [comment]
@lucasoares  you can achieve this with regex check this article 

https://medium.com/@aly.essam.seoudi/simple-react-guide-to-implement-chat-comment-input-component-react-mentions-emoji-mart-a48a4d8c4fad
