### ISSUE TITLE
Some Emojis are rendered incorrrectly

### ISSUE THREAD

**Issue by antrant** [missive/emoji-mart#434]
I open Emoji Mart in iOS 11 - Safari and it was rendered as the image below:
![1591937809505](https://user-images.githubusercontent.com/20618729/84472457-63191b00-acb1-11ea-8836-c62afe3c1a29.jpg)

Here is my component:
```
<EmojiPicker
        showPreview={false}
        showSkinTones={false}
        native={true}
 />
```

Open [https://missive.github.io/emoji-mart](https://missive.github.io/emoji-mart/) (on the same device) will show the same result.

How to resolve this?

**Comment by EtienneLem** [comment]
These emojis are recent and not supported by your iOS version. The only bulletproof way is not to set `native={true}`
