### ISSUE TITLE
Some person emoji do not exist when there is a male and/or female version on Windows 10

### ISSUE THREAD

**Issue by seahorsepip** [missive/emoji-mart#443]
Some emoji do not exist on windows 10.

One example is `pilot`, this emoji does not exist but `male pilot` and `female pilot` do exist.
This seems to be the case for all `person` emoji with male and/or female versions.

Current workaround is filtering all `person` emoji out that have a `male` or `female` version:

```js
emojisToShowFilter={(emoji) => {
  const person = '1F9D1';
  const male = '1F468';
  const female = '1F469';
  const zwj = '200D';
  if (emoji.unified) {
    const prefix = `${person}-${zwj}-`;
    if (!emoji.unified.startsWith(prefix)) {
      return true;
    }
    const suffix = emoji.unified.substring(prefix.length);
    return !!Object
      .values(data)
      .find(({unified}) => unified === `${male}-${zwj}-${suffix}` || unified === `${female}-${zwj}-${suffix}`);
  }
  return true;
}}
```

Maybe this could be added as an option or documented somewhere? I thought I'd share this here for anyone else who runs into this issue.

**Comment by EtienneLem** [comment]
Chances are this is not an issue anymore in latest version. Please reopen an issue if that’s not the case.
