### ISSUE TITLE
Support for relative sizes on the Emoji component

### ISSUE THREAD

**Issue by BrockWills** [missive/emoji-mart#447]
First of all, thank you for this incredible project.

I was hoping to pass a responsive size such as `size="2rem"` to the `<Emoji />` component.

With the current codebase this seems to work perfectly fine because the size is just passed straight through to css, but PropTypes validation fails because it expects a number. What do people think about updating the PropTypes for the Emoji component to instead be:
```
size: PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.number
]).isRequired,
```

That way, all types of css sizes like `px`, `em`, `rem`, etc. would all be supported.

**Comment by vple** [comment]
I'd like this as well and just made a PR.

I messed around with it a bit—this change will support rem as expected, but it doesn't work as intended with em and %. Details below.

The Emoji component renders something like this:

```
<span aria-label="👍, +1, thumbsup" class="emoji-mart-emoji emoji-mart-emoji-native">
  <span style="font-size: 10rem;">👍</span>
</span>
```

The issue for em is that `.emoji-mart-emoji` sets `font-size` to 0. So any em value for the inner span will also be 0. That was introduced [here](https://github.com/missive/emoji-mart/commit/919976e10e9f42187aeb925767910d731ff2252e), but I'm not familiar enough to know if there are good alternate approaches.

The issue for % is that the outer span doesn't have an explicit size, so the inner span gets confused.

**Comment by EtienneLem** [comment]
This is now possible on latest version with the `<em-emoji>` web component. See https://github.com/missive/emoji-mart#-emoji-component
