### ISSUE TITLE
Prefetch emoji sheets

### ISSUE THREAD

**Issue by michaeljguarino** [missive/emoji-mart#450]
I've noticed pretty laggy load times on the first emoji render in my app and was wondering if there's any mechanism to prefetch the sheets we'd like to ensure their in the browsers cache as soon as possible.  Something done at page load would be ideal I believe.

**Comment by sujeetjaiswara** [comment]
Yes, same issue. 
I am facing

**Comment by kozzztya** [comment]
Agree, that prefetch be great. As a dirty solution to prevent lag at the first render, I added the second emoji picker that always on the page but always invisible.

**Comment by kabachook** [comment]
@michaeljguarino if you are using SSR, you can try something like this:
```js
// config.ts
export const emojiSet = "apple";
export const emojiSheetSize = 32;
export const emojiBackgroundImageFn = (set, sheetSize) => "https://unpkg.com/emoji-datasource-".concat(set, "@").concat("5.0.1", "/img/").concat(set, "/sheets-256/").concat(sheetSize, ".png")
export const emojiSheetUrl = emojiBackgroundImageFn(emojiSet, emojiSheetSize);
```

```js
// index.tsx
import { emojiSheetUrl } from "../config";

export default function Home () {
    return  (
          // ....
        <link rel="preload" href={emojiSheetUrl} as="image" />
    )
}
```

If not using SSR, I suggest that you can ether write preload manually in html or use Webpack HTML template plugins to calculate preload url dynamically.
