### ISSUE TITLE
when selecting flag of any country then it is showing country name instead of flag icon

### ISSUE THREAD

**Issue by Chetnatl** [missive/emoji-mart#451]
For some of the country's flags, it is showing the country name. but I want to show the flag image to the user.

See in below image:

![image](https://user-images.githubusercontent.com/61341696/92385464-90019080-f12f-11ea-9b71-fb0402abb672.png)

**Comment by duong120798** [comment]
Have you figured out how to fix this ?

**Comment by Chetnatl** [comment]
@duong120798 no

**Comment by rajeevnathverma** [comment]
Is anyone found solution for it ?

**Comment by EtienneLem** [comment]
If your browser does support these native emojis and they only appear this way in an input, you may need to add these fonts to your inputs:

```
input {
  font-family: "Segoe UI Emoji", "Segoe UI Symbol", "Segoe UI", "Apple Color Emoji", "Twemoji Mozilla", "Noto Color Emoji", "Android Emoji";
}
```

**Comment by Lakshmanan30111995** [comment]
Even I was facing the same issue in chrome browser.But in firefox it was loading correctly. The problem might be that you have to include the file manually in chrome browser. Try this work-around and let me know, which worked for me:

1. Download TwemojiMozilla.ttf file from https://github.com/mozilla/twemoji-colr/releases.
2. Include it in your css component by

@font-face {
  font-family: "TwemojiMozilla";
  src: local("TwemojiMozilla"),
  url("./TwemojiMozilla.ttf") format("truetype");
  font-weight: normal;
}
/* Your Input Div*/
.input {
	font-family: "TwemojiMozilla";
}

3. Hopefully, now it should load.

**Comment by rajeevnathverma143** [comment]
> Even I was facing the same issue in chrome browser.But in firefox it was loading correctly. The problem might be that you have to include the file manually in chrome browser. Try this work-around and let me know, which worked for me:
> 
> 1. Download TwemojiMozilla.ttf file from https://github.com/mozilla/twemoji-colr/releases.
> 2. Include it in JS file by import './TwemojiMozilla.ttf';
> 3. Include it in your css component by
> 
> @font-face {
> font-family: "TwemojiMozilla";
> src: local("TwemojiMozilla"),
> url("./TwemojiMozilla.ttf") format("truetype");
> font-weight: normal;
> }
> /* Your Input Div*/
> .input {
> font-family: "TwemojiMozilla";
> }
> 
> 1. Hopefully, now it should load.

Great Its working, Thanks !

**Comment by rajeevnathverma143** [comment]
Using this font-family flag are now showing but on this input field not showing any numbers like 1 2 3 on chrome .
Please suggest me what need for it.

**Comment by Lakshmanan30111995** [comment]
> Using this font-family flag are now showing but on this input field not showing any numbers like 1 2 3 on chrome .
> Please suggest me what need for it.

Please use this for cross browser support(Chrome, Firefox, Safari) and cross OS support (MAC, Windows)

.input {
        font-family: 'Segoe UI Emoji', 'Segoe UI Symbol', 'Open-Sans', "Apple Color Emoji", "TwemojiMozilla", "Noto Color Emoji", "Android Emoji", sans-serif;
}

This will display characters, emoji's and numbers.

**Comment by ji123mmy** [comment]
> > Using this font-family flag are now showing but on this input field not showing any numbers like 1 2 3 on chrome .
> > Please suggest me what need for it.
> 
> Please use this for cross browser support(Chrome, Firefox, Safari) and cross OS support (MAC, Windows)
> 
> .input {
> font-family: 'Segoe UI Emoji', 'Segoe UI Symbol', 'Open-Sans', "Apple Color Emoji", "TwemojiMozilla", "Noto Color Emoji", "Android Emoji", sans-serif;
> }
> 
> This will display characters, emoji's and numbers.

It didn't work . Is there any other solution?

**Comment by riyazpanarwala** [comment]
Is this issue fixed ?

**Comment by basharatanis** [comment]
Hi, 
I am using latest version (3.0.1) of emoji-mart. 
I have couple of issues in the app right now. 
1. When I select flag of any country then it is showing country name instead of flag icon (ONLY IN WINDOWS)
2. I cannot see some emojis such as thumbsup, thumbsdown, etc. 

Kindly let me know if this issue is fixed or if you have any idea to get this issue fixed. 

Thanks

**Comment by ajaythakkar** [comment]
> Even I was facing the same issue in chrome browser.But in firefox it was loading correctly. The problem might be that you have to include the file manually in chrome browser. Try this work-around and let me know, which worked for me:
> 
> 1. Download TwemojiMozilla.ttf file from https://github.com/mozilla/twemoji-colr/releases.
> 2. Include it in JS file by import './TwemojiMozilla.ttf';
> 3. Include it in your css component by
> 
> @font-face { font-family: "TwemojiMozilla"; src: local("TwemojiMozilla"), url("./TwemojiMozilla.ttf") format("truetype"); font-weight: normal; } /* Your Input Div*/ .input { font-family: "TwemojiMozilla"; }
> 
> 4. Hopefully, now it should load.

This is working but the number was not working so you need to modify it like:

`font-family: Arial,"TwemojiMozilla"`

This will work with emoji and numbers

**Comment by cg-tester** [comment]
@Lakshmanan30111995 ,  I want to implement your solution.
But I am developing Angular project.
How can I add .ttf file and css?
Please let me know.

**Comment by ajaythakkar** [comment]
> @Lakshmanan30111995 , I want to implement your solution. But I am developing Angular project. How can I add .ttf file and css? Please let me know.

I have also worked with angular projects, here are the details:
`/* Emoji Text */
@font-face {
  font-family: "TwemojiMozilla";
  src: local("TwemojiMozilla"),
  url("assets/fonts/TwemojiMozilla.ttf") format("truetype");
  font-weight: normal;
}

textarea,
.emoji_text {
  font-family: "Poppins", "TwemojiMozilla";
}

/* Emoji Text */`

**Comment by cg-tester** [comment]
@Lakshmanan30111995 
Thank you very much.
But please tell me more details.
![image](https://github.com/missive/emoji-mart/assets/137314418/11a55e49-cbb5-42e8-b23c-0accdfd8fdba)
I use emoji-mart in quill-editor and if I click flag emoji, flag emojis should be drawn on quill-editor.

**Comment by cg-tester** [comment]
@ajaythakkar 
Thank you very much.
Please tell me more details.

**Comment by cg-tester** [comment]
Oh, @ajaythakkar , @Lakshmanan30111995 ,  Thank you very much.
It works well. Great!
