### ISSUE TITLE
Theme prop isn't working

### ISSUE THREAD

**Issue by edenavital** [missive/emoji-mart#454]
Hello there,
I tried to add theme prop to the Picker component, but it doesn't work. ('light' / 'dark' as documented) 
Afterwards, I tried to clone the project and debug, and looks like this line isn't exist in the installed version, only in the cloned project:

var theme = this.getPreferredTheme()

So my question is, why it is not published yet, or maybe i'm doing something wrong (I installed latest version)
Thanks :)

**Comment by edenavital** [comment]
Anyone ???

**Comment by EtienneLem** [comment]
> and looks like this line isn't exist in the installed version, only in the cloned project:

Are you sure you have **v3.0.0** installed? Sounds like that might not be the case.

**Comment by edenavital** [comment]
For some reason, it seems to work only after creating a build...
Good enough for me, thanks 👍
