### ISSUE TITLE
emoji-mart picker css not loading on production.

### ISSUE THREAD

**Issue by anasyo10** [missive/emoji-mart#458]
I am having this issue, the emoji picker css isnt being loaded on production. 

![image](https://user-images.githubusercontent.com/19250299/97223333-7278ab00-17f1-11eb-80cf-2ecc6ba07968.png)

**Comment by EtienneLem** [comment]
There can be multiple reasons, but that wouldn’t be an issue with the library. You should first make sure that the CSS is either included and bundled in your CSS or that an external stylesheet is included in your HTML page.
