### ISSUE TITLE
Hide default preview image 🏬

### ISSUE THREAD

**Issue by ahmedrafayat** [missive/emoji-mart#462]
Is there any easy way to hide the default preview emoji (The one that is show with the "title" prop when no emoji is hovered on) ?

I just want that to be hidden. I still want to see the preview image when I hover on an emoji.

![Screenshot 2020-11-07 at 2 06 14 AM](https://user-images.githubusercontent.com/41651149/98410161-56e98c00-209e-11eb-9060-ad6836c2962b.png)

**Comment by EtienneLem** [comment]
An empty string for the `emoji` prop will work, i.e.:

```js
<Picker title='Pick your emoji…' emoji='' />
```
