### ISSUE TITLE
Nimblepicker with native set

### ISSUE THREAD

**Issue by Raghavansk** [missive/emoji-mart#463]
Hi,
I am trying to use NimblePicker with a native set (I wanted to use only NimblePicker but not the picker component as we are exposing the EmojiPikcer as part of some component library , so that others should be able to use different sets). By default NimblePicker would render a native set, even for this case do we need to use all.json? data props seem to be mandatory for nimblePicker

**Comment by EtienneLem** [comment]
This should no longer be an issue in latest version. Please reopen an issue if that’s not the case.
