### ISSUE TITLE
Emoji 

### ISSUE THREAD

**Issue by dexterns88** [missive/emoji-mart#469]
When using emoji set `apple`  and insert `ballot_box_with_ballot` I get emoji with  length of 3 but when insert emoji from macOS emoji panel get this emoji with 2 character. also when moving cursor they move it into middle of emoji.
`
const validEmoji = '🗳' 
const martEmoji = '🗳️'  

validEmoji.length // 2
martEmoji.length // 3
`

If I try to encode this emoji for both get same value '1f5f3'

**Comment by EtienneLem** [comment]
From https://emojipedia.org/ballot-box-with-ballot, when I copy/paste the emoji I get `length == 3`:

<img width="399" alt="Screen Shot 2020-12-15 at 8 25 03 AM" src="https://user-images.githubusercontent.com/436043/102220674-27a11880-3eaf-11eb-924f-282a164e8fce.png">
