### ISSUE TITLE
Prop onOutsideClick

### ISSUE THREAD

**Issue by anaumov** [missive/emoji-mart#47]
Hey, guys! Thanks for nice picker! How about add prop for handle outside click? It would be useful if user want to hide component on outside click.

What do you think?

**Comment by vinnymac** [comment]
@anaumov I vote against including this behavior in this dependency. If someone really needs it, it could be added with one of the many other libraries wrapping this one. I think if anything maybe a note about it in the ReadMe.

https://github.com/Pomax/react-onclickoutside
https://github.com/kentor/react-click-outside
https://github.com/tj/react-click-outside

**Comment by EtienneLem** [comment]
Sorry for being silent on this one, thanks for the links @vinnymac!

I would also prefer not to have to handle that in the lib. What we do in our app is when rendering EmojiMart, we render it in a full-width container that has 2 elements: a veil and the picker. The veil is just a full width/height `<div>` with no background that registers  click events. This also prevents the user from scrolling other elements, clicking on links, etc, etc.

We do that in React, but here’s a quick plain HTML/JS example (click anywhere outside vs. inside): http://codepen.io/EtienneLem/pen/evrbRK

**Comment by anaumov** [comment]
@vinnymac @EtienneLem Thank for your reply! Ok, I got your point. It would be nice to add these links in readme.

**Comment by gtaylor44** [comment]
I wanted the same behaviour (close when click outside). Without having to use a 3rd party lib...

```
componentWillUnmount() {
    document.body.removeEventListener("click", this.emojiMartClickOutsideHandler);
}

emojiMartClickOutsideHandler = (e) => {

    let emojiWindowIsOpen = false;

    if (e.path) {
        e.path.forEach(elem => {             
            if (elem.classList && elem.classList.contains("emoji-mart")) {
                emojiWindowIsOpen = true;
                return;
             }
          });
       }

    if (!emojiWindowIsOpen) {
        this.setState({emojiWindowOpen: false});
        document.body.removeEventListener("click", this.emojiMartClickOutsideHandler);
    }

    toggleEmojiWindow = () => {

        if (this.state.emojiWindowOpen) {
            this.setState({ emojiWindowOpen: false });
        }
        else {
            document.body.addEventListener("click", this.emojiMartClickOutsideHandler);
            this.setState({ emojiWindowOpen: true });
        }
    }
}
```

**Comment by amitpatil321** [comment]
This is how I solved it

```
  onToggleEmojiWindow = () => {
    const { showEmoji } = this.state;
    this.setState({ showEmoji: !showEmoji });
  };

  componentDidMount() {
    document.querySelector(".main-content").addEventListener("click", event => {
      // Get parent element and check if click happened outside parent only
      const parent = document.querySelector(".emoji-mart");
      const { showEmoji } = this.state;
      if (showEmoji && !parent.contains(event.target)) {
        this.onToggleEmojiWindow();
      }
    });
  }
```
