### ISSUE TITLE
Possible to hide    .emoji-mart-preview     section?

### ISSUE THREAD

**Issue by davvit** [missive/emoji-mart#470]
Would be nice to have api exposed for that. its not picking up my css changes.

![image](https://user-images.githubusercontent.com/4433698/103198224-679fcc80-48ad-11eb-8fce-0202837eeb8e.png)

**Comment by mdnmnahmed** [comment]
try this---
**showPreview={false}**

```
<Picker
    showPreview={false}
    showSkinTones={false}
    native={true}
    onSelect={doSomething}
 />
```

**Comment by davvit** [comment]
didnt help

**Comment by dhruvbhatia7** [comment]
This worked for me

`.emoji-mart-preview {
                        display: none;
                    }
`

**Comment by davvit** [comment]
Yep that works! thanks @dhruvbhatia7

**Comment by kisildev-580** [comment]
> try this---
> **showPreview={false}**
> 
> ```
> <Picker
>     showPreview={false}
>     showSkinTones={false}
>     native={true}
>     onSelect={doSomething}
>  />
> ```

it works for me

**Comment by sebastianfast** [comment]
`showSkinTones={false}` did it for me. This is not supposed to work like that, is it?

**Comment by mageshkumar1598** [comment]
Still not working for me? Applied both `showPreview={false}` and `showSkinTones={false}`, but still preview is displayed!! Can anyone help?

**Comment by YannisHofmann** [comment]
+1

**Comment by EtienneLem** [comment]
In latest version, it can be done with `previewPosition : 'none'`
