### ISSUE TITLE
one emoji is not showing properly

### ISSUE THREAD

**Issue by mdnmnahmed** [missive/emoji-mart#471]
this **emoji is not showing** ---

![image](https://user-images.githubusercontent.com/39140801/103451263-908ddc00-4c76-11eb-97f2-b50ee241a89e.png)

please fix it...

**Comment by suarezluis** [comment]
Is that the :relaxed: ( ☺️ ) emoji ?

**Comment by suarezluis** [comment]
Is that the : relaxed : ( ☺️ ) emoji ?

**Comment by mdnmnahmed** [comment]
@suarezluis yeah, right...

**Comment by Clement83** [comment]
We have same issue. Is there a plan to fix it?

**Comment by EtienneLem** [comment]
This is not quite related to the usage of this library. You need to make sure you set the proper `font-family` on your website or input where the emojis are used.

**Comment by suarezluis** [comment]
Changing the font-family solved the issue for me Thanks!

**Comment by Clement83** [comment]
For me too, I fallback my font fammily with `apple color emoji` and all is OK : 
`font-family: Helvetica Neue, apple color emoji, sans-serif;`
