### ISSUE TITLE
Anchors querySelector error in React app

### ISSUE THREAD

**Issue by MatheusPires99** [missive/emoji-mart#472]
I am getting an error when clicking on any anchor in a React app:

![Captura de Tela 2021-01-06 às 14 16 05](https://user-images.githubusercontent.com/49207932/103799337-b8d85a80-5029-11eb-83c0-d0d735f59280.png)

It changes the emoji category before give me the error

**Comment by MatheusPires99** [comment]
I found the error, but don't know how to solve it.

In my application I have a cookies bar for the user to accept, when accepted the anchors starts with this error, if I don't accept no error occurs, does anyone know how what can I do about it?

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
