### ISSUE TITLE
Emoji navigation items can't clicked the first time

### ISSUE THREAD

**Issue by broccoli77** [missive/emoji-mart#473]
The first time the picker component loaded the navigation items couldn't be clicked until I clicked one of the emoticons.
(ps: The picker is in the modal component.)

![表情工具栏点击失效](https://user-images.githubusercontent.com/44807152/103971669-2dd09f00-51a6-11eb-8522-bc9ae48ebdb5.gif)

**Comment by prakashks20** [comment]
I'm also facing the same issue with some specific devices.

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
