### ISSUE TITLE
css-loader v4.0.0 breaking emoji-mart css

### ISSUE THREAD

**Issue by Streeterxs** [missive/emoji-mart#474]
### Overview
Recently after our project updates css-loader to v5.0.0 a bug occured on our emoji-mart picker. After a few debbuging we found that the breaking change occured at v4.0.0 of css-loader package

### Screenshots
after:
![image](https://user-images.githubusercontent.com/41974719/104072863-1536a800-51eb-11eb-8d4d-dff19f62aa44.png)
before:
![image](https://user-images.githubusercontent.com/41974719/104073145-aefe5500-51eb-11eb-98aa-b2775737bcab.png)

**Comment by EtienneLem** [comment]
This is no longer an issue in latest version. Please reopen an issue if that’s not the case.
