### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'custom' of object '#<Object>'

### ISSUE THREAD

**Issue by cabello** [missive/emoji-mart#477]
Hi,

Thank you for this component, it saved me so much time, I wouldn't have implemented something as polished as this component. 🙇 

I am currently using EmojiMart with Typescript.

I was using immer for the state management portion of my app that integrated with EmojiMart, something along the lines:

```typescript
import { Picker } from 'emoji-mart';
import { produce } from 'immer';

 <Picker
    custom={customEmojiList}
    theme='auto'
    title=''
    emoji=''
    onSelect={(emoji) => {
      setReactions((state) =>
        produce(state, (draftState) => {
          draftState[reactionIndex] = emoji;
        })
      );
      setReactionIndex(-1);
    }}
  />
```

And when I started using custom emojis, I've got the following error:

<img width="599" alt="Screen Shot 2021-01-13 at 6 42 21 PM" src="https://user-images.githubusercontent.com/60936/104525843-17c04580-55cf-11eb-8c6f-a286f8c69505.png">

And it's happening because of this line:

https://github.com/missive/emoji-mart/blob/ca3d4e5f0ee6a259bf04d91e540386548163dd6d/src/utils/index.js#L99

For now I just went back to not using immer for this portion of the app:

```typescript
onSelect={(emoji) => {
  setReactions((state) =>
    state.map((item, index) =>
      index !== reactionIndex ? item : emoji
    )
  );
  setReactionIndex(-1);
}}
```

If I were to suggest a solution for this issue, it would be to not change emoji items when getting the data, move `custom: boolean` (id and unified also) to be part of the interface.

Sharing this in case anyone finds similar issue.

Thank you again 💜

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
