### ISSUE TITLE
Add support for custom category anchors.

### ISSUE THREAD

**Issue by MasterEric** [missive/emoji-mart#481]
#224 and #351 allow for multiple custom categories, but only the first will appear as a category anchor, and will appear with a star icon.

As seen here, functionality ensures only the first category will be added, and the rest will be ignored.

https://github.com/missive/emoji-mart/blob/master/src/components/picker/nimble-picker.js#L84

Modify this to add for multiple custom categories, including the ability to specify their icons via the existing `icons` property.

This should also include a prop which enables this functionality, named something like `multipleCustomCategories`, which is false by default. This is to prevent breaking existing implementations.

**Comment by EtienneLem** [comment]
This is supported in latest version. See https://github.com/missive/emoji-mart#custom-emojis
