### ISSUE TITLE
Cannot set custom emoji as idle emoji

### ISSUE THREAD

**Issue by MasterEric** [missive/emoji-mart#483]
When setting the `emoji` prop of a picker to a custom emoji name, the picker does not display any emoji.

The changes likely will need to be made around this line, which is returning null when it can't find the named emoji:

https://github.com/missive/emoji-mart/blob/ca3d4e5f0ee6a259bf04d91e540386548163dd6d/src/utils/index.js#L84

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
