### ISSUE TITLE
Relaxed face emoji looks different

### ISSUE THREAD

**Issue by ashbadami** [missive/emoji-mart#484]
Hi, We are seeing that the relaxed face emoji icon looks different from others. I am new to UI development. our product is using 
version 2.11.1

![image](https://user-images.githubusercontent.com/17021104/107377334-b2615680-6a9f-11eb-9bd9-87220d82c61d.png)

computed styles for relaxed face icon
![image](https://user-images.githubusercontent.com/17021104/107378083-7a0e4800-6aa0-11eb-8851-2696368c4efb.png)

**Comment by mariuszbeltowski** [comment]
Same here, did you fix it?

**Comment by EtienneLem** [comment]
This is fixed in latest version.
