### ISSUE TITLE
Display emoji in textarea

### ISSUE THREAD

**Issue by sites21** [missive/emoji-mart#485]
How can I display emoji in textarea and in a chat? I didn't want to use native emoji. I want a facebook emoji, but when I click on them,  I get in a textarea a native emoji! What can I do with this?

**Comment by afuggini** [comment]
You can't display custom emojis in a textarea other than the native ones, since a textarea only accepts texts, and other emojis are rendered as images. What you can do is try a custom textarea such as https://draftjs.org/ which is not really a <textarea> behind the curtains.

**Comment by sites21** [comment]
> You can't display custom emojis in a textarea other than the native ones, since a textarea only accepts texts, and other emojis are rendered as images. What you can do is try a custom textarea such as https://draftjs.org/ which is not really a <textarea> behind the curtains.

Thank you for this reply!

**Comment by schmoninator** [comment]
Another alternative would be to use native emojis but have them rendered using a custom font. 
I am using joypixels for example: https://demos.joypixels.com/latest/joypixels-web-font.html
