### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by tanderson96** [missive/emoji-mart#487]
Howdy! We recently had an accessibility audit of our web application, which leverages emoji-mart as our emoji picker, and the auditor noted a few things specifically around the emoji picker that I wanted to pass along in case anyone has time to address them (the following are copy-pasted from the auditor's report):

- In the Emoji modal, visual headings (e.g., "Frequently Used", "Smileys & People") should be tagged as headings.

- In the Emoji modal, cannot reach emoji details (e.g., "Grinning Face :grinning:") using the keyboard alone.

- In the Emoji modal, roles and values (i.e., that they are tabs and whether they are selected) are not provided for emoji category tabs and screen reader users are not notified when they are changed.

- In the Emoji modal, screen reader users are not notified when an emoji is selected.

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
