### ISSUE TITLE
Control skin tone emoji size with props instead of hard coding it

### ISSUE THREAD

**Issue by afuggini** [missive/emoji-mart#489]
It would be nice that the font-size for the skin selection emoji is somehow configurable through props instead of hard-coded as `23`.

https://github.com/missive/emoji-mart/blob/ca3d4e5f0ee6a259bf04d91e540386548163dd6d/src/components/skins-emoji.js#L41

**Comment by EtienneLem** [comment]
Chances are this is not an issue anymore in latest version. Please reopen an issue if that’s not the case.
