### ISSUE TITLE
emoji picker slow to render to DOM

### ISSUE THREAD

**Issue by smatt989** [missive/emoji-mart#492]
would be nice to have a virtualized list so that we don't need to wait for the hundreds of emojis to render, which can really slow down the browser.  are there any plans for this (or some other way to speed up the rendering)?

**Comment by andrewckor** [comment]
Good idea, I have the same issue! 
This is a great dependency package that can be used for this one:
https://www.npmjs.com/package/react-virtualized

**Comment by summera** [comment]
We are also experiencing this. Seems a lot worse in Chrome. @EtienneLem any thoughts?

**Comment by sayjeyhi** [comment]
This one is really awful! Making `Picker` render slow! Should do something on this

**Comment by sayjeyhi** [comment]
I fixed it on this PR: https://github.com/missive/emoji-mart/pull/510

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
