### ISSUE TITLE
Insert emoji in the string on particular position (cursor position)

### ISSUE THREAD

**Issue by sachinj23** [missive/emoji-mart#493]
When i try to insert emoji in typed string where the cursor  position but emoji added in last of string. i want add emoji any where of particular string or paragraph at cursor position.

**Comment by mohamadyusuf19** [comment]
I have the same problem

**Comment by touktoug** [comment]
This is propably because you inject emoji like this `'${value} ${emoji}'`, it automatically inject it after value. You can do better.

Check cursor position when you trigger input.

```
const handleClickInput = useCallback(
    e => setCursorPosition(e.target.selectionStart),
    []
  );
```
Then you can add emoji in current index. You can use this function for example

```
const insertAt = (target, newString, pos) => {
  if(typeof(pos) == 'undefined') pos = 0;
  if(typeof(newString) == 'undefined') newString = '';

  return target.slice(0, pos) + newString + target.slice(pos);
};
```

and finaly

```
 const handleChangeEmoji = useCallback(
    emoji => {
      const getValue = insertAt(value, emoji?.native, cursorPosition);
      onChange({ value: getValue });
      // ... do other stuff
    },
    [onChange, value, cursorPosition]
  );
```

**Comment by santhosh1190** [comment]
@touktoug : Thanks for the input to insert emoji in particular position. I tried what you told. But when I insert multiple emojis one by one at particular position, I get the different output. Please refer the image.

![emoji](https://user-images.githubusercontent.com/11721441/120493077-4604bd00-c3d8-11eb-9c82-3cb7ac4e991c.png)

Could you please tell me how to solve this problem?
Thanks in advance.

**Comment by santhosh1190** [comment]
Hi,
I fixed it. It's working fine now.

**Comment by bhuvnesh-dev** [comment]
@santhosh119 What you did to fix the issue you mentioned above? I'm getting the same issue while inserting multiple emojis as a specific position.

**Comment by sebastiansterk** [comment]
@santhosh1190 please share your fix.

**Comment by oinochoe** [comment]
@santhosh1190 please share your fix.
