### ISSUE TITLE
Add option to clear/unset emoji

### ISSUE THREAD

**Issue by holic** [missive/emoji-mart#495]
First off, thanks for Emoji Mart 🙏  Fantastic library!

We have an "optional icon" field in our CMS that allows associating an icon with a piece of content. Once you've set an icon, there's no way to "unset" it. We can certainly build this into our own UI, but thought I'd make a request to add this functionality to Emoji Mart. It would let us keep our own UI for the emoji picker fairly compact by including this in the Emoji Mart popover.

![image](https://user-images.githubusercontent.com/508855/113192048-2522be80-9213-11eb-9335-791bbe707b02.png)

**Comment by EtienneLem** [comment]
Hey, thanks for the kind words 🙌🏼 

I think that’s beyond the the purpose of the lib itself. Here’s how we’re handling the same UX in our app:

![2021-03-31 14 26 08](https://user-images.githubusercontent.com/436043/113192937-632cdc00-922d-11eb-9dcf-207e816a1fc4.gif)

**Comment by Jordan-Templeman** [comment]
A little late to the party, but I had to solve a similar issue. What I did was use a Poppable menu and then wrapped the Picker and a remove button inside of it. I then just had to add some basic styling and it came out pretty well 
![Screen Shot 2023-01-12 at 10 50 01 AM](https://user-images.githubusercontent.com/93560385/212141647-5f8c5dca-3400-49da-9e85-e8bba955b464.png)

**Comment by kamilsk** [comment]
Hi @Jordan-Templeman! We are solving the same issue. Could you please add some details about your solution? It will be great if it will gist or working code snippet (jsfiddle/codesandbox/raw).

**Comment by Jordan-Templeman** [comment]
Here is how I set up the JSX
```
 <OutsideClickHandler onOutsideClick={onClickOutside}>
      <PoppableMenu
        isOpen={isOpen}
        item={
          <>
            <Picker
              data={data}
              onClickOutside={onClickOutside}
              onEmojiSelect={onEmojiSelect}
              perLine={isExtraSmWindow ? 8 : perLine}
              previewEmoji={emojiPresent}
              previewPosition='bottom'
              skinTonePosition='search'
              theme={mode}
            />
            {emojiPresent && (
              <RemoveButton
                buttonType='tertiary'
                id='remove-emoji'
                onClick={removeButtonAction}
                text={t('remove')}
              />
            )}
          </>
        }
        menuStyling={{ zIndex: 101 }}
        modifiers={[
          {
            name: 'flip',
            options: {
              fallbackPlacements: ['right'],
            },
          },
        ]}
        onClick={onClick}
        placement='bottom-start'
        trigger={trigger}
      />
    </OutsideClickHandler>
  );
};
``` 
In order to get the position of the button to sit inside of the picker like that had to add absolute positioning and set the z-index higher than the Poppable menu
```
const RemoveButton = styled(DefaultButton)`
  position: absolute;
  bottom: 1rem;
  right: 1rem};
  z-index: 105; // higher than poppable menu
`;
```
