### ISSUE TITLE
Broken emoji sheets google@6.0.1

### ISSUE THREAD

**Issue by danilkinkin** [missive/emoji-mart#496]
I am trying using new emoji sheets [https://unpkg.com/emoji-datasource-google@6.0.1/img/google/sheets-256/64.png](https://unpkg.com/emoji-datasource-google@6.0.1/img/google/sheets-256/64.png), but it has broken.

![image](https://user-images.githubusercontent.com/10831688/114995401-d5005900-9eae-11eb-8e30-6381e5e988e8.png)

I am change sheets from ```backgroundImageFn={(set, sheetSize) => `https://unpkg.com/emoji-datasource-google@6.0.1/img/${set}/sheets-256/${sheetSize}.png`}```

emoji-datasource-google@5.0.1
![image](https://user-images.githubusercontent.com/10831688/114995860-4d671a00-9eaf-11eb-8676-448579d92ae1.png)

emoji-datasource-google@6.0.1
![image](https://user-images.githubusercontent.com/10831688/114995939-6374da80-9eaf-11eb-8b11-3ab1eacd327b.png)

How do I set these sheets correctly?

**Comment by EtienneLem** [comment]
You can’t use a different version of emoji-data than the one the data was built it (currently is 5.0.1)

**Comment by danilkinkin** [comment]
Are there any plans to update emoji-data to version 6.0.1?
