### ISSUE TITLE
Custom Emoji for content editable

### ISSUE THREAD

**Issue by diego-toro** [missive/emoji-mart#504]
Hello there! I'm working on a chatbox and was wondering if there's a way to access the emojis data? I saw there are utils for it but not exposed. 

My goal is to use the emojis data with an `img` tag, so the emoji is selectable similarly to web WhatsApp,  but the Emoji component generates a `span` with hardcoded styles. It doesn't accept attributes either so I cannot disable the content editable without a wrapper.

<img width="1006" alt="Screen Shot 2021-05-28 at 7 47 41 AM" src="https://user-images.githubusercontent.com/5667514/119986056-062d7800-bf89-11eb-9064-c57ccfc96909.png">

Check what happens with the emoji span after adding it without a wrapper. Sort of takes the focus and hides the content.

<img width="1420" alt="Screen Shot 2021-05-28 at 12 10 31 AM" src="https://user-images.githubusercontent.com/5667514/119933450-c2674e00-bf49-11eb-81b5-cc8eb4c77a5c.png">

Any help? Thanks in advance.

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
