### ISSUE TITLE
emoji-mart search box not showing

### ISSUE THREAD

**Issue by pankaj1305** [missive/emoji-mart#505]
Hi,
I am using emoji-mart library with version "emoji-mart": "^2.9.2" in our react application. emoji functionality working perfectly but search functionality and search box not working.
Also, I have passed all require param as suggested.

 `
!
 import { Picker } from 'emoji-mart';

<Picker
            onSelect={this._selectEmoji}
            backgroundImageFn={() => '../../assets/emojione.png'}
            custom={customEmojis}
            set='apple'
            size={48}
            title='Pick your emoji…' emoji='point_up'
            i18n={{ search: 'Recherche', categories: { search: 'Résultats de recherche', recent: 'Récents' } }} 
          />`
Please suggest.

![Screenshot from 2021-06-04 14-37-47](https://user-images.githubusercontent.com/15360267/120777249-b596bb80-c542-11eb-83ee-714833ecdfc1.png)

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
