### ISSUE TITLE
Import specific set of emojies / import the package through CDN

### ISSUE THREAD

**Issue by MatanYemini** [missive/emoji-mart#509]
Hi!

There is an option to import only a part of the package? 

Let's say only a set of emojies? 

In addition, there is a way to do CDN import of it?

By setting specific set and different sheet size I was not able to reduce the size of my bundle (it still imports the same amount of emojies) 

Using React v17 and Webpack.  

Thanks.

**Comment by MatanYemini** [comment]
Seems like even when you try to load only a specific set of emojies (using the data param) it still loads the "all.json"

**Comment by 0xdevalias** [comment]
Semi-related:

- https://github.com/missive/emoji-mart/issues/412

**Comment by 0xdevalias** [comment]
@MatanYemini Have you read the 'datasets' section of the README that talks about how to include only a certain set of emoji by using `NimblePicker`?

- https://github.com/missive/emoji-mart#datasets

> **Datasets**
> While all sets are available by default, you may want to include only a single set data to reduce the size of your bundle.

**Comment by 0xdevalias** [comment]
@MatanYemini Is this when following the 'datasets' section of the README that talks about how to include only a certain set of emoji by using `NimblePicker`?

- https://github.com/missive/emoji-mart#datasets

> **Datasets**
> While all sets are available by default, you may want to include only a single set data to reduce the size of your bundle.

**Comment by MatanYemini** [comment]
Yeah, I have tried using this option, but (as you can see also from the readme) there is no real difference.

The only option that I see currently is to manually change the dataset JSON to include 10-15 emoji. But before doing it, I prefer to find a "more gentle approach".

**Comment by 0xdevalias** [comment]
Not sure if it will be an option for you, but I just split our bundle so that it lazy loads this component separately to the rest of our bundle:

- https://github.com/sparkletown/sparkle/pull/1721

**Comment by EtienneLem** [comment]
This shouldn’t be an issue anymore in latest version. Please reopen an issue if that’s not the case.
