### ISSUE TITLE
💤  creating issue

### ISSUE THREAD

**Issue by Saurabh7120** [missive/emoji-mart#512]
In my chat app, I used the library and I noticed a very weird issue. The issue is that the 💤 emoji doesn't give a line break after reaching the endpoint while all other emojis do so.

<img width="761" alt="Screen Shot 2021-07-14 at 10 41 23 AM" src="https://user-images.githubusercontent.com/51123071/125564994-dada7e77-17d5-41c1-b968-114efddb6d21.png">

In the image, you can see that the emojis at the top automatically breaks the line after reaching the endpoint of the container but the 💤 emoji doesn't break the line and overflows the container and hides half the content.

Can somebody help me please

**Comment by Saurabh7120** [comment]
is anybody looking into this?

**Comment by EtienneLem** [comment]
Sorry, this issue is not related to the usage of this library.
