### ISSUE TITLE
Many custom categories

### ISSUE THREAD

**Issue by danilkinkin** [missive/emoji-mart#513]
I want to add stickers in my keyboard. And want separate by sticker pack. Now time available one custom category. 

I found a few similar issues https://github.com/missive/emoji-mart/issues/481, https://github.com/missive/emoji-mart/issues/224, but all without answer. 

Any update by this feature?

**Comment by EtienneLem** [comment]
This is possible in the latest version. See https://github.com/missive/emoji-mart#custom-emojis
