### ISSUE TITLE
Category Tabs Are Not Accessible

### ISSUE THREAD

**Issue by michaeldrotar** [missive/emoji-mart#514]
Hey there!

Appreciate that you're keeping accessibility in mind for this product. We hit one issue that doesn't seem to be mentioned yet in the other accessibility bugs.

Steps to Reproduce:
- set `useButton=true` (absolutely necessary for any amount of accessibility to function currently)
- use tab to get focus to reach a category tab, use enter to select it
- continue tabbing down to the emojis..

Expected:
- should be able to tab to the category selected

Actual:
- it always tabs to the very first emoji of the first category, cause the category tabs scroll the window rather than filter

Proposal:
- perhaps have an option that makes the tabs work as a filter and add a default "All" as the first tab

Thanks!

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
