### ISSUE TITLE
Click the category submits the form (type="button" is missing)

### ISSUE THREAD

**Issue by idubinets** [missive/emoji-mart#515]
Hello team,

When I put the emoji-mart into form, click the category submits the form. It happens because category buttons do not have type="button" attribute. Can you fix it?

![image](https://user-images.githubusercontent.com/2304959/127440902-98fcafc8-5fd6-432e-9b61-4e4b64a960e4.png)

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
