### ISSUE TITLE
flag emojis doesn't appear in mac OS and windows at the same time

### ISSUE THREAD

**Issue by mohamahdimp** [missive/emoji-mart#517]
Hi, I am using emoji-mart in an electron application. 
I use this in font-family: 
```
 font-family: Roboto-Regular, TwemojiMozilla -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
    sans-serif;
```
but it doesn't work in windows and when I change the font family to 
```
font-family: -apple-system, Roboto-Regular, BlinkMacSystemFont,
    "Helvetica Neue", sans-serif, TwemojiMozilla;
```
it doesn't work in Mac OS

**Comment by serzhenko** [comment]
Haven't you missed a comma between «TwemojiMozilla» and «-apple-system»?

**Comment by mohamahdimp** [comment]
when I use comma, it doesn't work on mac OS

**Comment by EtienneLem** [comment]
This is fixed in latest version. Windows doesn’t support country flags. EmojiMart now detects when that’s the case and doesn’t display them.
