### ISSUE TITLE
Emoji-Mart flag and skull emoji issue. 

### ISSUE THREAD

**Issue by sudiparyal185** [missive/emoji-mart#521]
I am using `emoji-mart` library and integrating with `draft-js. ` But there is inconsistency when backspace key is pressed specially with 'Flags' and skull emoji's. The pictures of emoji's when backspace key is pressed are attached. It's working fine with most of the emojis but has bug on selective emoji's specially flags. 
![Screen Shot 2021-08-19 at 11 15 28 AM](https://user-images.githubusercontent.com/89212305/130105178-90dc216c-972e-41df-8206-3ff39945c62d.png)
![Screen Shot 2021-08-19 at 11 15 56 AM](https://user-images.githubusercontent.com/89212305/130105184-dbdaf86d-2ec4-4124-81f1-20700da50144.png)
![Screen Shot 2021-08-19 at 11 16 47 AM](https://user-images.githubusercontent.com/89212305/130105185-0f4b2c0b-1a82-4290-8285-02c8a6744aa3.png)
![Screen Shot 2021-08-19 at 11 17 13 AM](https://user-images.githubusercontent.com/89212305/130105187-2afca890-ff5d-4503-afe5-6ba93e393f6f.png)

**Comment by richardtorres314** [comment]
@sudiparyal185 This may be an issue with the emoji set you're using and how that's being rendered. For example,

![draftjs](https://user-images.githubusercontent.com/7980806/134970404-b3c5221d-3013-477a-b099-2516d7c2d3b7.png)

Draft.js renders fine the skull emoji. This is being rendered on macOS. It would render differently if it were rendered natively and on a different operating system.

**Comment by Rashmi-SendinBlue** [comment]
I'm also having the same issue and it happens only when you enter backspace. Emojis are being rendered correctly but behaving differently on clicking delete button. I'm using "apple" set on macos.

**Comment by EtienneLem** [comment]
Browsers are better at handling emojis nowadays. Chances are this is not an issue anymore. If it is, that would be an issue that `draft-js` need to fix.
