### ISSUE TITLE
Performance Optimization!

### ISSUE THREAD

**Issue by ponikar** [missive/emoji-mart#522]
This library is awesome no doubt but I experience a performance issue in my react app. Whenever I toggle the emoji mart component it takes around 25ms to show the emoji component. Which is quite annoying. If anyone is having a solution for this one, Please help me.

If I don't detach Emoji Picker from the component tree and use the display property to hide/show that component, the problem remains the same. The library is also quite big for small projects.  

Thank you!

**Comment by steelbrain** [comment]
Duplicate of https://github.com/missive/emoji-mart/issues/492

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
