### ISSUE TITLE
Emojis faded out, not clickable

### ISSUE THREAD

**Issue by hidayetmm** [missive/emoji-mart#525]
Emojis is not rendering properly.

![image](https://user-images.githubusercontent.com/74297256/132209467-9d5e1fe8-ac25-4c8c-968d-4d1f1eba166d.png)

**Comment by EtienneLem** [comment]
If you inspect you will most likely find styles from your website that does this. You probably have global styles affecting all your `<button>` or something like that. You can validate by visiting https://missive.github.io/emoji-mart
