### ISSUE TITLE
Error loading the emoji

### ISSUE THREAD

**Issue by AServantDev** [missive/emoji-mart#530]
Hi there, the spreadsheet for the emoji won't load, but it's still clickable and I get the following error : Refused to load the image '<URL>' because it violates the following Content Security Policy directive: 
![content](https://user-images.githubusercontent.com/34283027/134174968-ad46d341-67f6-493a-b7a7-dad7cf8218ee.png)
![spreadsheet](https://user-images.githubusercontent.com/34283027/134175001-dc6ad25a-fcda-4518-afea-8f8960bb6171.png)

**Comment by danwid** [comment]
per the docs 
`Sheets are served from unpkg, a global CDN that serves files published to npm.`

Maybe there are issues on accessing the cdn?

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
