### ISSUE TITLE
Missing emoji, not all emoji showing

### ISSUE THREAD

**Issue by zahid-arbisoft** [missive/emoji-mart#535]
Missing emoji, not all emoji showing. I am using set="apple", sheetSize="64".

All emoji for a category are showing in a single line and show up on a horizontal scroll. How can i break them into mutiple lines

<img width="326" alt="Screen Shot 2021-10-18 at 6 43 18 PM" src="https://user-images.githubusercontent.com/31304505/137743540-06a76ccd-4026-4a0a-825a-d273b31b6d15.png">

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
