### ISSUE TITLE
enableFrequentEmojiSort does not instanly sort frequent emojis

### ISSUE THREAD

**Issue by alex-ersbiometrics** [missive/emoji-mart#540]
I've added :enableFrequentEmojiSort="true" as a prop to my emoji picker however the frequently used emojis only update when the component is rerendered (such as when I reload the page).

I can see in the localStorage "emoji-mart.frequently" object that the count of the emoji increases as I click it but it does not update the frequent list until the component is rerendered. Am I doing something wrong?

**Comment by EtienneLem** [comment]
The frequent category only re-renders after unmountin/mounting the component. This is on purpose, so that nothing moves when user clicks on emojis.
