### ISSUE TITLE
Prevent page reload after clearing search value?

### ISSUE THREAD

**Issue by Streamlinelv** [missive/emoji-mart#541]
Hi, I love what you have developed here and it's working great!
However there is a small issue with the Search field and specifically "emoji-mart-search-icon" element.

<img width="296" alt="Screen Shot 2021-10-28 at 15 15 27" src="https://user-images.githubusercontent.com/6198156/139253604-f9786214-4b26-45f8-a17c-ce2dfa307dc2.png">

When something is entered in the search field and I try to use the X (Clear icon) the value is cleared, but the page instantly reloads.

Is there a way to prevent this from happening as this is a bad UX?

Thank you!
Nauris

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
