### ISSUE TITLE
 Emojis are Light in Color  in windows os

### ISSUE THREAD

**Issue by divyP** [missive/emoji-mart#544]
BROWSER /OS: chrome / window
SCREENSHOT / VIDEO:  

[https://www.loom.com/share/e7bda987793344dc989b74a624e2301f](url)
![emojis colorless](https://user-images.githubusercontent.com/80256911/143152677-341baf15-acb7-4cba-a414-ec66a01dd098.png)

**Comment by divyP** [comment]
Is there any update?

**Comment by EtienneLem** [comment]
Make sure you set the right font-family on your website. This is not necessarily related to the usage of this library.
