### ISSUE TITLE
Custom tabs support

### ISSUE THREAD

**Issue by vsobotka** [missive/emoji-mart#547]
Hi, is it possible to have not only custom categories, but also tabs? In our game, there are 200+ resources and buildings, that we want players to easily reference in chat. To do that, it would be best to have custom tabs for Resources and Buildings. Then, we would be able to use custom categories in those tabs for industries like Agriculture and Aerospace.

Also, it would be good to have the possibility to change the tabs order.

**Comment by EtienneLem** [comment]
No sorry, that would be beyond the scope of this library.
