### ISSUE TITLE
Unable to order custom category when customCategory property is set

### ISSUE THREAD

**Issue by vsobotka** [missive/emoji-mart#549]
When I have custom emoji defined with customCategory property like this
```
const resourcesEmoji: CustomEmoji[] = this.props.resources.map(resource => ({
      name: resource.name,
      short_names: ["re-" + resource.db_letter],
      imageUrl: getImage(resource.image),
      customCategory: customCategory,
    }))
```
```
<Picker
        custom={[...resourcesEmoji, ...buildingsEmoji, ...otherEmoji, ...guidesEmoji]}
      />
```

I am not able to use `include` prop to change the position of the `custom` category tab. It fails on
```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at new Anchors (anchors.js:25)
```

Workaround:
Do not use customCategory property for CustomEmoji objects - instead, use the i18n to set category name. Then, it is possible to use include prop with ['custom'] or the specific order you wish.

**Comment by EtienneLem** [comment]
This is possible with latest version, add your [custom categories](https://github.com/missive/emoji-mart#custom-emojis) and define the order of your categories with the [`categories`](https://github.com/missive/emoji-mart#options--props) prop (make sure you include your custom category ids as well)
