### ISSUE TITLE
A couple of suggestions for the search bar

### ISSUE THREAD

**Issue by JustinDrake** [missive/emoji-mart#55]
Emoji mart is awesome. Two suggestions for the search bar:

1. Add a magnifying glass icon, just like Slack

<img width="102" alt="screen shot 2017-04-06 at 22 53 07" src="https://cloud.githubusercontent.com/assets/731743/24777117/d65bd8f8-1b1b-11e7-990d-cf841059d547.png">

2. Add a cross icon when there is text in the search bar, to clear the text.

<img width="174" alt="screen shot 2017-04-06 at 22 54 49" src="https://cloud.githubusercontent.com/assets/731743/24777187/1885bbc2-1b1c-11e7-9fd5-1cf5fea62a6e.png">

**Comment by nolanlawson** [comment]
The input can already be styled using CSS outside of this library. Closing as this issue is a bit old and can be fixed by the user of the library, please reopen as necessary. Thanks!
