### ISSUE TITLE
Cannot insert emoji properly on a caret position

### ISSUE THREAD

**Issue by Yaroslav-Kunytskyy** [missive/emoji-mart#551]
Emoji inserts after caret position if there was emoji before caret and text after it. The more emoji before the caret were used, the bigger offset will be. 
I believe that issue occurs because I'm trying to insert emoji based on `selectionStart` and `selectionEnd`, but it counts length of characters and native emoji takes 2 spaces.

Corresponding code block:
```
const handleAddEmoji = (event) => {
  const stringWithEmoji = 
    input.substring(0, event.currentTarget.selectionStart) + 
    emoji + 
    input.substring(event.currentTarget.selectionEnd);
  setInput(stringWithEmoji);
}
```

**Comment by EtienneLem** [comment]
Sorry, this issue is not caused by the direct usage of this library.
