### ISSUE TITLE
Serving from other source than unpkg.com

### ISSUE THREAD

**Issue by theunreal** [missive/emoji-mart#553]
Due to security concerns, it's not that safe to whitelist all unpkg.com domains from applications, Is there any workaround to load the emojis from somewhere else (e.g locally path?)

Thanks!

**Comment by Tanmayshetty** [comment]
@theunreal Please refer **backgroundImageFn** prop and the following issue
![image](https://user-images.githubusercontent.com/8419309/152655444-d9749eaf-30cc-4ba9-adcc-1ef3149c572e.png)
 
https://github.com/missive/emoji-mart/issues/413#issuecomment-587141570

```
<Picker
  backgroundImageFn={(set, sheetSize) => {
    return '/assets/sheet.png'
  }}
/>
```

**Comment by dpatra** [comment]
`backgroundImageFn` Not working in v5.1.0

**Comment by dpatra** [comment]
It works like the following in v5.1.0

```
import spriteSheet from '../../assets/emoji/14_apple_sheets_256_64.png';

....

<Picker
getSpritesheetURL={() => {
        return spriteSheet;
    }}
/>
```

**Comment by VictorYeung0725** [comment]
> @theunreal Please refer **backgroundImageFn** prop and the following issue ![image](https://user-images.githubusercontent.com/8419309/152655444-d9749eaf-30cc-4ba9-adcc-1ef3149c572e.png)
> 
> [#413 (comment)](https://github.com/missive/emoji-mart/issues/413#issuecomment-587141570)
> 
> ```
> <Picker
>   backgroundImageFn={(set, sheetSize) => {
>     return '/assets/sheet.png'
>   }}
> />
> ```

is this props still avaliable now 2024? 
i did not found this props in the documentation 
but still need to use local image

**Comment by VictorYeung0725** [comment]
> getSpritesheetURL={() => {
>         return spriteSheet;
>     }}

thank you @dpatra 
after apply this it atually did not fetch another network request 
but the picker lost emoji 
resulting no emoji show up in picker 
but still are able to select 

![Screenshot from 2024-04-18 11-00-30](https://github.com/missive/emoji-mart/assets/96713542/d7fb7632-f72d-4c1d-8f8e-e86944cd4784)

did you encounter this issue ?
