### ISSUE TITLE
Some emojis are not displayed correctly

### ISSUE THREAD

**Issue by 11ume** [missive/emoji-mart#554]
I suppose it is a browser or OS support problem, could these emojis be imported so that they work correctly?
![image (1)](https://user-images.githubusercontent.com/11588112/151578282-6b2fd50f-ba94-42fb-b9b4-0c019118cc48.png)

**Comment by EtienneLem** [comment]
In latest version, you need to use `<em-emoji set="apple">` to match the set of your picker and your displayed emojis. See https://github.com/missive/emoji-mart#-emoji-component
