### ISSUE TITLE
Issue with country flag and some emojis are not visible 

### ISSUE THREAD

**Issue by basharatanis** [missive/emoji-mart#559]
<img width="1061" alt="Screen Shot 2022-03-10 at 2 39 02 PM" src="https://user-images.githubusercontent.com/56668352/157766937-7be4f7bd-bc29-4521-a84a-30afff0ab674.png">

Hi, 
I am using latest version (3.0.1) of emoji-mart. 
I have couple of issues in the app right now. 
1. When I select flag of any country then it is showing country name instead of flag icon (ONLY IN WINDOWS)
2. I cannot see some emojis such as thumbsup when I scroll but they show up when I search for them. 

Kindly let me know if this issue is fixed or if you have any idea to get this issue fixed. 

Thanks

**Comment by SheepTester** [comment]
That's an issue with the font you're using for the text field and not the emoji picker itself. Windows' native emoji font does not include countries for political reasons

**Comment by sahil2796** [comment]
So we have any ideal solution regarding the same?
Coz even I am facing the same issue.
