### ISSUE TITLE
More stylish scroll bar

### ISSUE THREAD

**Issue by JustinDrake** [missive/emoji-mart#56]
A few points of comparison between emoji mart and Slack:

<img width="49" alt="screen shot 2017-04-06 at 22 56 06" src="https://cloud.githubusercontent.com/assets/731743/24777236/50ec6f10-1b1c-11e7-85e7-e46d39dd8a42.png">

1. The scrollbar is shown permanently
2. It is styled beautifully
3. It starts below the search box, unlike emoji mart

**Comment by ricking06** [comment]
Well you can use custom scrollbar and put them in picker.js in place of `emoji-mart-scroll`. I did that but im not going to merge it because i have changed a lot of style (basically removed the whole bottom preview functionality)  .

**Comment by ricking06** [comment]
https://www.npmjs.com/package/emoji-go i implemented it here.

**Comment by EtienneLem** [comment]
Thanks for the link @ricking06. I for one would prefer @JustinDrake’s approach of just styling the stylebar rather than adding a dependency.

**Comment by nolanlawson** [comment]
Yes, this can already be done in CSS using custom scrollbars . Closing as this should ideally be handled outside this library.

See:

- https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
