### ISSUE TITLE
Blush emoji not displaying on Chrome

### ISSUE THREAD

**Issue by ali-flairbox** [missive/emoji-mart#561]
Hello 👋 

I've seen there are a few issues out there with some of the emojis not displaying correctly, but haven't found a fix for this one yet.

The blush emoji displays like this on Chrome using the NimblePicker:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/85241160/158790424-86c9b93a-dbd6-464b-9fae-6cca49ac681a.png">

I have tried with/without native prop, with/without useButton prop, different sets, nothing fixes it for chrome.
Any help on this would be much appreciated. 

Thanks!

**Comment by jdgalani** [comment]
+1

**Comment by jdgalani** [comment]
i am too facing this while rendering native emoji, but in picker it is displaying perfectly for me, just when i select and display native emoji it not correct

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.

**Comment by oliverlouis** [comment]
In order to fix this, the emoji needs to be given a font-family of "Apple Color emoji"
