### ISSUE TITLE
There's a way to convert the native emoji to colons or render the Emoji component within a input?

### ISSUE THREAD

**Issue by YagoBiermann** [missive/emoji-mart#564]
I'm making a chat and i want to send emoji with the messages, but i don't want to render the native emoji of the browser, i know that i could send the emoji with colons and extract from the string to render with the emoji component but this is out of consideration because it's very ugly from the user's perspective, and the more emojis you add to the input more ugly it gets, like so: 
![ugly chat](https://user-images.githubusercontent.com/55931376/161107737-092a24dc-0bbb-4e38-82e5-d1cf975fb2eb.png)

What's the best way to send the emoji in the input and render with the emoji component? like this:
![example](https://user-images.githubusercontent.com/55931376/161108478-0ef3daa0-fdfd-4284-bad8-03e617aa1639.png)

I thought about extract the native emoji from the string and look for with **emojiIndex.search()** passing the native emoji, like this: `emojiIndex.search("🙃")` but it doesn't work, maybe this could be a feature in the future...

Any ideas of what should i do in this case?

I'm leaving [a link to sandbox](https://codesandbox.io/s/render-emoji-f5604h?file=/src/App.tsx) with the minimum code to reproduce this problem, feel free to fork and make your changes!

**Comment by EtienneLem** [comment]
It is indeed a feature now: you can search for a native emoji on the latest version with `await EmojiMart.SearchIndex.search('🤞🏼')`
