### ISSUE TITLE
Support React.js v18

### ISSUE THREAD

**Issue by Divlo** [missive/emoji-mart#565]
Hey :wave:,

Now that React.js v18 has been released, it could be cool to support it.

Ref: https://github.com/missive/emoji-mart/blob/ccd591dd5af5ea21455e65b16c233f4876447b80/package.json#L27

**Comment by ludwighen** [comment]
@tony-scio just tested it in my relatively fresh v18 project and same issue, page crashes when picker is opened. Would love to see react v18 support on this :)

**Comment by GavinThomas1192** [comment]
Same

**Comment by cslecours** [comment]
@tony-scio , @ludwighen, @GavinThomas1192 Are you sure it's related to React 18, and not a browser issue? We're still on React 17 and we experience some freezing/lagging too.

**Comment by GavinThomas1192** [comment]
> @tony-scio , @ludwighen, @GavinThomas1192 Are you sure it's related to React 18, and not a browser issue? We're still on React 17 and we experience some freezing/lagging too.

We are using CRA, "react-scripts": "4.0.3", and " "react": "17.0.2". No freezing/lagging, however we are only using about 45 of the total emoji's. You might reduce the list down to see if that's your issue.

**Comment by Divlo** [comment]
I think it would be best to have a core maintainer or someone who knows better this codebase to open a PR to add support for React.js v18.

I closed my PR, as I don't think it is only an easy peerDeps change, but maybe there is also some code change to add support for it.
Feel free to open another PR yourself with true React.js v18 support and maybe with automated tests too.

**Comment by EtienneLem** [comment]
Good news! [v5.0.0](https://github.com/missive/emoji-mart/discussions/573) has been released and EmojiMart doesn’t depend on React at all anymore. It can still be very easily integrated into a React project ([see example](https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart-website/example-react.html)).

Apologies in advance for the lack of documentation. There are some breaking changes, but depending on your usage it shouldn’t be too different than before.
