### ISSUE TITLE
Anchors scrolling to wrong position when component is in a MUI popover

### ISSUE THREAD

**Issue by jontewks** [missive/emoji-mart#567]
I've got the Picker component inside of a mui popover so it is positioned the way I'd like and automatically closes on click away and stops other scrolling. The anchors up top for the various categories don't scroll to the correct places though. I'm assuming this is because of how mui is rendering the component inside the modal its using but I can't figure out how to remedy the issue. Have you dealt with something like this before?

I noticed going to the correct category and calling `scrollIntoView` works, and had found this issue where that solution was mentioned but it didn't seem to be how its actually scrolling at the moment. https://github.com/missive/emoji-mart/issues/246

Even just a prop that we can utilize like `onCategorySelect` or similar would make it available for me to fix since doing it in a popover is the root cause, but I also think this wouldn't be that uncommon of a use case. 

Thanks very much!

Happy to set up a minimum use case for an example within the popover if you'd like.

https://user-images.githubusercontent.com/3970573/161845979-56f3b0cb-7d56-4dc1-8f8d-9a4117c30155.mp4

**Comment by EtienneLem** [comment]
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.
