### ISSUE TITLE
Label for skin tone selector

### ISSUE THREAD

**Issue by Lexpeee** [missive/emoji-mart#574]
Hello. Could there be a possible way for me to add like a label for the skin tone selector? Just wanted to add a label for accessibility purposes, and I want the users to know that this is a skin tone picker before clicking. Can be a tooltip or a small label or something. It's currently set to the title though. 

![image](https://user-images.githubusercontent.com/30643024/165400504-ce776f94-c105-4bfe-8215-6803c40136ae.png)

**Comment by EtienneLem** [comment]
Latest version includes an accessibility label for this button.
