### ISSUE TITLE
[Version 5] - Nextjs SSG/SSR not working due usage of window

### ISSUE THREAD

**Issue by omridevk** [missive/emoji-mart#575]
Window is undefined
emoji-mart/dist/index.js (1102:56)

**Comment by omridevk** [comment]
https://github.com/missive/emoji-mart/blob/5d04680c0503410752256ed1f744166ac48ee219/packages/emoji-mart/src/helpers/store.js

**Comment by omridevk** [comment]
can we disable localStorage?

**Comment by omridevk** [comment]
Thank you, I would suggest if possible, until then, update v3 to support React v18

**Comment by omridevk** [comment]
I also can't fix it by using useEffect as the usual solution for stuff like that.

**Comment by Leandro096** [comment]
I am having the same exact issue.
![Snapshot](https://user-images.githubusercontent.com/67251206/165541643-1dd18264-61c4-4343-b233-58a03997acef.jpeg)

**Comment by EtienneLem** [comment]
Okay, that’s indeed as I thought. You need to defer the loading of the script so that it’s only loaded on the client side (and not the server). You can read more about that here: https://dev.to/swyx/how-to-use-web-components-with-next-js-and-typescript-4gg1

Here’s an example of how to import and use the lib with Next.js:

```js
import { useEffect, useRef } from 'react'
import data from '@emoji-mart/data'

function Picker(props = {}) {
  const ref = useRef()

  useEffect(() => {
    import('emoji-mart').then((EmojiMart) => {
      new EmojiMart.Picker({ ...props, data, ref })
    })
  }, [])

  return <div ref={ref}></div>
}
```

**Comment by maltesa** [comment]
Thank you for the solution. It is a bit hard to find though. Maybe it would be worth mentioning it in the readme. I guess many people are using frameworks like nextjs that come with ssr out of the box.

**Comment by mfer-mickey** [comment]
> 

i think so

**Comment by gabek** [comment]
With the above solution I'm receiving the error:
```
TypeError: Cannot read properties of undefined (reading 'version')
```
Does anybody have any ideas why I might be seeing that?

**Comment by amanzrx4** [comment]
> Okay, that’s indeed as I thought. You need to defer the loading of the script so that it’s only loaded on the client side (and not the server). You can read more about that here: https://dev.to/swyx/how-to-use-web-components-with-next-js-and-typescript-4gg1
> 
> Here’s an example of how to import and use the lib with Next.js:
> 
> ```js
> import { useEffect, useRef } from 'react'
> import data from '@emoji-mart/data'
> 
> function Picker(props = {}) {
>   const ref = useRef()
> 
>   useEffect(() => {
>     import('emoji-mart').then((EmojiMart) => {
>       new EmojiMart.Picker({ ...props, data, ref })
>     })
>   }, [])
> 
>   return <div ref={ref}></div>
> }
> ```

hi, i tried this i rendered <Picker/> inside my <feed/> component but it's rendered twice and again and again if the the controlled input in <feed/> changes.

**Comment by everdrone** [comment]
Same problem as @amanzrx4

**Comment by gabek** [comment]
This is all disappointing, as I haven't been able to get it working either.  If anybody has any suggestions on an Emoji picker component that supports custom emoji and works out of the box with React+Next please share your suggestions!

**Comment by austinbuckler** [comment]
was able to resolve this using dynamic imports and instantiating the Picker constructor in a ref callback function.

putting the picker in `useEffect` will trigger the effect twice in development mode when react strict-mode is enabled.

```javascript
function EmojiPicker() {
    const pickerRef = useRef()
    const handleDivRef = (divEl) => {
        pickerRef.current = divEl
        import('emoji-mart').then(m => new m.Picker({ ref: pickerRef, data: emojiData }))
    }

    return <div ref={handleDivRef} />
}
```

@gabek @everdrone

**Comment by arclogos132** [comment]
Any update on this?

**Comment by thienna** [comment]
any update?

**Comment by aamancio** [comment]
Another possible solution is doing this.

```tsx
import { useEffect, useRef } from "react";
import data from "@emoji-mart/data";

export const EmojiPicker = (props: any) => {
  const ref = useRef<any>();
  const showEmojis = useRef(true);

  useEffect(() => {
    if (showEmojis.current) {
      showEmojis.current = false;
      import("emoji-mart").then((EmojiMart) => {
        new EmojiMart.Picker({ ...props, data, ref });
      });
    }
  }, [props]);

  return <div ref={ref}></div>;
};

```

**Comment by aamancio** [comment]
> 

Why not put the whole code

**Comment by aamancio** [comment]
One of the things to be aware it seems that non of the methods is respecting the styles.

**Comment by thiagosullivan** [comment]
> Another possible solution is doing this.
> 
> ```tsx
> import { useEffect, useRef } from "react";
> import data from "@emoji-mart/data";
> 
> export const EmojiPicker = (props: any) => {
>   const ref = useRef<any>();
>   const showEmojis = useRef(true);
> 
>   useEffect(() => {
>     if (showEmojis.current) {
>       showEmojis.current = false;
>       import("emoji-mart").then((EmojiMart) => {
>         new EmojiMart.Picker({ ...props, data, ref });
>       });
>     }
>   }, [props]);
> 
>   return <div ref={ref}></div>;
> };
> ```

Thank for this solution! Works perfectly on my case!
