### ISSUE TITLE
Autofocus broken in Firefox in 5.0 release

### ISSUE THREAD

**Issue by dfalling** [missive/emoji-mart#577]
This is reproducible on the [example page](https://missiveapp.com/open/emoji-mart). Toggle autoFocus to `True` in Firefox and note that the field isn't focused after page refresh. This worked in 3.0.1 for Safari, Firefox and Chrome, and the current implementation works fine in Safari and Chrome.

I'm not sure why this doesn't work in Firefox. The same simple HTML `<input type="search" autofocus="true" placeholder="Search">` works fine normally in Firefox.

**Comment by stefansundin** [comment]
This problem also exists in Chrome in certain cases, e.g. if you show the picker conditionally. I think it is this issue: https://stackoverflow.com/a/65056221/2730380.

It would be interesting to try a `useEffect` hook that calls `focus()` on the input field manually. Perhaps it can also check if the picker is attached to the DOM with [Node.isConnected](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected) to see if it is attached to the DOM.
