### ISSUE TITLE
V5 - SearchIndex.search is stuck on pending upon search.

### ISSUE THREAD

**Issue by omridevk** [missive/emoji-mart#579]
SearchIndex is stuck on pending in v5

**Comment by EtienneLem** [comment]
Dats most likely hasn't been initiated, is that possible?

See example in packages/emoji-mart-website/example-headless-search.html

**Comment by omridevk** [comment]
thank you, great library

**Comment by omridevk** [comment]
Works. but a bit ugly I have to admit.

**Comment by zurita-dev** [comment]
I spent two days trying to get the search to work haha, thanks!
