### ISSUE TITLE
[React] V5 - Saving config globally causes problems with multiple instances

### ISSUE THREAD

**Issue by datsteves** [missive/emoji-mart#580]
due to how the config is handled, you can't create multiple instances in one session with different props. 
It is especially relevant for react ecosystems as you create multiple instances often as you won't mount the picker at all times with the same props.

i know for sure for this line that if you do `new Picker({ theme: "light", ... })` and `new Picker({ theme: "dark", ... })` that `pickerProps.theme` will in both cases result in `light`
https://github.com/missive/emoji-mart/blob/5d04680c0503410752256ed1f744166ac48ee219/packages/emoji-mart/src/components/Picker/PickerElement.js#L13

The usecase where i do have the issue is when you have for example a mechanism that the user can toggle between light and dark mode. That change between darkmode and lightmode won't happen anymore without a reload. 

a minimal example to test it with:
```tsx
import data from '@emoji-mart/data';
import { Picker } from 'emoji-mart';
import React from 'react';

function EmojiPicker(props) {
  const ref = React.useRef();
  React.useEffect(() => {
    new Picker({ ...props, data, ref });
  }, []);
  return <div ref={ref} />;
}

const TestCompnent = () => {
  const [theme, setTheme] = React.useState('dark');
  return (
    <React.Fragment>
      <button
        onClick={() => {
          setTheme(theme === 'light' ? 'dark' : 'light');
        }}
      >
        Toggle
      </button>
      <EmojiPicker
        onEmojiSelect={() => {}}
        theme={theme}
        native
        emojiSize={25}
        sheetSize={32}
        data={data}
      />
    </React.Fragment>
  );
};

export default TestCompnent;
```

for now i will use the prev. version :)

**Comment by Clebal** [comment]
@EtienneLem are you working on it or might I help?
Idk if it's as simple as doing:

PickerElement.js
```ts
    const props = {
      ...pickerProps,
      ...getProps(this.props, this),
      element: this,
```
