### ISSUE TITLE
PickerProps does not contain "data" argument

### ISSUE THREAD

**Issue by ppascualv** [missive/emoji-mart#581]
Typescript raises this error using the example code from the readme

TS2345: Argument of type '{ data: { categories: { id: string; emojis: string[]; }[]; emojis: { &quot;100&quot;: { id: string; name: string; keywords: string[]; skins: { unified: string; native: string; }[]; version: number; }; &quot;1234&quot;: { id: string; name: string; keywords: string[]; skins: { ...; }[]; version: number; }; ... 1846 more ...; &quot;flag-wales&quot;...' is not assignable to parameter of type 'PickerProps | Readonly&lt;PickerProps&gt;'.<br/>Object literal may only specify known properties, and 'data' does not exist in type 'PickerProps | Readonly&lt;PickerProps&gt;'.

I'm using version 5.0.0

**Comment by samyilias** [comment]
Saw that as well , are you using https://www.npmjs.com/package/@types/emoji-mart . it's probably because this package was not updated to support the latest changes on v5

**Comment by EtienneLem** [comment]
Proper typescript support will indeed be tracked in #576, thanks for your feedback!
