### ISSUE TITLE
Support for react-scripts@4.0.3

### ISSUE THREAD

**Issue by MMajeed** [missive/emoji-mart#582]
The recent release of v5.0.0 doesn't seem to work with react-scripts@4.0.3. 

Here is the error I get when I try to add `emoji-mart` to a brand new react app that is built against react-scripts@4.0.3

```
./node_modules/emoji-mart/dist/index.js 1906:21
Module parse failed: Unexpected token (1906:21)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js  
You may need an additional loader to handle the result of these loaders.
|   }
|
>   handleClickOutside = e => {
|     const {
|       element: element
```

These are the dependencies I have in my project

```
  "dependencies": {
    "@emoji-mart/data": "^1.0.1",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.1.1",
    "@testing-library/user-event": "^13.5.0",
    "emoji-mart": "^5.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^2.1.4"
  },
```

When I upgrade my project to use `react-scripts@5.0.1`, then everything works fine. It's kind of difficult for us to upgrade our react-scripts on our main project at the moment so I was hoping there was a solution where I didn't have to do the upgrade but still use your library.

**Comment by MMajeed** [comment]
Temp solution that we managed to find to get it working. 

1. Update your babel to the latest version 
```
  "devDependencies": {
    "@babel/cli": "^7.17.10",
    "@babel/core": "^7.17.10",
    "@babel/preset-env": "^7.17.10"
  }
```
2. Under your browerslist, update to this
```
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      ">0.2%",
      "not dead",
      "not op_mini all"
    ]
  },
```

It's not an ideal solution but it did allow the library to work

**Comment by srmagura** [comment]
The code in the emoji-mart bundle that is triggering this is the `async` and `await` keywords.

emoji-mart is transpiling & bundling their code using Parcel which does not have an easy way to set the ES spec targeted by the compilation... so I don't know how to fix this.

**Comment by EtienneLem** [comment]
The library does use modern web APIs and doesn’t target older browsers on purpose. [Async functions](https://caniuse.com/async-functions) are considered stable, you would need to include a polyfill in your app if you need to support older browsers.

Or — I’m not quite familiar with react-scripts — you could try to transpile with babel when loading the library into your codebase.
