### ISSUE TITLE
Hosting the spritesheet locally

### ISSUE THREAD

**Issue by merfed** [missive/emoji-mart#585]
Since it seems that the cdn spritesheet is set when setting the backgroundImage property, it doesn't seem there's a way to host the spritesheet locally.

https://github.com/missive/emoji-mart/blob/5d04680c0503410752256ed1f744166ac48ee219/packages/emoji-mart/src/components/Emoji/Emoji.js#L59

Is there a way to do this, if not can it be added?

**Comment by EtienneLem** [comment]
Indeed, that’s an oversight. Will be supported in the next release.
