### ISSUE TITLE
If a frequently used custom emoji is removed, it will remain in the frequently used

### ISSUE THREAD

**Issue by merfed** [missive/emoji-mart#586]
I'm loading custom emoji into the picker, and having done some tests, I've removed a few. From this point you get a bunch of `emoji is undefined` errors because the removed emoji is still present in the emoji list for the frequent category.

Unsure at the moment as to a work around for this, other than if the emoji isn't currently present in the emoji list or is undefined, ignore it in the frequent list.

Did some more research into this, it _does_ look like at one point this was a feature in a previous version with this pull request: #133.

A quick glance at the code makes me think this might fix it:

```
Picker.js
renderEmojiButton() {
    if (emoji === undefined) {
      return null
    }

    ....
}
```

And

```
config.js after while loop starts

while (i--) {
    ...

    if (emoji === undefined) {
      continue
    }

    ...
}
```

But, at first glance it might not fix the ordering of the frequently used list, and merely omit emojis that cannot be found, leaving you with uneven groupings in the middle.

**Comment by EtienneLem** [comment]
Hey @gregsadetsky 🙃

Right, I see. Thanks for the reproducible steps, will be fixed in the next version.

**Comment by alixcui-glean** [comment]
What if I do not the user to add a custom emoji themselves? Is there still a way I can supply a few custom emojis? Does v5 still support something like the `custom` prop to the Picker?

**Comment by gregsadetsky** [comment]
Cheers! Extremely small ping to remind you to update https://missiveapp.com/open/emoji-mart/ but otherwise nothing to say except one big thanks! :-)
