### ISSUE TITLE
How to remove the search box

### ISSUE THREAD

**Issue by sandywk** [missive/emoji-mart#587]
How to view detailed documents

I need to remove the search box. Which parameter should I use

`    const picker = new EmojiMart.Picker({ 
      data, 
      onEmojiSelect: addFunc,
      previewPosition: 'none',
      icons: 'solid',
      stickySearch: false
    })
    document.querySelector(id).appendChild(picker)`

**Comment by moxccc** [comment]
加一个这个参数 searchPosition:"none",
