### ISSUE TITLE
How to reset Picker

### ISSUE THREAD

**Issue by staniel359** [missive/emoji-mart#588]
Hello.
I need to dynamically pass options to `new Picker()`, e.g. `locale` or `theme`.
So on options change I need `Picker` to render with new options.
How can I reset/reinitialize it?
Thanks.

**Comment by robaweb** [comment]
I have resolved it by some code fixes in https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart/src/components/Picker/PickerElement.js

```
const {
      onEmojiSelect,
      onClickOutside,
      onAddCustomEmoji,
      getImageURL,
      getSpritesheetURL,
      theme, // added
      set,  // added
      native,  // added
      i18n,  // added
    } = this.props

    const props = {
      ...pickerProps,
      element: this,
      onEmojiSelect,
      onClickOutside,
      onAddCustomEmoji,
      getImageURL,
      getSpritesheetURL,
      theme, // added
      set, // added
      native, // added
      i18n, // added
    }
```

And then recreate an instance of the Picker. React example:
```
const EmojiPicker: FC<EmojiMartPickerProps> = (props) => {
  const randomStrRef = useRef((Math.random() + 1).toString(36).substring(7));
  const ref = useRef<HTMLDivElement>(null);
  const [renderCount, setRenderCount] = useState(0);

  useEffect(() => {
    renderCount && (new Picker({
      ...props,
      ref,
    }));

  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [renderCount]);

  useEffect(() => {
    setRenderCount(renderCount + 1);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.i18n, props.theme, props.native, props.set, props.i18n]);

  return <div key={`emojimart-${randomStrRef.current}-${renderCount}`} ref={ref}/>;
}
```

**Comment by EtienneLem** [comment]
Should be fixed in db1725f

**Comment by dpatra** [comment]
> Should be fixed in [db1725f](https://github.com/missive/emoji-mart/commit/db1725f3cf34edcf64813081f6ac920ea96f4060)

Any release plans??

**Comment by EtienneLem** [comment]
v5.2.0 has been released.

**Comment by staniel359** [comment]
@EtienneLem Thank you.

**Comment by robaweb** [comment]
@EtienneLem thank you! 
But the `i18n` prop is still static, could you make it as reactive as well?

**Comment by EtienneLem** [comment]
> @EtienneLem thank you! But the `i18n` and `locale` props are still static, could you make them reactive as well?

Right, yes that can be done
