### ISSUE TITLE
window is not defined in next build 

### ISSUE THREAD

**Issue by Lexpeee** [missive/emoji-mart#597]
I'm getting a build error upon build in m[y NextJS app. Wonder what's our workaround for this one. 
![image](https://user-images.githubusercontent.com/30643024/168158239-8c5998a2-1ad3-4b1f-b866-0de467cd4c13.png)

**Comment by EtienneLem** [comment]
See [#575 ](https://github.com/missive/emoji-mart/issues/575#issuecomment-1111323710), will add documentation soon.
