### ISSUE TITLE
ReferenceError: window is not defined in /node_modules/emoji-mart/dist/index.js

### ISSUE THREAD

**Issue by hrithin220900** [missive/emoji-mart#599]
I am facing this error when i try to use emoji-mart using next-js, tried most comon fixes available on the internet but none seemed to work. Please fix this issue.
![issue](https://user-images.githubusercontent.com/65213514/168423339-2dffaad5-a009-407c-a15d-ac114ea5ae14.png)

**Comment by EtienneLem** [comment]
See [#575 ](https://github.com/missive/emoji-mart/issues/575#issuecomment-1111323710), will add documentation soon.

**Comment by hrithin220900** [comment]
Thank You, problem was solved!!
