### ISSUE TITLE
Return an IMG element instead of a SPAN

### ISSUE THREAD

**Issue by armandofreire** [missive/emoji-mart#60]
Hi there guys!

First of all, thanks for the awesome work with emoji-mart! I just realized the component <Emoji /> returns 
something like this for the grinning emoji, for example:

`<span class="emoji-mart-emoji"><span style="width: 24px; height: 24px; display: inline-block; background-image: url(&quot;https://unpkg.com/emoji-datasource@2.4.4/sheet_google_64.png&quot;); background-size: 4100%; background-position: 65% 37.5%;"></span></span>`

Is there any possiblity to specify what type of element we would receive as return of the `<Emoji />` component? For example, transforming the` <span><span/></span>` to a single `<img />` element solved a few problems with my implementation!

Or to make it simpler: is there any way to setup the `<Emoji />` to return an `<img />` instead of a couple of spans?

EDIT: or the data that will compose the emoji? Like the BG position and stuff?

Thanks a lot guys! <3

**Comment by EtienneLem** [comment]
> or the data that will compose the emoji? Like the BG position and stuff?

Yeah, I was thinking that perhaps the `Emoji` component could have a `render` props that could receive all the data needed. When present, the component would call `props.render` instead of using the default `<span>` technique. Would that work for you?

**Comment by armandofreire** [comment]
Oh, it looks great! I currently have a function that returns an `<Emoji ... />` and passes it to the render method but in that case would I be able to grab these props of the component before rendering, so I can decide whether to render an `<img/>` or a `<span/>`, for example?

Anyways, thank you so much for your attention! :D

**Comment by darklightblue** [comment]
This will also fix the issue where you can't copy emojis.

You can just add the `:code:` on the `alt` so when you highlight it, it is being selected and copied.

**Comment by satyapendem** [comment]
Hi @EtienneLem ,

I'm using emoji mart in non react I just exposed `Emoji` and I'm just using `Emoji({ html: true, set: 'apple', emoji: emojiName, size: 22 })`. From this how I can get the `<img />` html. Please help me.

**Comment by daiict218** [comment]
Can we prioritise it. I'm facing the same issue while using `emoji-mart` with draft-js

**Comment by daiict218** [comment]
I can open up a PR for `nimble-picker` which can behave as renderProps (if some prop is coming) and pass on the data to be rendered to the component

**Comment by darklightblue** [comment]
I forked this diff and added the image element:

https://github.com/missive/emoji-mart/compare/master...darklightblue:T6276-image-tags?expand=1

I didn't bother to create a PR coz I don't think it's the correct fix for my end tho (and the way I code it is not really good and I was able to solve the issue on css side without editing the library). You can use it as a reference tho.

**Comment by darklightblue** [comment]
If you want to make it so you can copy-paste it, you can actually pass the `:code:` as a children when generating `NimbleEmoji`:

In my case:

```
const emojiComponent= NimbleEmoji({
   emoji,
   html: true,
   data,
   size: 18 // change the line height and font size on css based on this
   set: 'emojione',
   sheetSize: 32.
   children: :code: here
})
```

then on your css (of course you can change the values here):
```
.emoji-mart-emoji {
    font-size: 1.3em;
    line-height: 1em; 
}
```

and it worked like a charm

**Comment by daiict218** [comment]
Hey @darklightblue, whenever I'll render 

```
const emojiComponent= NimbleEmoji({
   emoji,
   html: true,
   data,
   size: 18 // change the line height and font size on css based on this
   set: 'emojione',
   sheetSize: 32.
   children: :code: here
})
```

It'll give me a string of `image-url` being the background image of span as the `nimble-picker` gives me a string 

```
return `<${Tag.name} style='${style}' aria-label='${label}' ${
      title ? `title='${title}'` : ''
    } class='${className}'>${children || ''}</${Tag.name}>`
```
And Tag is hardcoded as span in there. I just want the image-url so that I can customise the element that I want to render as emoji

**Comment by daiict218** [comment]
Well, I guess I'll need the image-url and background position in the sprite where emoji is rendered and the sprite as well 😛

**Comment by daiict218** [comment]
I tried 
```

const getEmoji = ({ emoji, set, size }) => NimbleEmoji({
  emoji,
  html: true,
  data,
  size,
  set,
  sheetSize: 32,
  children: `<span style="z-index: -1; color: transparent;display: inline-block; transform: translateY(-3px)">${emoji.native}</span>`,
});
```

```
return (
    <span dangerouslySetInnerHTML={{ __html: emojiComponent }}></span>
  );
```

But I'm facing the same issues of cursor not available just after the emoji.

**Comment by baldarian** [comment]
Are there any news on this ?

It would be also a good solution to pass the `tagName` as a prop (img, span or whatever) and then it would be used to render the JSX with the passed tag.

What do you think ?

**Comment by danilkinkin** [comment]
Are there any news on this ?

`children` in `Emoji` component solves the problem with copying the line, but does not solve the problem with the selection

![image](https://user-images.githubusercontent.com/10831688/114866624-dbd29180-9e04-11eb-9cee-66e07e233476.png)

**Comment by EtienneLem** [comment]
In latest version, `<em-emoji>` uses image by default.
