### ISSUE TITLE
There is a wrong with webpack of use emoji-mart v5. 

### ISSUE THREAD

**Issue by yzsn123** [missive/emoji-mart#602]
client?0555:159 ./node_modules/emoji-mart/dist/index.js 1816:23
Module parse failed: Unexpected token (1816:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         return darkMedia.matches ? 'dark' : 'light';
|     }
>     handleClickOutside = (e)=>{
|         const { element: element  } = this.props;
|         if (e.target != element) {

**Comment by mohit-s96** [comment]
We had the same issue. Turns out it was due to the outdated webpack version. Updated webpack and it works fine now.

**Comment by Haraldson** [comment]
Well is it officially incompatible with Webpack 4.x? If not I’d rather see this fixed, as upgrading to Webpack 5 is a *big* undertaking.
