### ISSUE TITLE
Keep getting this error | Module not found: Error: Can't resolve 'emoji-mart/css/emoji-mart.css'

### ISSUE THREAD

**Issue by DaltonOtineru** [missive/emoji-mart#603]
Trying to use the Emoji picked in my react application but it keeps throwing this error. I used create-react-app to create the application. I'm importing and using it as such... I've included the package.json if that would help anyone figure out whats going on. I'd appreciate any advice, thanks!

**import { Picker } from 'emoji-mart';
import 'emoji-mart/css/emoji-mart.css';**
![Screen Shot 2022-05-24 at 2 54 16 PM](https://user-images.githubusercontent.com/91712332/170138657-a940ec66-3dca-4dea-b863-1f63eb5331da.png)
![Screen Shot 2022-05-24 at 2 55 30 PM](https://user-images.githubusercontent.com/91712332/170138777-7c880a8b-09d5-45ce-9b02-37fea88a080d.png)

**Comment by EtienneLem** [comment]
The new v5.0.0 doesn’t require you to manually inject CSS anymore, see https://github.com/missive/emoji-mart#react
