### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by jpezninjo** [missive/emoji-mart#605]
Hey my team is running into this error after upgrading from 3.0 to 5.0

"Must use import to load ES Module: /Users/xxxx/fractal/frontend/node_modules/emoji-mart/dist/index.js"

Usage is as so -

>import { Picker } from 'emoji-mart'

**Comment by peZhmanParsaee** [comment]
@jpezninjo I have the same issue, and I think that it is related to Node.js version that you are using. If a previous version of Node like 12 or before is used, then you can upgrade the Node.js version if it is possible to see what happens. Also remember that it can causes other side effects, so be careful

**Comment by EtienneLem** [comment]
I believe this should be fixed in **v5.2.0**. Both ESM and CommonJS builds are available and should be selected automatically by your bundler.

**Comment by jpezninjo** [comment]
was able to update and have successful usage in my app. thanks!
