### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by ai** [missive/emoji-mart#62]
Having ChangeLog is very important for every open-source project. Here is main reasons: [keepachangelog.com](http://keepachangelog.com/).

For example, I found 0.5 release. It is major release. Is it safe to update? Commits could not answer me, because I am not familiar with project’s internal architecture. So I can miss important changes.

@EtienneLem for example, all my open source projects (Autoprefixer, PostCSS) always have ChangeLog :)

**Comment by EtienneLem** [comment]
Agreed, sorry about that. From now on changes will be in https://github.com/missive/emoji-mart/releases
