### ISSUE TITLE
Error while running jest tests

### ISSUE THREAD

**Issue by kurund** [missive/emoji-mart#633]
I am getting the below error while running the test suite. It seems to be working fine in the browser.

```
● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kurund/....../node_modules/emoji-mart/dist/index.js:2768
    export {$724e43cd4d4265a7$export$2e2bcd8739ae039 as Picker, $8b28a44b07620e42$export$2e2bcd8739ae039 as Emoji, $e43013e6209d8d65$export$2e2bcd8739ae039 as SearchIndex, $2e94d13d43a3b87d$export$2e2bcd8739ae039 as FrequentlyUsed, $205291deb9107ba0$export$2cd8252107eb640b as init, $205291deb9107ba0$export$2d0294657ab35f1b as Data, $205291deb9107ba0$export$dbe3113d60765c1a as I18n};
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React, { useEffect, useRef } from 'react';
      2 | import data from '@emoji-mart/data';
    > 3 | import { Picker } from 'emoji-mart';

```

I am using "emoji-mart": "^5.1.0", "@emoji-mart/data": "^1.0.2",

**Comment by RustamY** [comment]
Hi, I also encountered the same error. Did you manage to fix it?

**Comment by kurund** [comment]
@RustamY 

Not yet, still awaiting a response on this ticket. If not, I guess I will have to revert to the older version.

**Comment by kurund** [comment]
@EtienneLem 

I would really appreciate any suggestions to resolve this and would be happy to help. Thank you.

**Comment by RustamY** [comment]
> @RustamY
> 
> Not yet, still awaiting a response on this ticket. If not, I guess I will have to revert to the older version.

@kurund What version did it work in?

**Comment by kurund** [comment]
@RustamY 

We previously used `"emoji-mart": "^3.0.0"`

**Comment by EtienneLem** [comment]
I think this is also fixed by #619

**Comment by kurund** [comment]
@EtienneLem Thanks.

Are you planning a new release anything soon? It would really help!

**Comment by jovpet** [comment]
@EtienneLem this has not been fixed by #619. I've pulled the latest version, built it and the error with jest is still there.

**Comment by EtienneLem** [comment]
Have you followed the steps as explained in the Jest error?

> Here's what you can do:
     **• If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.**
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

**Comment by kurund** [comment]
adding the below mock fixed the issue for us.

```
jest.mock('emoji-mart', () => {
  return {
    Picker: () => {
      return null;
    },
  };
});

```
