### ISSUE TITLE
Click event listener not being removed after cleanup.

### ISSUE THREAD

**Issue by thatguyjono94** [missive/emoji-mart#635]
In `Picker.js`, the class adds an event listener `document.addEventListener('click', this.handleClickOutside)` on the `componentDidMount` lifecycle method. However there is no cleanup to remove this event listener when the component unmounts.

This is bad for two reasons:

1) The click event will always fire regardless which route you're own (event routes without the emoji plugin).

2) Using the `onClickOutside` prop will always fire this method on click events and you could potentially receive an error like `setState() on an unmounted component` react error if you have changed routes.

This should be fixed ASAP as it's just bad to have an event fire like that for EVERY click on your app.

**Comment by EtienneLem** [comment]
Fixed in #590
