### ISSUE TITLE
getEmojiDataFromNative equivalent in v5 ?

### ISSUE THREAD

**Issue by Ethorsen** [missive/emoji-mart#636]
Hi there,

I'm using this function in v3 to convert native emoji bytes to emoji-mart data.  Is there an equivalent in v5 or is there any plan to bring back this feature?

Thank you
Eric

**Comment by EtienneLem** [comment]
The equivalent is by using `SearchIndex`, it should be a lot more performant than before since it relies on the search index.

```js
const results = avait EmojiMart.SearchIndex.search('🤞🏼')
const emojiData = results[0]

if (emojiData) {
  // …
}
```

Leaving the issue open as a reminder to document this.

**Comment by Bilb** [comment]
Hey, you should probably remove `export function getEmojiDataFromNative(nativeString: any): Promise<any>;` as it is not working and that SearchIndex is indeed what we need to use now. Thanks!
