### ISSUE TITLE
is-emoji-supported/src/is-emoji-supported.ts' file: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rlocatelli9** [missive/emoji-mart#647]
Hello!

I have updated the lib emoji-mart for the latest (5.1.0) that is available here: https://www.npmjs.com/package/emoji-mart
But, I received an error after restarting the project react: 
_____________
Failed to parse source map from './node_modules/emoji-mart/dist/node_modules/is-emoji-supported/src/is-emoji-supported.ts' file: Error: ENOENT: no such file or directory, open './node_modules/emoji-mart/dist/node_modules/is-emoji-supported/src/is-emoji-supported.ts'
____________
I have seen that in the emoji-mart module doesn't exist the node_modules folder inside her.
![image](https://user-images.githubusercontent.com/36084116/180081124-45ada2da-16b2-4b9f-8928-2a6430374847.png)

## I tried
I ran the command in the sequence:
`rm -rf node_modules`
`rm -rf package-lock.json`
`npm cache clear --force`
`npm install`
> But, nothing was resolved.

## Environment:
Windows 10 with WSL 2
node: v16.14.2
npm: 8.5.0
React: 17.0.2

Does someone know how I resolve it?

**Comment by EtienneLem** [comment]
Issue would need to be addressed here: https://github.com/koala-interactive/is-emoji-supported/issues/17

**Comment by arcoirisapp** [comment]
Hi Robson, you find any solution ?

Thanks.

> Hello!
> 
> I have updated the lib emoji-mart for the latest (5.1.0) that is available here: https://www.npmjs.com/package/emoji-mart But, I received an error after restarting the project react:
> 
> Failed to parse source map from './node_modules/emoji-mart/dist/node_modules/is-emoji-supported/src/is-emoji-supported.ts' file: Error: ENOENT: no such file or directory, open './node_modules/emoji-mart/dist/node_modules/is-emoji-supported/src/is-emoji-supported.ts'
> 
> I have seen that in the emoji-mart module doesn't exist the node_modules folder inside her. ![image](https://user-images.githubusercontent.com/36084116/180081124-45ada2da-16b2-4b9f-8928-2a6430374847.png)
> 
> ## I tried
> I ran the command in the sequence: `rm -rf node_modules` `rm -rf package-lock.json` `npm cache clear --force` `npm install`
> 
> > But, nothing was resolved.
> 
> ## Environment:
> Windows 10 with WSL 2 node: v16.14.2 npm: 8.5.0 React: 17.0.2
> 
> Does someone know how I resolve it?

**Comment by marekves** [comment]
> Hi Robson, you find any solution ?
> 
> Thanks.
> 
> > Hello!
> > I have updated the lib emoji-mart for the latest (5.1.0) that is available here: https://www.npmjs.com/package/emoji-mart But, I received an error after restarting the project react:
> > Failed to parse source map from './node_modules/emoji-mart/dist/node_modules/is-emoji-supported/src/is-emoji-supported.ts' file: Error: ENOENT: no such file or directory, open './node_modules/emoji-mart/dist/node_modules/is-emoji-supported/src/is-emoji-supported.ts'
> > I have seen that in the emoji-mart module doesn't exist the node_modules folder inside her. ![image](https://user-images.githubusercontent.com/36084116/180081124-45ada2da-16b2-4b9f-8928-2a6430374847.png)
> > ## I tried
> > I ran the command in the sequence: `rm -rf node_modules` `rm -rf package-lock.json` `npm cache clear --force` `npm install`
> > > But, nothing was resolved.
> > 
> > 
> > ## Environment:
> > Windows 10 with WSL 2 node: v16.14.2 npm: 8.5.0 React: 17.0.2
> > Does someone know how I resolve it?

+1
