### ISSUE TITLE
React > 15.5 deprecating React.Proptypes  

### ISSUE THREAD

**Issue by AdamTyler** [missive/emoji-mart#65]
React is moving proptypes to a separate package in version 16 and in the meantime logging warnings.  PropTypes are being used directly in various components currently causing the following warning `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by EtienneLem** [comment]
I haven’t been following the discussion on that, is it recommended to simply drop `PropTypes` altogether or to use the separate package?

**Comment by AdamTyler** [comment]
The solution is to use the separate `prop-types`.  Their blog post can be found [here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)
