### ISSUE TITLE
the icons do not appear in picker

### ISSUE THREAD

**Issue by arcoirisapp** [missive/emoji-mart#655]
Hello,  the icons do not appear in picker, what do you think ? 
i use react and v5.2.0, thanks

import data from '@emoji-mart/data'
import Picker from '@emoji-mart/react'

Picker    data={data}    set={KEY_EMOJI_SET}          emojiSize={22}

![image](https://user-images.githubusercontent.com/75837492/181302085-21fa42ef-12d8-441f-bd22-50be1be533b6.png)

**Comment by EtienneLem** [comment]
Make sure you import and use the Twitter data when using the Twitter set:

```js
import data from '@emoji-mart/data/sets/14/twitter.json'
```

**Comment by arcoirisapp** [comment]
That was it, thank you very much for responding so quickly,

**Comment by tettoffensive** [comment]
@EtienneLem this should be in the readme (if it is I don't see it)

**Comment by EtienneLem** [comment]
> @EtienneLem this should be in the readme (if it is I don't see it)

Indeed! We could also make it possible to detect which dataset is being imported and `console.warn` when it doesn’t match the `set` provided.
