### ISSUE TITLE
can't set the properties without defaults

### ISSUE THREAD

**Issue by Sadman95** [missive/emoji-mart#683]
![Screenshot_1](https://user-images.githubusercontent.com/86881892/186133435-9a3f0987-7eb6-40ad-accb-e46e0ad16d16.png)

**Comment by EtienneLem** [comment]
> can't set the properties without defaults

I’m not sure what you are referring to, but the error message suggests that you have not @emoji-mart/react to your `devDependencies`, is that possible?
