### ISSUE TITLE
Passing different category props does not change the shown categories after first mount

### ISSUE THREAD

**Issue by chriskevini** [missive/emoji-mart#685]
If I pass the prop categories={[ "people", "nature",]} on first mount then all subsequent mounts will only show those two categories no matter what prop is passed.

**Comment by EtienneLem** [comment]
Are you using the latest version and the @emoji-mart/react wrapper? See https://github.com/missive/emoji-mart#react

**Comment by chriskevini** [comment]
I've created a minimal reproducible example: https://codesandbox.io/s/upbeat-mclean-us5j3f?file=/src/App.js
