### ISSUE TITLE
maxFrequentRows="0" not work

### ISSUE THREAD

**Issue by alexbakers** [missive/emoji-mart#695]
Hello, friends.

I added 
`maxFrequentRows="0"`
`maxFrequentRows={0}`
`maxFrequentRows="none"`

But 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/98721968/189725319-a0b2b091-92f1-42af-99fc-4e6d4879c089.png">

React 18.

**Comment by aubreythreadgill** [comment]
Thanks for submitting, Alex. I'm experiencing the same issue. Were you able to solve it?

I also tried negative values, which had the impact of showing one, single emoji in the 'Frequently used' section. 

![image](https://user-images.githubusercontent.com/94575293/199134697-2f999080-95ed-4cde-8012-30fe7f8741c4.png)

**Comment by EtienneLem** [comment]
@aubreythreadgill Sorry this fix hasn’t been released yet. I wanted to address a few PRs / issues before doing so, notably the TypeScript one. A new version will soon be released.

**Comment by aubreythreadgill** [comment]
Excellent, thank you very much for your reply Etienne, and for this wonderful package 🙏🏻
