### ISSUE TITLE
"yarn dev" server errors without showing emoji

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [missive/emoji-mart#713]
After `yarn build`ing locally, running `yarn dev` gives a server that has a runtime error in the console:

```plaintext
Uncaught ReferenceError: React is not defined
    at Object.<anonymous> (example-emoji-component.html:3480:32)
    ...
```

I tried adding React to the `<head>` in `layout.html`:

```html
<script
  crossorigin
  src="https://unpkg.com/react@18/umd/react.development.js"
></script>
```

...but that exposed a second error:

```plaintext
Uncaught (in promise) ReferenceError: Emoji is not defined
    at EmojiElement.connectedCallback (example-emoji-component.html:4030:58)
```

<img width="836" alt="screenshot of the examples page with no interactive example" src="https://user-images.githubusercontent.com/3335181/194626127-2e53b21f-40c6-484c-a16a-dba8ba56f9ee.png">

**Comment by EtienneLem** [comment]
Not sure where this is coming from 🤔. React is not a dependency, it doesn’t need to be included.

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
