### ISSUE TITLE
Virtualize or lazy-render the list of emoji

### ISSUE THREAD

**Issue by JustinDrake** [missive/emoji-mart#72]
At the moment it seems all images are rendered at the same time during load. My gut feel is performance would improve drastically if images where lazily rendered when scrolling. (See for example this library https://github.com/dinbror/blazy.)

**Comment by vkartaviy** [comment]
Btw - **Slack** uses https://github.com/bvaughn/react-virtualized for that https://slack.engineering/rebuilding-slacks-emoji-picker-in-react-bfbd8ce6fbfe?gi=e7eb80a7d19f

**Comment by nolanlawson** [comment]
Looks like a duplicate of #6
