### ISSUE TITLE
When using the categories attribute, custom categories are not working

### ISSUE THREAD

**Issue by imfycc** [missive/emoji-mart#722]
## example：

[![Edit upbeat-rubin-uf0vve](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-rubin-uf0vve?fontsize=14&hidenavigation=1&theme=dark)

## expected：
If there is a custom attribute, it is expected to display custom categories, not affected by the categories attribute

**Comment by EtienneLem** [comment]
This is the expected behavior; when providing custom categories order, you need to take your custom categories into consideration. In your example, you need to include the `github` category somewhere in your `categories` array.
