### ISSUE TITLE
Unexpected token  /node_modules/emoji-mart/dist/module.js:1261:55

### ISSUE THREAD

**Issue by lujiajian1** [missive/emoji-mart#727]
Hello! Thanks for building emoji-mart.
I have a problem with my project.
![image](https://user-images.githubusercontent.com/33251973/201288001-75ebbb8f-7831-4022-9c16-60e4f0a7cd6a.png)
![image](https://user-images.githubusercontent.com/33251973/201288143-d5e79e51-c0dd-45e8-8b71-d6456a7db31d.png)
Thanks

**Comment by EtienneLem** [comment]
Can you tell me what bundler you are using?

**Comment by EtienneLem** [comment]
Should be fixed in **v5.3.2**

**Comment by Smileghostin** [comment]
I have simillar problem, but i use emoji-market v5.3.2
Bundler - webpack


![bad_day1](https://user-images.githubusercontent.com/44057308/201520724-6e0474b4-f386-45d8-b2fd-dd3bb1dc5f2c.png)
![bad_day2](https://user-images.githubusercontent.com/44057308/201520729-7dc43d70-241e-4feb-a2fe-c68ae06b3265.png)
![bad_day3](https://user-images.githubusercontent.com/44057308/201520774-d3f09905-11aa-45d6-86e9-500fc960d6ca.png)

**Comment by lujiajian1** [comment]
When I used v5.3.2, the problem was solved, thanks.
