### ISSUE TITLE
Is there a type definition file for @emoji-mart/data in @emoji-mart v5?

### ISSUE THREAD

**Issue by hatsu38** [missive/emoji-mart#733]
I am using emoji-mart v3 in a TypeScript project.
I would like to upgrade to Emoji-mart v5.

```tsx
import data from '@emoji-mart/data'
import Picker from '@emoji-mart/react'

function App() {
  return (
    <Picker data={data} onEmojiSelect={console.log} />
  )
}
```
When I write the above code, I get the following error
Is there any way to upgrade to emoji-mart v5 in a TypeScript project?
<img width="795" alt="スクリーンショット 2022-11-12 19 40 03" src="https://user-images.githubusercontent.com/16137809/201470389-bf9ba559-90be-46f3-9a0e-5e119fa2fd24.png">
> Cannot find module '@emoji-mart/data' or its corresponding type declarations.

**Comment by kmlbss** [comment]
I'm having the same problem in my next js application.  
I seacrhed about it and found that you can install @emoji-mart/react  and import data from it. this was not the solution for me again..

**Comment by kurund** [comment]
I have explicitly defined types for `@emoji-mart-react`  which works for me.

```js
declare module '@emoji-mart/react';
```

**Comment by arnovanstaden** [comment]
adding `declare module '@emoji-mart/react';` to my global.d.ts file solved the issue for me

**Comment by phil-loops** [comment]
> I am using emoji-mart v3 in a TypeScript project. I would like to upgrade to Emoji-mart v5.
> 
> ```tsx
> import data from '@emoji-mart/data'
> import Picker from '@emoji-mart/react'
> 
> function App() {
>   return (
>     <Picker data={data} onEmojiSelect={console.log} />
>   )
> }
> ```
> 
> When I write the above code, I get the following error Is there any way to upgrade to emoji-mart v5 in a TypeScript project? <img alt="スクリーンショット 2022-11-12 19 40 03" width="795" src="https://user-images.githubusercontent.com/16137809/201470389-bf9ba559-90be-46f3-9a0e-5e119fa2fd24.png">
> 
> > Cannot find module '@emoji-mart/data' or its corresponding type declarations.

We were in a similar situation. I still don't know how to get accurate types, but [this solution](https://github.com/missive/emoji-mart/discussions/736) allowed me to at least load the component.

**Comment by hatsu38** [comment]
Thank you! I tried your solution and it worked.
