### ISSUE TITLE
next js app server error when displaying emoji-mart component Picker

### ISSUE THREAD

**Issue by kmlbss** [missive/emoji-mart#735]
I am using emoji-mart in my next js application. I installed  @emoji-mart/react and emoji-mart and import data, Picker .But in the browser side this error  is showing :
![2022-11-14_01-53-13](https://user-images.githubusercontent.com/49821804/201546416-f3117fb3-bd5e-4cbb-9972-8db2aa31f847.png)

**Comment by phil-loops** [comment]
I ran into a similar issue -- I noticed that this kind of error only occurred when I loaded the page - never from the hot-reloading.

[My solution ](https://github.com/missive/emoji-mart/discussions/736 was to lazily load the component

**Comment by imranbarbhuiya** [comment]
@EtienneLem can you do a new release with the fix or can u provide me an older version that works
