### ISSUE TITLE
TS compiler throws errors

### ISSUE THREAD

**Issue by apoorv-mishra** [missive/emoji-mart#749]
Running into the following errors upon `yarn tsc` :point_down: 

```js
node_modules/emoji-mart/dist/index.d.ts:1:46 - error TS2307: Cannot find module 'components/HTMLElement' or its corresponding type declarations.

1 import { HTMLElement as _HTMLElement1 } from "components/HTMLElement";
                                               ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/emoji-mart/dist/index.d.ts:162:41 - error TS2307: Cannot find module 'bundle-text:./PickerStyles.scss' or its corresponding type declarations.

162 export { default as PickerStyles } from 'bundle-text:./PickerStyles.scss';
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fails on both local and [CI](https://app.circleci.com/pipelines/github/outline/outline/9693/workflows/6ed94781-fdb0-489e-ae16-165e8b9c81b9/jobs/21303)

**Version** :point_down: 
```
emoji-mart@5.3.3
ts@4.7.4
react@17.0.2
node@16.16.0
```

**Comment by EtienneLem** [comment]
I sort of see how `tsc` would throw; I’m not sure if these lines should be there. Probably is a Parcel bug. That being said, given you have `node_modules` in your `tsconfig` `exclude`, is it supposed to evaluate this `d.ts` file?

**Comment by apoorv-mishra** [comment]
Well...it shouldn't but there seems to be a [gotcha](https://www.typescriptlang.org/tsconfig#exclude) if I'm not misunderstanding it.

> Important: exclude only changes which files are [include](https://www.typescriptlang.org/tsconfig#include)d as a result of the include setting. A file specified by exclude can still become part of your codebase due to an import statement in your code, a types inclusion, a /// <reference directive, or being specified in the [files](https://www.typescriptlang.org/tsconfig#files) list.

**Comment by stanvanheumen** [comment]
I'm getting the same error using the latest version (5.5.0).

**Comment by apoorv-mishra** [comment]
No longer facing this as of v5.5.2. Thanks :pray:
