### ISSUE TITLE
category images not taking proper height in IE

### ISSUE THREAD

**Issue by iamsaksham** [missive/emoji-mart#75]
There seems to be an issue that category(SVG) images are not taking height and width as given in the SVG viewport.
The SVG i.e category images takes a greater height.

I even found the fix that `max-height` can be given to images so that in case they dont take height from SVG viewport then it can be a rescue. It looks like `max-width: 18px` is given but not max-height

Do you want me to create a pull request that fixes the height of category images?

**Comment by iamsaksham** [comment]
#77 I've created this pull request. Please consider merging it

**Comment by iamsaksham** [comment]
Any update on this? @EtienneLem

**Comment by EtienneLem** [comment]
Sorry been away for the past 2 weeks, got a lot of things I need to catch up on before I can look into this
