### ISSUE TITLE
Bug: Broken truncation of Preview text

### ISSUE THREAD

**Issue by yelyzavetatymoshenko** [missive/emoji-mart#762]
After release of v5.4.0 there is a problem with long emoji name in Preview. The text is not truncated but instead just changing width of the picker and causing jumpiness. 

Steps to reproduce:
1. Hover over on random emojis and see how Picker width is changing depending on the text in Preview.

Also, see gif.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/95352205/208854142-46e5b8a3-499d-4b5e-ae04-c6235cabfb8e.gif)

**Comment by fongfan999** [comment]
I'm also having this issue +1

**Comment by rottenpen** [comment]
I fixed it https://github.com/missive/emoji-mart/pull/767

**Comment by fongfan999** [comment]
Thanks @rottenpen
