### ISSUE TITLE
找不到模块 @emoji-mart/data 或其相应的类型声明

### ISSUE THREAD

**Issue by coderluojz** [missive/emoji-mart#764]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/74349832/209905253-4c90a81b-d7e2-487d-8fda-c07caa73576b.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/74349832/209905277-8e1045de-9909-4b69-be9b-4f2ab9837753.png">
我安装了 `@emoji-mart/data` 提示找不到模块 `@emoji-mart/data` 或其相应的类型声明，并且我的 node_modules 里面没有找到相应的类型声明，例如 `index.d.ts`。

**Comment by EtienneLem** [comment]
Should be fixed in `@emoji-mart/data` **v1.1.1**

**Comment by coderluojz** [comment]
多久可以发布v1.1.1
