### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property.

### ISSUE THREAD

**Issue by mugishap** [missive/emoji-mart#771]
I was using emoji mart in nextjs when I encountered an error stating `JSX element class does not support attributes because it does not have a 'props' property.` 

Project setup
NodeJS - 16.18.1
Next - 12.1.6
React - 17.0.2

![Screenshot from 2023-01-11 16-25-12](https://user-images.githubusercontent.com/94197472/211832534-bd3e0aa4-4596-4351-b989-8c5587ae0414.png)
![Screenshot from 2023-01-11 16-26-54](https://user-images.githubusercontent.com/94197472/211832564-d189f4fb-fc77-4670-b415-03e78b4d24fc.png)

Anyone with an idea can give a hand. Thanks in advance

**Comment by EtienneLem** [comment]
1. Are you using `@emoji-mart/react`? See documentation: https://github.com/missive/emoji-mart#react
2. The `Picker` element doesn’t support a `style` prop. You should style a parent div.
