### ISSUE TITLE
The latest version is broken

### ISSUE THREAD

**Issue by sergei-zelinsky** [missive/emoji-mart#783]
Hello there,

First of all, thank you for such a beautiful library ❤️

It looks like the latest version `v5.5.1` is broken. It doesn't work on the examples page or locally.

**Error message:**

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
```

Examples page: https://missiveapp.com/open/emoji-mart/example-emoji-component.html

<img width="1728" alt="Screenshot 2023-01-22 at 16 57 28" src="https://user-images.githubusercontent.com/19428086/213922681-6c781836-4dda-4fd8-b306-f2e8aadb5f05.png">

I hope that helps. Thanks!

**Comment by EtienneLem** [comment]
Fixed in **v5.5.2**
