### ISSUE TITLE
Is it possible to build this as a standalone Electron app?

### ISSUE THREAD

**Issue by Darthagnon** [missive/emoji-mart#787]
[Winmoji](https://github.com/ryanSN/winmoji) exists as an alternative for Windows' built-in emoji picker, but it is lacking in features and bundles Google Analytics. I was wondering whether there was any way of building Emoji Mart as a standalone Electron program in a similar way, or if anyone had already done it?

**Comment by Simon-Laux** [comment]
you inspired me to make https://github.com/Simon-Laux/tauri-emoji-mart-app. tauri is really awesome, it was really quick to throw this together.

**Comment by EtienneLem** [comment]
Thanks a lot for sharing @Simon-Laux. I will go ahead and close this issue, as this is not quite an issue per se. I would invite people to submit issues / feature requests on that repo 🙃

**Comment by Simon-Laux** [comment]
BTW: Meanwhile @vemonet also made a tauri app for it: https://github.com/vemonet/EmojiMart
Compared to my experiment, this project has more features, is actively maintained and even has a flathub store release (next to windows and macOS releases).
