### ISSUE TITLE
Update for Emoji-Version 15.0

### ISSUE THREAD

**Issue by schmoninator** [missive/emoji-mart#851]
Hi, 
is there any plan to release picker-data for emoji version 15.0?
The release has been out since September '22 and the next version (15.1) is already set to be released in September of this year.
Best, Simon

**Comment by schmoninator** [comment]
Apparently, there already is a pull request for this:
https://github.com/missive/emoji-mart/pull/844

could you please merge it?

**Comment by romansp** [comment]
It seems that PR has been merged but no new release has been created. Is there anything that can be done to have it available on `npm`?

Also [v15.1 has been approved](https://emojipedia.org/emoji-15.1) and [v16 is supposedly coming out in late 2024](https://emojipedia.org/emoji-16.0). 

15.1 PR in emoji-data repo: https://github.com/iamcal/emoji-data/pull/235

**Comment by jiaweing** [comment]
![image](https://github.com/missive/emoji-mart/assets/33184869/3400170a-86a7-4b67-851b-0af6e3a00caa)

Is this why the v15 dataset is missing in the package?
