### ISSUE TITLE
Question: How to put apple smile in my input? (React)

### ISSUE THREAD

**Issue by uncle-ara** [missive/emoji-mart#859]
Dear colleagues, developers, hello!

I'm using apple smileys in my project (react). And I have already achieved that I made my own Emoji component, now my smileys are rendered in messages. 

But I can not achieve the same in the input. Because my input prop value accepts a string, it can't accept a component. That's my problem.

Maybe someone has already done this, please share your idea or experience. Thank you all!

P.S This library doesn't work for me -- react-input-emoji

**Comment by VictorYeung0725** [comment]
@uncle-ara  did you manage to solve this problem 
i have the same issue

**Comment by ThenTech** [comment]
You can only display native emojis in string form. To display components, you'll need to use a div with contenteditable instead and add them as child components instead of appending to a string.
