### ISSUE TITLE
Hiding search input

### ISSUE THREAD

**Issue by zgrybus** [missive/emoji-mart#864]
1. How to hide search input? I don't see relevant prop for it :( I wouldn't like to render it.
2. How to hide `Pick an emoji` section?

**Comment by deeeeno** [comment]
searchPosition='none'

**Comment by jamesmacfie** [comment]
Hide the `Pick an emoji`section with `previewPosition="none"`

![image](https://github.com/missive/emoji-mart/assets/1654201/590bc90c-4add-40fe-8b28-c4e54a164e55)
