### ISSUE TITLE
Using exclude breaks search

### ISSUE THREAD

**Issue by sebmor** [missive/emoji-mart#89]
```
  <Picker exclude={['nature', 'activity', 'objects', 'flags', 'places', 'symbols', 'custom']} />
```

Results in ``Uncaught TypeError: Cannot read property 'sort' of undefined``

**Comment by nkzawa** [comment]
Same here. Setting `include={[]}` is a workaround for now.

**Comment by EtienneLem** [comment]
Oh, that would explain how I wasn’t able to reproduce on the demo page. Fixing and releasing a new version to NPM in a few.
