### ISSUE TITLE
How to remove the preview part?

### ISSUE THREAD

**Issue by stvncode** [missive/emoji-mart#924]
I have been trying to remove it by css like :
```
#preview {
  display: none !important;
}
```
or 
```
em-emoji-picker #preview {
  display: none !important;
}
```
but nothing is working.

**Comment by EtienneLem** [comment]
You can use `previewPosition: 'none'`

**Comment by stvncode** [comment]
Thank you for your quick answer @EtienneLem ! I just have a last question sorry, is there a way to change the position of the portal by any way ? (I want it at the top and not the bottom)

**Comment by EtienneLem** [comment]
By portal you mean the preview? If so it would be `previewPosition: 'top'`.

You can see all options here: https://missiveapp.com/open/emoji-mart

**Comment by stvncode** [comment]
No i mean the Picker position. When i click on my trigger, i want the Picker to appear at the top and not the bottom.

**Comment by EtienneLem** [comment]
Ah, well that part isn’t handled by EmojiMart, but by your own code.

**Comment by stvncode** [comment]
For those who wonder, this is working : 
```
<div style={{ transform: "translate(0, -260px)" }}>
          <Picker
            data={data}
            emojiButtonSize={30}
            onClickOutside={() => {
              setOpen(false)
            }}
            onEmojiSelect={console.log}
            perLine={6}
            previewPosition="none"
          />
        </div>
```
