### ISSUE TITLE
emoji-mart not working with Tippy.js Popover

### ISSUE THREAD

**Issue by keval-key** [missive/emoji-mart#939]
Here is a reproducible link:
https://codesandbox.io/p/sandbox/emoji-demo-st6l7v

The emoji works fine the first time. However, if you select an emoji and click again to reopen the button, you may notice that some emojis are hidden.

Additionally, after scrolling, some emojis may still be hidden.

**Comment by keval6706** [comment]
Can be fixed by: [onShow](https://atomiks.github.io/tippyjs/v6/all-props/#onshow) [onHide](https://atomiks.github.io/tippyjs/v6/all-props/#onhide)
