### ISSUE TITLE
Bad image?

### ISSUE THREAD

**Issue by Luchanso** [missive/emoji-mart#98]
Hi, I have some problem with twemoji 64.png and 32.png. And I don't know how to name it in English, maybe "Artifacts"?
![img](https://user-images.githubusercontent.com/2098777/28925943-fdf9290a-786e-11e7-99bd-9e79e9325afa.png)

I think, it's because sprite sheet is not correct
![untitled2](https://user-images.githubusercontent.com/2098777/28926452-7ee9d018-7870-11e7-82ec-7c6ba0736a17.png)

**Comment by EtienneLem** [comment]
👋  @Luchanso 

I feel like this could be some browser image resampling issues (perhaps mixed with the twemoji sheet compression). What I did on my own projects to prevent such issues and serve pixel-perfect emojis is to use sheets that are exactly @2x the size I use. For example, emojis are 20px throughout the app, so I actually took the `64.png` sheet and resized it to be `40.png` (`1960px x 1960px`). That way images are sharp (and noise-free) on both normal and high resolution screens.

**Comment by Luchanso** [comment]
Okey, thank you for help, I'll try to experiment with it

**Comment by Luchanso** [comment]
@EtienneLem No, it's not working, I was make size={16} in props and use 32.png:
![image](https://user-images.githubusercontent.com/2098777/28927336-f43409fe-7872-11e7-8298-14f15fc70a11.png)

**Comment by Luchanso** [comment]
It's reproduce on Chrome Windows and on Chrome Ubuntu

**Comment by EtienneLem** [comment]
Closing as this needs to be handled by emoji-data
